### ISSUE TITLE
Zu wenig Datenpunkte

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.lovelace#1]
Hallo,
Bei mir wird nur das angezeigt, wie und wo holt er sich die Datenpunkte? Ich habe nur 4 DP?

![Screenshot (3314)](https://user-images.githubusercontent.com/41079106/58562268-34a4db00-8229-11e9-8dea-9742fc7abb10.png)

Was ist eigentlich Entität?

[lovelace.log](https://github.com/ioBroker/ioBroker.lovelace/files/3232819/lovelace.log)

**Comment by sigi2345** [comment]
> HUE, RGB und Color Temperature wird von Lovelace noch nicht unterstützt.
> Was anderes habe ich nicht im log gefunden.

Ja das verstehe ich, diese 5 DP wurden automatisch erstellt. Wie bekomme ich jetzt Zb. ein Thermostat von Homematic rein?

**Comment by holger05** [comment]
Ich habe auch noch nicht verstanden, wie die Datenpunkte (Entitäten?) festgelegt werden. Aber ich habe schon viel mehr wie du. Thermostat ist auch dabei.
![grafik](https://user-images.githubusercontent.com/33962350/58626726-beaa7d80-82d5-11e9-836a-aa8e537fafd4.png)
Ich habe versucht mit Rollen und Funktionen zu arbeiten, allerdings ändert sich nix.

**Comment by sigi2345** [comment]
Ja, kann uns das wer erklären?

**Comment by GermanBluefox** [comment]
> > HUE, RGB und Color Temperature wird von Lovelace noch nicht unterstützt.
> > Was anderes habe ich nicht im log gefunden.
> 
> Ja das verstehe ich, diese 5 DP wurden automatisch erstellt. Wie bekomme ich jetzt Zb. ein Thermostat von Homematic rein?

Thermostat muss Function und Raum haben. Kannst du Screenshot von dem Thermostat machen. Wie hier?
![image](https://user-images.githubusercontent.com/4582016/58705498-b757a280-83af-11e9-98f2-4188018fceb7.png)

**Comment by sigi2345** [comment]
> > > HUE, RGB und Color Temperature wird von Lovelace noch nicht unterstützt.
> > > Was anderes habe ich nicht im log gefunden.
> > 
> > 
> > Ja das verstehe ich, diese 5 DP wurden automatisch erstellt. Wie bekomme ich jetzt Zb. ein Thermostat von Homematic rein?
> 
> Thermostat muss Function und Raum haben. Kannst du Screenshot von dem Thermostat machen. Wie hier?

![Screenshot (3347)](https://user-images.githubusercontent.com/41079106/58715388-08bf5c00-83c7-11e9-91e5-4c5457dd3142.png)

**Comment by GermanBluefox** [comment]
> > > > HUE, RGB und Color Temperature wird von Lovelace noch nicht unterstützt.
> > > > Was anderes habe ich nicht im log gefunden.
> > > 
> > > 
> > > Ja das verstehe ich, diese 5 DP wurden automatisch erstellt. Wie bekomme ich jetzt Zb. ein Thermostat von Homematic rein?
> > 
> > 
> > Thermostat muss Function und Raum haben. Kannst du Screenshot von dem Thermostat machen. Wie hier?
> 
> ![Screenshot (3347)](https://user-images.githubusercontent.com/41079106/58715388-08bf5c00-83c7-11e9-91e5-4c5457dd3142.png)

Was für ein Gerät ist das? Ist mir leider vollig unbekannt und da fehlen wichtige Rollen.
Wenn du aber SET_TEMPERATURE mit der Rolle "level.temperature" versiehst dann sollte das Gerät erkannt werden.

**Comment by sigi2345** [comment]
> Was für ein Gerät ist das?

https://www.elv.at/homematic-heizkoerperthermostat-1.html

**Comment by holger05** [comment]
![grafik](https://user-images.githubusercontent.com/33962350/58793414-58d03580-85f6-11e9-9a9d-612b7fa42fb0.png)

Habe gerade gefunden, dass im Setting der Datenpunkte jetzt separat was für lovelace was einstellen kann. Dort kann man dann auch den Typ bestimmen und schon taucht der DP in der List auf.

**Comment by dirkhe** [comment]
Ich habe mal ein wenig in den code geschaut und ich bin der Meinung, dass im typedetector  die states für getAllStatesInDevice nicht richtig aufgelöst werden. siehe https://github.com/ioBroker/ioBroker.type-detector/issues/2
