### ISSUE TITLE
UI optimieren

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.lovelace#10]
Unter ioBroker Lovelace wird das "Hamburger" Menü nicht verwendet, daher wird dieses ausgeblendet. Für die angelegten Tabs sieht das dann aber blöd aus. Es wäre besser, wenn die Tabs linksbündig anfangen.
Ich hab ein Bild angehängt, dass es verdeutlichen soll (der Platz links neben dem Haus).

![](https://i.imgur.com/2SSWAMo.png)

Außerdem wäre eine Touch Optimierung wünschenswert, sprich das swipen zwischen Tabs.

**Comment by GermanBluefox** [comment]
Swipe Anforderung bitte gegen HASS schreiben.
