### ISSUE TITLE
Alias devices not shown in config

### ISSUE THREAD

**Issue by MeisterTR** [ioBroker/ioBroker.lovelace#100]
i have some alias devices, but they are not shown in the lovelace config.

![2020-08-14_17h06_01](https://user-images.githubusercontent.com/6328382/90264277-22748400-de51-11ea-9744-1b5239b9bb2b.png)
![2020-08-14_17h06_19](https://user-images.githubusercontent.com/6328382/90264287-256f7480-de51-11ea-8d72-074a477ed235.png)
![2020-08-14_17h06_37](https://user-images.githubusercontent.com/6328382/90264302-2a342880-de51-11ea-9aa7-745ca886b180.png)

**Comment by Garfonso** [comment]
Currently Lovelace does not support "dimmer" devices without ON state.

Workaround would be to add this (if there is no such state on the device, you could add an alias to the SET-state with read: val !== 0 and write: val > 0).
