### ISSUE TITLE
No history data with Nginx reverse proxy

### ISSUE THREAD

**Issue by allesgutewarweg** [ioBroker/ioBroker.lovelace#102]
Hello,

i've moved from OpenHAB to ioBroker some weeks ago. Everything went fine but i have a strange issue with my reverse proxy. 

Lovelace is working fine but i don't get any historical data so the graphes and history cards aren't working. 

The issue only occurs when i enable authentication in Nginx. Without authentication turned on everything is fine too.

`map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen       9091 ssl;
    server_name  XXXXXX;

    auth_basic "Restricted";
    auth_basic_user_file  /etc/nginx/htpasswd;

    ssl                  on;
    ssl_certificate      XXXXXX.cer;
    ssl_certificate_key  XXXXXX.key;

    ssl_session_timeout  10m;
    ssl_protocols TLSv1.3;
    ssl_ciphers  ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-DES-CBC3-SHA:AES128:HIGH:!aNULL:!MD5:!EDH;
    ssl_prefer_server_ciphers   on;

    access_log            /var/log/nginx/iobroker.access.log;

    location / {
      proxy_pass              http://XXX.XXX.XXX.XXX:8091;
      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;

      proxy_read_timeout  90;
    }

    location /api/websocket {
        proxy_pass            http://XXX.XXX.XXX.XXX:8091/api/websocket;
        proxy_http_version 1.1;
        proxy_set_header        Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

    error_page   500 502 503 504  /50x.html;

    location ~ /\.ht {
        deny  all;
    }
}`

In my opinion this issue is related to the **'authorization: Bearer no_token'** header. But i don't know how to further debug this problem or solve it.

Can somebody assist me, please?

**Comment by Apollon77** [comment]
What does the browser console say? Maybe some requests blocked by cors or such?

**Comment by Garfonso** [comment]
Hm.. last time I checked, reverse proxy was not really supported by the HomeAssistant / Lovelace guys and they have a lot of issues with that... I'm quite impressed you managed to come as far. :-)

I think this is in the lovelace code itself: https://github.com/Garfonso/home-assistant-polymer/blob/iob/src/util/fetch-with-auth.ts#L19 -> "auth.accessToken" gets filled with "no_token" in case authorization is disabled in lovelace.
Maybe could you try to enable authorization in lovelace (too)?

I'm not really sure if I am able to solve this.

**Comment by alpenhase83** [comment]
Thank you  very much for your fast replies.

> Hm.. last time I checked, reverse proxy was not really supported by the HomeAssistant / Lovelace guys and they have a lot of issues with that... I'm quite impressed you managed to come as far. :-)

I'm working in a datacenter so Nginx reverse proxies are our daily business :) 

Until now my panels are not very beautifull but they work without bigger problems:

![firefox_DpyESq8LPq](https://user-images.githubusercontent.com/31478347/91288719-9ee05e80-e791-11ea-8294-06ff45c4d075.png)
![firefox_1eHa6j5jRO](https://user-images.githubusercontent.com/31478347/91288724-a0118b80-e791-11ea-9b45-88ffb04a2d12.png)

> I think this is in the lovelace code itself: https://github.com/Garfonso/home-assistant-polymer/blob/iob/src/util/fetch-with-auth.ts#L19 -> "auth.accessToken" gets filled with "no_token" in case authorization is disabled in lovelace.
> Maybe could you try to enable authorization in lovelace (too)?

I give it a try when i'm home again. 

> What does the browser console say? Maybe some requests blocked by cors or such?
No issues so far. The only thing is the 401 ob this URL: https://XXXXXX:9091/api/history/period/2020-08-25T09:52:54.975Z?filter_entity_id=input_boolean.statusVars_Sichtschutz,input_boolean.statusVars_Sonnenschutz&end_time=2020-08-26T09:52:54.975Z&minimal_response

CURL TESTS:

Not working (with -H 'authorization: Bearer no_token'):
`curl 'https://USER:PASSWORD@XXXXXX:9091/api/history/period/2020-08-25T09:52:54.975Z?filter_entity_id=input_boolean.statusVars_Sichtschutz,input_boolean.statusVars_Sonnenschutz&end_time=2020-08-26T09:52:54.975Z&minimal_response' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0' -H 'Accept: */*' -H 'Accept-Language: de,en-US;q=0.7,en;q=0.3' --compressed -H 'Referer: https://XXXXXX:9091/lovelace/default_view' -H 'authorization: Bearer no_token' -H 'Connection: keep-alive'`

Working (without -H 'authorization: Bearer no_token'):
`curl 'https://USER:PASSWORD@XXXXXX:9091/api/history/period/2020-08-25T09:52:54.975Z?filter_entity_id=input_boolean.statusVars_Sichtschutz,input_boolean.statusVars_Sonnenschutz&end_time=2020-08-26T09:52:54.975Z&minimal_response' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0' -H 'Accept: */*' -H 'Accept-Language: de,en-US;q=0.7,en;q=0.3' --compressed -H 'Referer: https://XXXXXX:9091/lovelace/default_view' -H 'Connection: keep-alive'`

**Comment by alpenhase83** [comment]
@Garfonso Enabling auth in Lovelace didn't change anything.

**Comment by Garfonso** [comment]
Hm.. today I did some more research with lovelace and reverse proxy and ended up with the same issue... :-( 
Did you find any solution? 

Not sure how to solve / debug this TBH.

**Comment by Garfonso** [comment]
Hm.. it seems somehow for `/api/history` no auth header is sent.. still not sure why...
Current solution is to ignore auth for this type of URL (in Apache2 in a RequireAny block add something like `Require expr "(%{REQUEST_URI} =~ /api.history/)"` )

**Comment by petterpet** [comment]
Did anyone find a solution?
