### ISSUE TITLE
JavaScript runtime errors after enabling authentication

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.lovelace#103]
**Describe the bug**  
If auth is enabled in the adapter JS starts throwing exceptions after logging in. Lovelace UI shows up, but stays empty apart from the headers (i.e. no cards).

**To Reproduce**  
1. Enable auth
2. Log in

**Expected behavior**  
No errors, cards show up.

**Screenshots & Logfiles**  
```
Uncaught (in promise) TypeError: Cannot read property 'is_admin' of null
    at HTMLElement.value (chunk.9c9dde6a141ac9e7240c.js:29686)
    at HTMLElement.update (app.c15f410f.js:1)
    at HTMLElement.performUpdate (app.c15f410f.js:1)
    at HTMLElement._enqueueUpdate (app.c15f410f.js:1)
```

**Versions:**  
 - Adapter version: 1.2.6
 - JS-Controller version: 3.1.5
 - Node version: v12.18.3
 - Operating system: RPI/docker

**Comment by agross** [comment]
Related to this piece of code:

```
${this.hass.user.is_admin && !this.hass.config.safe_mode ? o.f`
                          <mwc-list-item
                            aria-label=${this.hass.localize("ui.panel.lovelace.menu.configure_ui")}
                            @tap="${this._editModeEnable}"
                          >
                            ${this.hass.localize("ui.panel.lovelace.menu.configure_ui")}
                          </mwc-list-item>
                        ` : ""}
```

**Comment by Garfonso** [comment]
Hm... I'll look into that. I'm pretty sure I tested authorization a few times, though. 

So one question: did you try to delete browser cache? Lovelace itself changed very much in this release.

**Comment by agross** [comment]
Yes, I also tried in Incognito mode. What is really strange is that the problem only occurs after the first successful login in Incognito.

**Comment by agross** [comment]
I made a little video that shows that it sometimes work. (Images, BTW, still don't show up.)

https://www.dropbox.com/s/vwae24hw9rg40ar/Kapture%202020-08-26%20at%2013.47.11.mp4?dl=0

**Comment by alpenhase83** [comment]
I've tested Lovelace with auth yesterday to fix my issue (https://github.com/ioBroker/ioBroker.lovelace/issues/102). I can't reproduce your issue, my installation is working fine with auth enabled. 

Repo: latest
