### ISSUE TITLE
Updated smart/friendly names are not reflected by the UI

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.lovelace#108]
**Describe the bug**  

An entity that has its friendly name updated shows the old friendly name.

**To Reproduce**  

```json
{
  "type": "device",
  "common": {
    "name": "Next Event Weather",
    "smartName": "München"
  },
  "native": {},
  "from": "system.adapter.javascript.0",
  "user": "system.user.admin",
  "ts": 1600881514308,
  "_id": "alias.0.GW.Next Event Weather",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

This channel is considered to be a weather forecast. There are states below it that are required for this to work, but I didn't show them above.

The important bit is the `common.smartName` which is `München`.

![image](https://user-images.githubusercontent.com/16245/94116722-aefc6400-fe4b-11ea-8db1-52b111a3452b.png)

When the `common.smartName` is changed to something else:

```json
{
  "type": "device",
  "common": {
    "name": "Next Event Weather",
    "smartName": "Flensburg"
  },
  "native": {},
  "from": "system.adapter.javascript.0",
  "user": "system.user.admin",
  "ts": 1600881514308,
  "_id": "alias.0.GW.Next Event Weather",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

This change is not reflected by the weather or entity card.

**Expected behavior**  

Cards should display the new friendly name.

**Versions:**  
 - Adapter version: 1.2.6
 - JS-Controller version: 3.1.5
 - Node version: 12
 - Operating system: docker

**Additional context**  

I need some dynamic weather forecasts for my work travel. The locations change frequently. Restarting the Lovelace adapter should not be required to update the locations on the UI.

The code that creates the weather channel and its states and updates the `smartName` is [here](https://github.com/agross/iobroker-scripts/blob/master/0/GW/Next_Event_Weather.ts#L162-L164). `smartName` updates are also not reflected when doing them by hand (i.e. through the object editor).

**Comment by Garfonso** [comment]
Does lovelace use the smartName at all? I always thought smartName was only for iot (I.e. Alexa, Google Home,...).

If you switch on debug logging in the lovelace adapter, do you see that it recreates entities when you change the smartName of an object? (will be delayed by 5 seconds and output a lot in debug mode).

Not sure if the cards do support something like this at all. Hm.

**Comment by agross** [comment]
You can see the smart name (München) in the screenshot above. The adapter contains code to extract it from the ioB state. Changing it might not trigger an update by the entity creator. That's my guess.
