### ISSUE TITLE
1.2.7 breaks HomeMatic thermostats

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.lovelace#112]
**Describe the bug**  

Since 1.2.7 HomeMatic thermostats display `N/A` temperature and "Auto".

**To Reproduce**  

1. Upgrade to 1.2.7

<img width="468" alt="2020-10-20_15-14-50" src="https://user-images.githubusercontent.com/16245/96591313-6b303980-12e7-11eb-9db6-cf9dde0b563c.png">

The upper card is a `simple-thermostat`.

**Expected behavior**  

With 1.2.6:

<img width="461" alt="2020-10-20_16-49-39" src="https://user-images.githubusercontent.com/16245/96603402-47bfbb80-12f4-11eb-9ed2-db978e4f4e02.png">

**Versions:**  
 - Adapter version: 1.2.7
 - JS-Controller version: 3.1.5
 - Node version: 12
 - Operating system: docker

**Comment by agross** [comment]
> Could you post a Screenshot of the entity

```
climate.HmIP_BWTH_000C9A498DC865_1

(nothing in the States column)

current_temperature: hm-rpc.1.000C9A498DC865.1.ACTUAL_TEMPERATURE
friendly_name: HmIP-BWTH 000C9A498DC865_1
icon: mdi:thermostat
max_temp: 30.5
min_temp: 4.5
temperature: hm-rpc.1.000C9A498DC865.1.SET_POINT_TEMPERATURE
unit_of_measurement: °C
```

> and the IoBroker objects

![image](https://user-images.githubusercontent.com/16245/96606366-7e4b0580-12f7-11eb-8dce-350c854513bb.png)

![image](https://user-images.githubusercontent.com/16245/96606656-cc600900-12f7-11eb-89b9-1beadafc7f54.png)


> Also I see that it says "auto" for you in 1.2.6, too. Does it always display auto there?

Not sure, I mostly use simple-thermostat because it uses up less screen real estate. I only added the normal thermostat for the screenshots above. Right now the "Auto" is missing, but I don't know why.

**Comment by Garfonso** [comment]
I will try to reproduce the problem with your information. But it will take a few days.

**Comment by agross** [comment]
Sure, in the meantime I downgraded to 1.2.6. Let me know if you need
further assistance.

Beste Grüße,

Alex
--
+49 175 4107268
Tiny phone, tiny mail

**Comment by thost96** [comment]
Same for me with EQ-3 Max thermostat. Same JS Controller, NodeJS version also on docker.

**Comment by JB1985** [comment]
Same here with Bosch Smart Home. I open a bug in simple-thermostat https://github.com/nervetattoo/simple-thermostat/issues/171

**Comment by Garfonso** [comment]
They won't be able to help you. It is a bug in 1.2.7. I already fixed it (if someone wants to try, you can install lovelace from github. Version is not jet bumped, though).
I am working on a few more things and then will release a new beta to latest (not sure when, though)

**Comment by agross** [comment]
Installing https://github.com/ioBroker/ioBroker.lovelace/commit/88873e9696a15276d364d37ddbe8dcf165fa9e83 fixed my HomeMatic thermostats.

The "Auto" string is missing, though:

1.2.6:
![image](https://user-images.githubusercontent.com/16245/98093451-44960500-1e88-11eb-91e3-7bf6b85be50e.png)

master:
![image](https://user-images.githubusercontent.com/16245/98093511-54ade480-1e88-11eb-9bb1-1a1404fec39a.png)

**Comment by Garfonso** [comment]
@agross 
honestly I do not really know where the 'auto' string in 1.2.6 comes from. Is it important? :smile:

**Comment by agross** [comment]
Since I use simple-thermostat it doesn't really matter. Reverting is fine with me!
