### ISSUE TITLE
Manually added state with 'switch' type has assumed_state attribute with true value

### ISSUE THREAD

**Issue by shady2k** [ioBroker/ioBroker.lovelace#115]
**Describe the bug**  
Manually added state with 'switch' type has assumed_state attribute with true value.

**Expected behavior**  
Manually added state with 'switch' type has no assumed_state attribute.

**Versions:**  
 - Adapter version: 1.2.7
 - JS-Controller version: 3.1.6
 - Node version: v10.21.0
 - Operating system: Debian GNU/Linux

**Additional context**  
This behaviour from 0.2.5 (2019-11-18) (algar42) Switch entity updated to show two state buttonts in GUI (assumed_state attrbute set to true) server.js:
entity.attributes.assumed_state = true;

**Comment by Garfonso** [comment]
I'm fine with removing it. @algar42 did you have a use case in mind when adding it? 

Maybe we could set assumed_state to true, if the object has the read flag set to false? That *should* indicate, we can not really get the current status in ioBroker, right?

**Comment by algar42** [comment]
the assumed_state attribute was added to switch in order to show 'two buttons' in GUI, like this:
![image](https://user-images.githubusercontent.com/40002726/98249123-f3b90600-1f86-11eb-885f-9d11bc799815.png)
If you want to display usual slider-switch you can use input_boolean type for manual state. it has the same behavior. 
here is input_boolean:
![image](https://user-images.githubusercontent.com/40002726/98249185-06333f80-1f87-11eb-8ffa-d371478e1a1b.png)

**Comment by Garfonso** [comment]
ok, this should be documented, at least... but documentation is an issue anyway, I fear.. hm. :-(

**Comment by shady2k** [comment]
But if I use input_boolean type, I get warning in UI: 
Entity not available

**Comment by Garfonso** [comment]
> 
> 
> But if I use input_boolean type, I get warning in UI:
> Entity not available
> ![image](https://user-images.githubusercontent.com/3366415/98250107-1a2b7100-1f88-11eb-8fdd-c5fb8a2fec8e.png)

Yes, because the entity id changes to `input_boolean.bedroom_conditioner_eco` 😄  You need to adjust the code of the card and then it should work.

**Comment by shady2k** [comment]
Yes, it works, thank you. Just a little strange, what you use assumed_state property in wrong case. I believe, that it must be used if we don't know status of device. Supposed, need to add another type to show two buttons in UI.

**Comment by Garfonso** [comment]
I, too, think that using the `assumed_state` attribute in this was on the switch entity is not the best solution. So I would still propose to use it only if the ioBroker-Object has `read` set to `false`. What's your opinion, @algar42 ?

On the other hand, switch entities can also be automatically created from `socket` and `button` device types.

**Comment by algar42** [comment]
Guys, it is just a strange name of an option in lovelace :)
![image](https://user-images.githubusercontent.com/40002726/98252810-6330f480-1f8b-11eb-8842-dfac1c93676a.png)

this option has nothing to do with the state value itself. it just controls how switch is displayed in GUI.

**Comment by shady2k** [comment]
> Guys, it is just a strange name of an option in lovelace :)
> ![image](https://user-images.githubusercontent.com/40002726/98252810-6330f480-1f8b-11eb-8842-dfac1c93676a.png)
> 
> this option has nothing to do with the state value itself. it just controls how switch is displayed in GUI.

Oh, I understand.

**Comment by shady2k** [comment]
My suggestion: delete line that forced assumed_state for swith type to true and add ability to add property in entity card configuration, so user can change UI view if neccessary.

**Comment by algar42** [comment]
it is not possible to change this property in GUI in already created entity.
What is possible is to add assumed_state property to the Object.common of iobroker object and use this in server.js code to set the entity property. (set to true by default, if user did not add this to iobroker object) 
Default true is because it is better to have two different switches in GUI by default. One is _switch_ with two buttons, and another is _input_boolean_ with slider_switch.

**Comment by shady2k** [comment]
Sounds reasonable. But the problem is that objects added automatically have one radio button, while objects added manually have two buttons. It is very uncomfortable.

**Comment by algar42** [comment]
hmm.. for which type of objects lovelace adapter automatically creates a switch entity?

**Comment by Garfonso** [comment]
Like I said above for socket and button (as defined in type-detector).

**Comment by Garfonso** [comment]
Honestly I am still in favor to make this based on read-flag. Read-Flag in ioBroker object should be false for switches where the state is unknown so this translates well to "assume_state" and then it makes sense to have two buttons. But in the other cases one button/slider to toggle if fine, not?

**Comment by shady2k** [comment]
> hmm.. for which type of objects lovelace adapter automatically creates a switch entity?

In my case, it is all objects with switch.light role
