### ISSUE TITLE
 Text Wert eines State Sensors

### ISSUE THREAD

**Issue by MarcelMertens** [ioBroker/ioBroker.lovelace#12]
Hallo,

besteht die Möglichkeit z.b. in der Sensor Card den Text Wert eines State Sensors auszugeben statt die Zahl?
Siehe auch:
https://forum.iobroker.net/topic/12140/gel%C3%B6st-text-wert-eines-states-ausgeben-anstatt-nummer

**Comment by Garfonso** [comment]
Ist das noch aktuell? Ich sehe im Code, dass es sowas zum teil schon gibt.

**Comment by Garfonso** [comment]
Ein Monat keine Reaktion -> scheint kein drignendes Problem. Es müsste auch mit entity input_select erreichbar sein.
