### ISSUE TITLE
'Entity name ... already in use' with multiple Instances

### ISSUE THREAD

**Issue by nooxnet** [ioBroker/ioBroker.lovelace#128]
I added a second Lovelace instance. When I wanted to create Lovelace entities via the wrench symbol in the objects tree and used the same names as with the first instance I got the error "Entity name 'x' already in use".

It seems like this only happens if the entity for the first instance has been defined and saved some seconds ago. So it does not happen, if you create the entities for both instances at once. It also only happens when you start defining the entity by checking the checkbox "Aktiviert" and selecting the entity type first. So:

**Workaround**
Start by filling out the entity name ("Entitätsname") first and select the type and activate it as a second step.

**To Reproduce**  
1. You have two Lovelace instances
2. Go into objects tree. 
3. Select an entry where you have already defined a Lovelace entity for the first Lovelace instance.
4. Fill out the settings for the second Lovelace instance by starting with "Activated"/"Aktiviert" and the entity type. Then use the same name as for the first instance.

**Expected behavior**  
Every instance has it's own naming space. So names for one instance can be used for the second too.

**Versions:**  
 - Adapter version: 1.3.3
 - JS-Controller version: 3.1.6
 - Node version: 12.20.0
 - Operating system: Raspbian

**Comment by Garfonso** [comment]
Yes, this is broken. I currently try to understand the code leading to this...

The cases where it works for a few seconds are caused because the lovelace instances wait for 5 seconds after the last object change to recreate all entities.
