### ISSUE TITLE
Add support for airContition device

### ISSUE THREAD

**Issue by PeterVoronov** [ioBroker/ioBroker.lovelace#129]
Hi.
I have a moes ZigBee thermostat
![image](https://user-images.githubusercontent.com/66964358/103143473-62147c00-471f-11eb-98ca-4745d5743986.png)
But for me is unclear, how I can show it in lovelace termostate (climate).
Can you share an example or point on docs?

And more over, I tried to install simple-thermostat, but without lucky 
![image](https://user-images.githubusercontent.com/66964358/103143490-bb7cab00-471f-11eb-81b5-5a510e48c604.png)
And I have an error
![image](https://user-images.githubusercontent.com/66964358/103143501-01397380-4720-11eb-90c7-34a15d55c28f.png)

**Comment by Garfonso** [comment]
Hi,

the thermostat (climate entity) has to use the "auto create entity" path, because it constists of multiple entities, ie this: https://github.com/ioBroker/ioBroker.lovelace#auto -> set room & function for the device (i.e. the "folder"). 
Then you can check with the deivces adapter ( https://github.com/iobroker/iobroker.devices ) if a device of type thermostat is created. If so lovelace should create an entity for the device and you can use that for the thermostat card.

Simple-Thermostat card:
Did you restart the lovelace adapter after installing the card and also reloaded lovelace in the browser? The card should work.

**Comment by PeterVoronov** [comment]
Thanks. 
Too small paragraph ;-), didn't notice it 
It's working now 
![image](https://user-images.githubusercontent.com/66964358/103151127-f31d3e80-4783-11eb-83b1-82cc215522a9.png)
But where I can read more about required attributes for the thermostat, to make the simple-thermostat from existing 
![image](https://user-images.githubusercontent.com/66964358/103151165-5d35e380-4784-11eb-957f-5045be1959fb.png)
more close to this one 
![image](https://user-images.githubusercontent.com/66964358/103151154-3c6d8e00-4784-11eb-8675-15810ac3b1ad.png) or 
![image](https://user-images.githubusercontent.com/66964358/103151157-4abbaa00-4784-11eb-9f4f-6b8db3990edc.png)

**Comment by Garfonso** [comment]
The iobroker device supports humidity state (role needs to start with `humidity` and it must be of type `number`). This should then also be added as attribute to the entity.

Currently ioBroker does not support a `state` state for thermostats. There is a new device type `airCondition` which could help with that, but it is not yet supported in this adapter.

**Comment by Garfonso** [comment]
I change the title of the issue and will leave this here for now. I try to do a stable release and am in the process of fixing bugs right now and try to postpone new features after that release (at lest such big ones)

**Comment by PeterVoronov** [comment]
Thanks!

**Comment by Garfonso** [comment]
I hope you are still around. I am currently working on airConditioner/thermostat support and will probably need your help in testing.

**Comment by PeterVoronov** [comment]
> I hope you are still around. I am currently working on airConditioner/thermostat support and will probably need your help in testing.

Hi. Will try to help

**Comment by Garfonso** [comment]
> 
> 
> > I hope you are still around. I am currently working on airConditioner/thermostat support and will probably need your help in testing.
> 
> Hi. Will try to help

Is your thermostat detected as device, i.e. do you see an entry in the devices tab in admin for the thermostat? Either as thermostat or as airConditioning? 
(if devices tab is missing, please install devices adapter and, if possible, try version 1.x, which probably is only in latest right now).

**Comment by Garfonso** [comment]
@PeterVoronov please test with 2.0.0 release. It supports a lot more features of airConditioner / thermostat. 

Be sure that your devices are detected by devices adapter (in devices tab) and have the right states in the right places.

Also for the buttons in the thermostat card to work properly the `MODE` state needs to have a proper common.states object. Lovelace supports those modes and creates buttons for them automatically: "off". "heat". "cool", "heat_cool", "auto", "dry", "fan_only".
