### ISSUE TITLE
Zweite Instance von einem Adapter wird nicht als Entität erkannt

### ISSUE THREAD

**Issue by gravidigit** [ioBroker/ioBroker.lovelace#13]
Beispiel:
milight.0.zone1.state wird erkannt
milight.1.zone1.state wird dann nicht mehr erkannt

1. milight.0.zone1.state schalte auf aktiviert im Objeckt und setze Name und Typ, weise einer Funktionien hinzu, starte Adapter neu, wird als Entität erkannt
2. milight.1.zone1.state schalte auf aktiviert im Objeckt und setze Name und Typ, weise einer Funktionien hinzu, starte Adapter neu, wird nicht als Entität erkannt

**Versions:**  
 - Adapter version: 0.1.1
 - JS-Controller version: 1.5.12
 - Node version: 8.16
 - Operating system: debian stretch

**Comment by GermanBluefox** [comment]
Ist auch Raum beim zweiten zugewiesen?

**Comment by gravidigit** [comment]
Ja ist zugewiesen
