### ISSUE TITLE
 lovelace.0.control.theme is type string instead of boolean

### ISSUE THREAD

**Issue by thost96** [ioBroker/ioBroker.lovelace#147]
**Describe the bug**  
After upgrading to Lovelace 1.3.6 I got the following warnings logged: 

```
lovelace.0 | 2021-01-08 18:28:50.789 | warn | (12891) This object will not be created in future versions. Please report this to the developer.
lovelace.0 | 2021-01-08 18:28:50.786 | warn | (12891) Object lovelace.0.control.theme is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
```

**To Reproduce**  
1. Go to the adapter settings and set the Theme to default. 

**Expected behavior**  
This config object should be set to string instead of boolean (as defined for now). 

**Versions:**  
 - Adapter version: 1.3.5
 - JS-Controller version: 3.1.6
 - Node version: 10.19.0
 - Operating system: linux/docker

I will create a PR for this i just a moment.

**Comment by Garfonso** [comment]
Oops. Emberassing. 🙁 Thanks for the PR.

**Comment by thost96** [comment]
as PR #148 has been merged, this issue can be closed.
