### ISSUE TITLE
support for browser_mod custom card 

### ISSUE THREAD

**Issue by thost96** [ioBroker/ioBroker.lovelace#150]
**Is your feature request related to a problem? Please describe.**
I'm trying to add popups to my Lovelace dashboard to show some content only after clicking on some entities, as the more-info option doesn't support this. With the popup from https://github.com/thomasloven/hass-browser_mod#popup it is possible to display any other card as a popup like the more-info, but much more customizable as I think. Any described service on that GitHub page doesn't work for me, as I already tested debug, popup and toast from browser_mod. Maybe there is an error in the service call handling? 

**Describe alternatives you've considered**
All alternative like the popup-card also didn't work for me. Maybe there is a general issue, as these are formerly only for home assistant itself. 

**Additional context**
I would be nice to get this working with any custom card: 

![image](https://user-images.githubusercontent.com/5551251/104232591-dace4480-5450-11eb-9cfc-69d8efd65004.png)

**Comment by Garfonso** [comment]
I'm looking into this. Will need some more time for this, though.

We need to reimplement the python-services that browser mod adds to HASS in the adapter. They seem to be quite basic, but not sure what needs to be done.

**Comment by nukleuz80** [comment]
Hi,

ich habe es auch versucht zu installieren. Geht leider nicht. Das wäre für Lovelace eine super Erweiterung die Oberfläche zu füllen bzw zu stylen. 

Schließe mich also gerne an 😎

**Comment by Garfonso** [comment]
> 
> 
> Hi,
> 
> ich habe es auch versucht zu installieren. Geht leider nicht. Das wäre für Lovelace eine super Erweiterung die Oberfläche zu füllen bzw zu stylen.
> 
> Schließe mich also gerne an 😎

Hi,

also installieren sollte gehen. Ist aber etwas komplizierter. 
* https://github.com/thomasloven/hass-browser_mod/releases das neuste Zip runterladen
* aus dem Zip im Ordner `custom_components\browser_mod` die `browser_mod.js` als custom-card installieren
* dann noch hier https://github.com/thomasloven/lovelace-card-tools die card-tools.js runterladen und ebenfalls als custom-card installieren.

Dann sollte es installiert sein und (je nach lovelace adapter version) Meldungen über unbekannte service-calls kommen. :-)

Habt ihr mal Anwendungsfälle für mich? Am liebsten mit Code-Beispielen, die ich direkt in lovelace-ui reinkopieren kann.

Danke. :-)

Garfonso 

//-------------------------- tranlsation:
Hi,

install should be possible, using this steps (it is a bit more complicated than usual):
* download newest zip file from https://github.com/thomasloven/hass-browser_mod/releases
* extract the zip, go to folder `custom_components\browser_mod` and install `browser_mod.js` as custom-card like usual
* get card-tools.js from https://github.com/thomasloven/lovelace-card-tools and install as custom card as well

You should now see a lot of unknown service-call messages (depends a bit on the version of the adapter, some don't print those messages). 

If you want to help, please post yaml code that uses the browser mod in ways that you need in iobroker, so I can add support and test more easily. Thanks.

Garfonso

**Comment by nukleuz80** [comment]
@thost96 

Popups are working - check it out:
https://forum.iobroker.net/topic/34775/test-adapter-lovelace-v1-2-x/813?_=1629226216434

**Comment by Garfonso** [comment]
more support still is in the work (close to release).

**Comment by nukleuz80** [comment]
👍

**Comment by TheMBeat** [comment]
Hallo @Garfonso, wie ist der Status?

Kann dir dieser [Wrapper](https://github.com/pyscript/pyscript) evtl. helfen?

**Comment by Garfonso** [comment]
Uhm.. Status is ... uhm... I did not find time to release / repair testing and so on... hm...

You can test by installing from my fork (i.e. Expertview in admin, install from github -> url): `https://github.com/Garfonso/iobroker.lovelace` 

It will create a folder `instances` and in there a new folder for each browser. In there will be objects to control the UI. And there are convenient objects to control all (connected) UIs at once in the instances' folder, too.
