### ISSUE TITLE
Swipe Navigation on mobile devices

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.lovelace#154]
I have found a Github repository that integrates a function (Swipe Support for mobile devices) via addon into Lovelace. I would like to see this function in this adapter.

[https://github.com/maykar/lovelace-swipe-navigation](https://github.com/maykar/lovelace-swipe-navigation)

**Comment by Garfonso** [comment]
Did you try to install it as custom card? Should work from what I see in the install description.

**Comment by dontobi** [comment]
I will test it and give feedback.

**Comment by dontobi** [comment]
I have saved the js file as a custom card in the instance. However, the function is not yet given.

**Comment by randomname32** [comment]
After installing lovelace 4.x, the swiping did not work for me anymore. I was able to fix it by using the following:

https://github.com/zanna-37/hass-swipe-navigation/releases/tag/v1.13.2
