### ISSUE TITLE
allow data-url as state

### ISSUE THREAD

**Issue by grisia** [ioBroker/ioBroker.lovelace#162]
I'm trying to display images that are stored as data-url in the state in LoveLace.

I have now adjusted the _getImage function slightly. For me the adaptation works. Maybe something similar can be implemented in the official release?

```diff
--- ./lib/server.js     2021-02-28 18:10:47.432251469 +0100
+++ ./lib_cust/server.js        2021-02-28 18:14:20.301190905 +0100
@@ -3295,6 +3295,19 @@
                                     cb(null, result);
                                 }
                             });
+                        } else if (state.val.startsWith('data')) {
+                            let dataUrl = state.val;
+                            let mimeType = dataUrl.substring(dataUrl.indexOf(":")+1, dataUrl.indexOf(";"))
+                            let encoding = dataUrl.substring(dataUrl.indexOf(";")+1, dataUrl.indexOf(","))
+
+                            if (encoding.localeCompare('base64', undefined, { sensitivity: 'base' }) !== 0) {
+                                err && this.log.warn(`Wrong encoding: ${encoding}`);
+                                cb(`Wrong encoding: ${encoding}`);
+                            }
+
+                            let base64Data = dataUrl.split(",")[1]
+                            const result = {content_type: mimeType || 'image/jpeg', content: base64Data};
+                            cb(null, result);
                         } else {
                             request(state.val, {encoding: null}, (err, state, body) => {
                                 if (body) {
```

**Comment by Garfonso** [comment]
I tried to add it. But can you give me an example string of the data that can be processed with that code?

Could you try the code in my dev branch? (install with custom url and enter: `Garfonso/iobroker.lovelace#dev` ).

**Comment by grisia** [comment]
I know I'm a little late... But here is some general approach... 

The first will work too, but it will only work with the scheme:
`'data:[mime];base64,[data]'`

in situations like this (I know the calling function is `getImage` and this makes no sens but...):
`'data:text/html;charset=utf-8,%3C%21DOC~~~'`
it will generate an error 'Wrong encoding'. I think this isn't correct...

Or may be [killmenot/parse-data-url](https://github.com/killmenot/parse-data-url) is ab better approach

```ts
let dataUrl: string = '';
dataUrl = 'data:';
dataUrl = 'data:,';
//dataUrl = 'data:text/html;charset=utf-8,%3C%21DOCTYPE%20html%3E%0D%0A%3Chtml%20lang%3D%22en%22%3E%0D%0A%3Chead%3E%3Ctitle%3EEmbedded%20Window%3C%2Ftitle%3E%3C%2Fhead%3E%0D%0A%3Cbody%3E%3Ch1%3E42%3C%2Fh1%3E%3C%2Fbody%3E%0A%3C%2Fhtml%3E%0A%0D%0A';
//dataUrl = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9YGARc5KB0XV+IAAAAddEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIFRoZSBHSU1Q72QlbgAAAF1JREFUGNO9zL0NglAAxPEfdLTs4BZM4DIO4C7OwQg2JoQ9LE1exdlYvBBeZ7jqch9//q1uH4TLzw4d6+ErXMMcXuHWxId3KOETnnXXV6MJpcq2MLaI97CER3N0vr4MkhoXe0rZigAAAABJRU5ErkJggg==';
//dataUrl = 'data:text/plain;base64,SGVsbG8sIFdvcmxkIQ%3D%3D';
//dataUrl = 'data:,Hello%2C%20World%21';
dataUrl = 'data:;charset=utf-8,Hello%2C%20World%21';

/*******
 *    Syntax (https://datatracker.ietf.org/doc/html/rfc2397)
 *      dataurl    := "data:" [ mediatype ] [ ";base64" ] "," data
 *      mediatype  := [ type "/" subtype ] *( ";" parameter )
 *      data       := *urlchar
 *      parameter  := attribute "=" value
 *******/
function yetAnotherDataUrlParserWithoutRegex(dataUrl: string): any {
    const parsed: any = {};
    let dataMarkerPosition: number = -1;

    if (`${dataUrl.substring(0, 5)}` !== "data:" || (dataMarkerPosition = dataUrl.indexOf(",", 5)) < 0) {
        throw new Error(`Invalid data URI scheme was given.`);
    }

    parsed.mediaType = `${dataUrl.substring(dataUrl.indexOf(":") + 1, dataMarkerPosition)}`;

    const mediaTypeParts = parsed.mediaType.split(';').map((x: string) => x.toLowerCase());

    parsed.contentType = `${mediaTypeParts[0]}`.length === 0 ? "text/plain" : mediaTypeParts[0];

    mediaTypeParts.slice(1).forEach((attribute: string) => {
        const p = attribute.split('=');
        parsed[p[0]] = p[1] || true;
    });

    if (parsed.contentType === "text/plain") {
        parsed.charset = parsed.charset || "US-ASCII";
    }

    parsed.mediaType = parsed.contentType;
    for (let key in parsed)
        if (key !== "mediaType" && key !== "contentType" && key !== "base64")
            parsed.mediaType += `;${parsed[key]}`;

    parsed.base64 = parsed.base64 || false;
    parsed.data = dataUrl.split(",")[1] || '';

    return parsed;
}

const parsed = yetAnotherDataUrlParserWithoutRegex(dataUrl);

if(false == parsed.contentType.startsWith("image")) {
    throw new Error(`Content type: '${parsed.contentType}' is not supportet here. Only images are supportet.`);
}

let result = {
    content_type: parsed.contentType,
    content: parsed.data
};

console.log(parsed);
console.log(result);
```
[typescriptlang.org/test](https://www.typescriptlang.org/play?noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&declaration=false&target=99&jsx=0&module=0&ts=4.3.4&ssl=55&ssc=2&pln=53&pc=1&inlineSourceMap=false#code/DYUwLgBAJghmMFUBOwBcEDOYkEsB2A5hALwQDkZA3AFCzzLAnl0ypW1yIpNkuoA07APRCWDHnzAgAHmCEALMAFtglAMbyYSDOGIBXMADMAtAA5+AUgDMAYQsAmAIwARAPI2AKgE0ACgFEHAAZFFWsAwOcLQIBBaxsQ4CDgGEJrSPt7EDwHezCoyJi4+RAYKDzbMBwwUDC-JQAjECgoJqCAdXwoAHsAdziHADFK6pByu3sB4tK8iKjY23quqABPMflHMIAWXNtB9bHBxZWZ+fHJ5USrcNjZmPYxblJeTlQcJRgCECEAB0JKepgOgAbJt+DgAGoAIVcACUeoEANIAcQIXWi6OiADkAMoIeR+BAEDHRNEYhE2aJeDE2TEAWQwAGoAJzEyFIqCQjwIPzogAySJ8NiE0nkkIAisTgD1sQNgAAvDG8vw9dE2aS0yHRABSAEc1EjidEoIFcY4BpCmV4DTC1ABWBGQwIADXBDIAksTmn5wV4oH5MQA3eptRzAep4CViqxa4BeJ0w4AALRskKsMHjXTdAxhXUT2MhAAlTWKAOz2MVhonogaOLUwvwDBBIzGuJly3mBTEEYDo6T+QxQXkeDCbSGJ2mbZxu1ybGwl1w9MUEexarpiplKxwyKCxgOQyEgRMlgBWevkTJEOscegLmw8vLlPU2UCBDL8SCdtNpaidN7a0jdKArARVw-A8PA8CdF0gVpLVvjUHV7FpXkYDdJkSxsPwYSsTFAgDJBNlpABreQuidEBAiQRMcCrdFITrBBbXfIitQINjiGIYRRE4cQnkkGQ5G+ZJ8H+QEQBBfhsSRcEMHqJFTAwLMoADNQlGkIi3TFNI0i4h5GD4l5+ALEBgGALoHHGQI2i6FAyicXSeMeZgXnUTRtF0AwTHMYzTPM+xLOs2yHEcdhqCEAAqSKovC6gIHCiAEogbFljweBpAgAAKRQwG+DBUBEFhsBgNQiJAJAADocHAQxypsghRC6NQFAuIQkEMNR7CsdCAEpYvixKEpYPRuES1BSAAIj4caIAAbQgJQmhwOBlm+EAIAAXVmiBxtE4FNmmzbxv4aaWD6gaEoWqAlrAFa1ogMatpu1btqEaaMD0eonrWzbwoy7bKGm74tBgBapCQCBeri87oE4aH7tIcLhuADQtDO86gaQEHwDKhKHrgbAcHqAw1vG4hpoDGBgD0EA+uiyKhGoQw9DwNRKi6PAIGWcBojwLowGKJBnEc4AfC0HQkA6fmugMGEQE+aQMr09AsFwQhuvQFJlggABvWLErUdmsAgDGdCgDW8C10htYAXxoAbQEgFhaS0UqkB8LoMCqHB2fQPA9AaHHSGMRwaD1hKcEMTKAAMABJtb08r3vqFX8AIDLAn4CBbW662o4gABCDjtqmiAAB9S8yp2XbK93PbZjnSATzoZFcQwMqOo6s+67qIAAHggQIe91uGIH5pBeggPAQB6CB33HpAMqjt08Ap4AcCgGH4AgBAYTdTANBABaIB6QEIAIHAAyycqo+6u3Eut6gw+NsWmnKy6lo8W6mFj+PhcTj6U6EEVn-Zu0hW7t1QONHuDIICOEzlXJArta5e3ZjnKOocBoGzwEbd+MBP6rVFkgMAGAmAm1frg-BIBE5CSqBlKgZBupvxgN8DKGVpDKwJmrEgAA+CA0hypgC6LyXoZUbBiQyt3DBiUyFQHKlgqQqVKHfzjhQ26hDiEzUCOtXO5VQCEH5iQIugQIAAH5tpSFkD8YSeBproFUQQrQGitFSIuotPBajHEYETmvNQIAMqOEYYYGyfhiryFYfjXARMpAcNVgQHuxBeHDzhlgo23wmARMJsTaha8wB0M4rfJ+A0ZEzW+Jo9am1SClMcJtcuo8kDUzvgla2BSn4R0yjIuR7MFFgCURxCaFjBLWKgTrQp0iX6yJRu5SAlTxlyLcjoSAtTxoIGxMYaI2IbBujdDtJ+D8n4dPsWtGZ7kJldKyD026jSIBBPBhlB2EBSpa3wM-E5kM4ZtIyo8guRdxqHOmgAMn+Q8kAWtC4TXkecyhAKgVfLBdtAEe0oGjOhgctxSiGSkHQXHYpjztHoMfkU2ZCLxKbFIUSsSIIy4V0MJTHQVyOksCYAnDANDckd26jNapVLyChQGkgcAw0OYyJoHslJkAZFMC5mAHmfMBZC3oCgQh4tJakRlnLGQwCFXABaRHDKNLgA6EMS802nTUqQtuoneARCMAqvbm8D4IAoFDyfmPCeU8Z5zxsovGwZzUqj1uugMg2LZkQsUbda2ZAIA4BIbzSA71vjfBslISAAsqEQFcHgYATz3ifBIVoNa8bE1EPANfApez7n8vesAaZIzMG+rAAAfS+ugDpoaLmrX4E-NtLbZmnVto-FJXRQC6K6GnGRBTB3DrMmnStehq23yAA)

**Comment by Garfonso** [comment]
I don't 100% understand the case you mentioned that will fail. 
It is fine, if the function fails if there is no image in the data (as long as it won't crash the adapter), then no image will be shown.
