### ISSUE TITLE
Increase upload limit

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.lovelace#171]
**Is your feature request related to a problem? Please describe.**
I would like to use the Purifier Card. This is over 2MB in size and cannot be uploaded in the adapter.

**Describe the solution you'd like**
The upload limit would have to be raised or removed.

**Describe alternatives you've considered**
An alternative would be to add it manually via the file system. However, a manual would be necessary for this.

**Additional context**
https://github.com/denysdovhan/purifier-card/releases

**Comment by Garfonso** [comment]
you can add files via the command line like this:
`iobroker file write custom-card.js /lovelace.0/cards/custom-card.js`

Adjust custom-card.js to your needs.

I don't know where there should be an upload limit and am not sure if it is possible to resolve it in the adapter. I'll try to investigate.

**Comment by Garfonso** [comment]
Ok... I found the limit.. it is hard coded in the configuration UI... :-(
I increased the limit to 5 MB in the dev Version. If you want to try, you can install with this current URL: `Garfonso/iobroker.lovelace#dev`

**Comment by dontobi** [comment]
I just installed the dev version. Then also the Custom Card. Thank you.

**Comment by dontobi** [comment]
I'll close here. The bug has been fixed.
