### ISSUE TITLE
Scaling problem

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.lovelace#172]
I don't know if it's a bug or if you can do something about it. However, I would like to point out a problem here. Some cards are not scaled correctly depending on the device. The best way to see this is to look at the screenshots.

Screenshots:
1. Pic: Notebook
2. Pic: Smartphone
3. Pic: Tablet Portrait
4. Pic: Tablet Landscape

Card: Simple Thermostat
![Screenshot_Heizung_Desktop.png](https://user-images.githubusercontent.com/19261667/111075248-5bf49700-84e7-11eb-9a52-3142bcb52d51.png)
![Screenshot_Heizung_Smartphone.jpg](https://user-images.githubusercontent.com/19261667/111075253-6020b480-84e7-11eb-8d39-817a9940e7ba.jpg)
![Screenshot_Heizung_Tablet_H.png](https://user-images.githubusercontent.com/19261667/111075256-63b43b80-84e7-11eb-9179-8c5d51a912e1.png)
![Screenshot_Heizung_Tablet_P.png](https://user-images.githubusercontent.com/19261667/111075261-67e05900-84e7-11eb-8a2e-2939b8cc6520.png)

Card: Light
![Screenshot_Licht_Desktop.png](https://user-images.githubusercontent.com/19261667/111075337-e63cfb00-84e7-11eb-94da-78471b561698.png)
![Screenshot_Licht_Smartphone.jpg](https://user-images.githubusercontent.com/19261667/111075362-fce35200-84e7-11eb-8003-961cac594d93.jpg)
![Screenshot_Licht_Tablet_H.png](https://user-images.githubusercontent.com/19261667/111075374-0a98d780-84e8-11eb-863b-39109e2f8436.png)
![Screenshot_Licht_Tablet_P.png](https://user-images.githubusercontent.com/19261667/111075377-0f5d8b80-84e8-11eb-9671-b0d7050064f1.png)

Card: Schütter Card
![Screenshot_Rolllaeden_Desktop.png](https://user-images.githubusercontent.com/19261667/111075441-4633a180-84e8-11eb-9d78-b7268e46a408.png)
![Screenshot_Rolllaeden_Smartphone.jpg](https://user-images.githubusercontent.com/19261667/111075446-4b90ec00-84e8-11eb-86d6-1c9a3732a878.jpg)
![Screenshot_Rolllaeden_Tablet_H.png](https://user-images.githubusercontent.com/19261667/111075458-50ee3680-84e8-11eb-9e90-c3c2208950e0.png)
![Screenshot_Rolllaeden_Tablet_P.png](https://user-images.githubusercontent.com/19261667/111075464-5481bd80-84e8-11eb-8c3d-49827cf1cfe8.png)

**Comment by Garfonso** [comment]
Hi,

no this adapter is not the right place to fix these things... are those all custom cards? If so, have a look if other people are expiriencing similar issues and if there is a fix for this.
For standard cards the homeassistant/frontend repository is the right place to look for issues: https://github.com/home-assistant/frontend/issues
Please do not report an issue there, right away. It might also be fixed in the latest version. We lag behind a bit. I plan to update the frontend again when I find time.

best regards,
Achim

**Comment by dontobi** [comment]
I fixed the problems with the thermostat card and the cover card myself today. With the Thermostat Card you can set some parameters in the theme. For the Cover Card I did it myself and adjusted the whole card today. Only the Light Card causes some problems on my wife's cell phone (I don't have any screenshots) and on my tablet. The three dots protrude into the circle.

I'll close here then.
