### ISSUE TITLE
Problem bei Umlauten

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.lovelace#2]
Ich habe zwei Räume mit Umlauten (Büro und Gäste WC). Dadurch erhalte ich Fehlermeldungen.

![Screenshot_20190602-152327](https://user-images.githubusercontent.com/19261667/58761963-692ad680-854a-11e9-8c0f-02b8dab4567b.jpg)

**Comment by GermanBluefox** [comment]
Please try the version from git

**Comment by dontobi** [comment]
Leider klappt es immernoch nicht.

**Comment by GermanBluefox** [comment]
Aber die heißen etzt andres. Du musst die neu platzieren.
ä => ae
ü => ue
usw

**Comment by GermanBluefox** [comment]
Some statement?

**Comment by dontobi** [comment]
Kam leider noch nicht zum testen. Werde das morgen nachholen.

**Comment by dontobi** [comment]
Hab es getestet. Bei mir werden die Entities mit einem Umlaut nun anders angezeigt. Der Umlaut wurde durch einen Unterstrich ersetzt. Dadurch ist die Funktion nun gegeben. Schön sieht es aber nicht aus.

![](https://i.imgur.com/s1w0l7e.jpg)

**Comment by GermanBluefox** [comment]
Was kann ich machen, wenn lovelace das nicht unterstützt? Ä=>Ae ?

**Comment by GermanBluefox** [comment]
No reaction.
