### ISSUE TITLE
The graphs is not cover full period with History from InfluxDB

### ISSUE THREAD

**Issue by PeterVoronov** [ioBroker/ioBroker.lovelace#201]
**Describe the bug**  
When for the graph is selecting a quite long interval - the graphs will show not a full changes of a selected value. 

**To Reproduce**  
1. Set the history instance as a history adapter for lovelace (it is usually by default)
2. Create any graph card with quite long interval, like 72 or 144 hours.
3. See a normal graph.
![lovelace_history](https://user-images.githubusercontent.com/66964358/120216004-225a3f00-c23f-11eb-8c3b-b9e0a4422a9d.PNG)
4. Set the influxdb instance as the history adapter for lovelace.
5. Restart lovelace adapter
6. See the wrong graph
![lovelace_influx](https://user-images.githubusercontent.com/66964358/120216040-2dad6a80-c23f-11eb-8c22-a2458aacc314.PNG)

**Expected behavior**  
As you can see on images - in case of influxdb the biggest and latest value is lest, then actual one. I found the reason of this behaviour - it is an absence of the count option for the GetHistory requests.
Both adapters - history and influxdb has the same code :
history, main,js, function getHistory
```
...
        count:      parseInt(msg.message.options.count, 10) || 500,
        ...
        limit:      parseInt(msg.message.options.limit || adapter.config.limit || 2000, 10),
...
```
influxdb, main,js, function getHistory
history, main,js
```
...
        count:      parseInt(msg.message.options.count, 10) || 500,
        ...
        limit:      parseInt(msg.message.options.limit || adapter.config.limit || 2000, 10),
...
```
But only the influxDB is applied the count on the amount of the history data point, returned by the query. It can be faund in the iobroker log, when debug is enabled:
```
2021-05-31 18:43:36.187  - .[34mdebug.[39m: influxdb.0 (6263) SELECT value from "linkeddevices.0.sockets.blitzwolf.plug.boiler.energy" WHERE time <= '2021-05-28T15:43:36.755Z' ORDER BY time DESC LIMIT 1;SELE
CT * from "linkeddevices.0.sockets.blitzwolf.plug.boiler.energy" WHERE  time > '2021-05-28T15:43:36.755Z' AND  time < '2021-05-31T15:43:36.755Z' LIMIT 500;SELECT value from "linkeddevices.0.sockets.blitzwolf
.plug.boiler.energy" WHERE time >= '2021-05-31T15:43:36.755Z' LIMIT 1
```
You can see it in a middle SELECT clause - **LIMIT 500;**, it is default value for a limit, if it not set.

It can be simple fixed by adding the value of limit to the `getHistory` request options, for example before the line 
[                                aggregate: 'onchange',](https://github.com/ioBroker/ioBroker.lovelace/blob/507a6320261423805ae3e3d1f88e861a66aeab3f/lib/server.js#L1898)

The option code can look like:
```
                            const options = {
                                start: new Date(req.params.start).getTime(),
                                end: new Date(req.query.end_time).getTime(),
                                count: 10000,
                                aggregate: 'onchange',
                                user,
                            };
```
For me it fixed the issue, but may be this option has to be configurable ?
The InfluxDB log 
```
2021-05-31 18:50:46.091  - .[34mdebug.[39m: influxdb.0 (6263) SELECT value from "linkeddevices.0.sockets.blitzwolf.plug.boiler.energy" WHERE time <= '2021-05-28T15:50:46.660Z' ORDER BY time DESC LIMIT 1;SELECT * from "linkeddevices.0.sockets.blitzwolf.plug.boiler.energy" WHERE  time > '2021-05-28T15:50:46.660Z' AND  time < '2021-05-31T15:50:46.660Z' LIMIT 10000;SELECT value from "linkeddevices.0.sockets.blitzwo
lf.plug.boiler.energy" WHERE time >= '2021-05-31T15:50:46.660Z' LIMIT 1
```
![lovelace_influx_ok](https://user-images.githubusercontent.com/66964358/120217787-841ba880-c241-11eb-8201-167f9f2bd4d1.PNG)

**Screenshots & Logfiles**  
See above

**Versions:**  
 - Adapter version: 1.9.5
 - JS-Controller version: 3.2.16
 - Node version: 12.22.1
 - Operating system: Debian

**Additional context**  
No

**Comment by PeterVoronov** [comment]
It's looks like the InfluxDB adapter make the things right way, in comparsion with history, which is not applied any limit or counts

**Comment by PeterVoronov** [comment]
Appropriate Pull Request is created - [historyMaxCount is introduced to make Lovelace compatible with some History adapters (at least - InfluxDB)](https://github.com/ioBroker/ioBroker.lovelace/pull/210)

**Comment by Garfonso** [comment]
please test with version in latest ( 2.0.0 )
