### ISSUE TITLE
Lovelace Settings missing in Admin 5

### ISSUE THREAD

**Issue by thost96** [ioBroker/ioBroker.lovelace#212]
**Describe the bug**  
Lovelace's entity information can't be edited or added in the new admin 5 react UI. There is no option in the state settings anymore:
![image](https://user-images.githubusercontent.com/5551251/120783174-0b5f6980-c52b-11eb-8498-dedc1156cf76.png)

Using the old UI is a workaround at the moment: 
![image](https://user-images.githubusercontent.com/5551251/120783738-9e000880-c52b-11eb-8cab-4fe2bc0638bb.png)

**Versions:**  
 - Adapter version: iobroker.admin v5.1.6 / iobroker.lovelace 1.5.0 
 - JS-Controller version: 3.3.11 
 - Node version: node 12.22.1
 - Operating system: Debian / Docker

**Comment by Apollon77** [comment]
known, adapter needs update. works when you turn off the new react ui in a second instance

**Comment by Garfonso** [comment]
Yes, I already implemented the new UI ( https://github.com/Garfonso/ioBroker.lovelace/commit/31368a0f3d2ff137ecb88490eb39833bc04ba857 ). Just need to find an annoying bug (in another part of the adapter) and then will start the process to get it into latest.

**Comment by Apollon77** [comment]
Do you have a rough feeling on when ready? (For Admin5 release planning)

**Comment by Garfonso** [comment]
I try to prepare a PR today or tomorrow.

I was a bit unorganized in the recent weeks, so it is a big code change in one branch that is not easy to split up anymore... Will try to improve that again in the future.

**Comment by Apollon77** [comment]
happens ... all good :-) other you could cherry pick just the jsonconfig in an own PR/commit and release and then bring out rest ... IF that is feaable
