### ISSUE TITLE
Weather card buggy

### ISSUE THREAD

**Issue by Alexander060101** [ioBroker/ioBroker.lovelace#219]
The Weather card seems to be buggy.
I am using it with the DasWetter adapter but it shows the wrong values.
It's 1 day deferred and shows Monday values as Sunday, Tuesday values as Monday and so on.
Did I do something wrong?

Thank you for your help.

See screenshots:
<img width="1434" alt="Bildschirmfoto 2021-06-20 um 13 36 26" src="https://user-images.githubusercontent.com/12053064/122672852-e840e500-d1cd-11eb-9a26-c3a41d4b9c25.png">
<img width="1409" alt="Bildschirmfoto 2021-06-20 um 13 44 35" src="https://user-images.githubusercontent.com/12053064/122672877-09093a80-d1ce-11eb-8bc4-597763677cbf.png">
<img width="503" alt="Bildschirmfoto 2021-06-20 um 13 43 04" src="https://user-images.githubusercontent.com/12053064/122672890-14f4fc80-d1ce-11eb-9f84-5ad29903edb1.png">

Here my card configuration:
  - type: weather-forecast
    entity: weather.Regen__Regen_Deutschland_
    name: Regen
    show_forecast: true

**Versions:**  
 - Adapter version: 1.5.0
 - JS-Controller version: 3.1.6
 - Node version: 10.24.1
 - Operating system: Raspberry Pi OS 10 (Buster)

**Comment by Garfonso** [comment]
Sorry for my late reply. I wanted to check this again, but somehow forgot...

I am investigating this issue. It is not an issue with lovelace. It might be an issue with type-detector or dasWetter.

**Comment by Garfonso** [comment]
can you test with my development version?

- enable expert view in admins tab
- install from github custom url and paste `Garfonso/iobroker.lovelace#dev`

**Comment by Alexander060101** [comment]
Thanks!
I will do so on the weekend latest but will try to do it today/tomorrow.

**Comment by Alexander060101** [comment]
I just tried it.
I have Lovelace version 2.0.3 now and here the weather card is working correctly now.
Thanks!
