### ISSUE TITLE
Improve automatic entity name correction

### ISSUE THREAD

**Issue by Alexander060101** [ioBroker/ioBroker.lovelace#220]
When I add a new sensor or whatever I normally copy the state address from the title and copy-paste it.
Dots (.) are replaced automatically with underlines (_) but dashes (-) are not.
But as dashes do not work as well, I would suggest this should be automatically replaced as well.

<img width="1445" alt="Bildschirmfoto 2021-06-20 um 14 38 35" src="https://user-images.githubusercontent.com/12053064/122674489-c2b7d980-d1d5-11eb-8172-28ef6f887d40.png">

Versions:
Adapter version: 1.5.0
JS-Controller version: 3.1.6
Node version: 10.24.1
Operating system: Raspberry Pi OS 10 (Buster)

**Comment by Garfonso** [comment]
What do you mean by "dashes do not work as well"?

**Comment by Garfonso** [comment]
just checked: in new Admin 5 UI this is already implemented (it will even auto fill the field you now copy & paste manually). I hope you will enjoy. 😄 

I don't think I will fix this in Admin 4, since release of 5 is already in progress (and is already in latest). Thanks for reporting it, though.
