### ISSUE TITLE
Homematic Rauchmelder LowBat

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.lovelace#221]
**Describe the bug**  
Mit Version 2.0.0 wurde binary_sensor eingeführt. Die LowBat Objekte meiner Homematic Thermostate wurden auch einwandfrei erkannt, jedoch die meine Homematic Rauchmelder nicht.

**Expected behavior**  
Es sollten die LowBat Objekte der Rauchmelder auch automatisch erkannt werden.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/19261667/123742256-a5f16500-d8ab-11eb-9832-8e6532038bbf.png)

**Versions:**  
 - Adapter version: 2.0.0
 - JS-Controller version: 3.3.14
 - Node version: 14.16.1
 - Operating system: Docker Container (auf einem Raspi 4 4GB)

**Comment by Garfonso** [comment]
Ist der State denn im Geräte Adapter mit dabei? Nur dann kann der lovelace Adapter den als "zugehörig" erkennen.
Bzw. ist das Entity manuell konfiguriert oder automatisch erkannt? Den zusätzlichen Alarm gibt es nur für automatisch erkannte entities. Bei manuellen müsste man den LowBat binary_sensor auch manuell erstellen.

**Comment by dontobi** [comment]
Die Rauchmelder sind einem Raum und einer Funktion zugeordnet (siehe Bild). Ich habe keinem Objekt manuell einem Entity zugeordnet. Bei den Thermostaten ging alles ohne Probleme. Ich werde gleich den ioBroker mal komplett neustarten und schau dann nochmal, ob die Entities erstellt wurden.

![image](https://user-images.githubusercontent.com/19261667/123778944-f11e6e80-d8d1-11eb-84dc-3645089957cf.png)

**Comment by Garfonso** [comment]
![Geräte-States-Prüfen](https://user-images.githubusercontent.com/620860/123785093-6725d400-d8d8-11eb-8397-fa817403861f.JPG)

Ok, dann bitte mal, wie im Bild Prüfen ob es da bei "Zustände" ein "LOW BAT" gibt und das einen Eintrag hat.

Und / Oder gerne auch mal vom Rauchmelder ein Json an mich -> Rauchmelder hab ich hier gar nicht, dann baue ich damit nen Test. :-)

**Comment by dontobi** [comment]
Nachdem ich den "Geräte" Adapter gerade installiert habe (hatte den bisher nie für notwendig gehalten), musste ich feststellen das die Rauchmelder gar nicht als Gerät erkannt werden. Eine Funktion und einen Raum habe ich zugewiesen.

Leider kann ich keine neuen Ordner und Geräte im ioBroker.devices Adapter anlegen.

**Comment by dontobi** [comment]
> > Leider kann ich keine neuen Ordner und Geräte im ioBroker.devices Adapter anlegen.
> 
> Warum?

Wenn ich das wüsste... Habe im Forum bereits einen Beitrag gepostet.

**Comment by dontobi** [comment]
Ich hab einen Ordner manuell hinzugefügt bekommen. Werde dann morgen weitere Tests durchführen. Jedoch ist mir aufgefallen, dass bei den Thermostaten kein LowBat Value eingetragen ist, Lovelace dieses aber erkennt.

**Comment by dontobi** [comment]
Ich habe heute morgen nochmals ein wenig ausprobiert. Der Geräte Adapter macht irgendwie nicht das, was ich möchte. Daher habe ich ein Issue aufgemacht (siehe https://github.com/ioBroker/ioBroker.devices/issues/79).

Die Frage die sich mir nun stellt ist, wie es hier weiter geht. Derzeit kann ich die manuell erstellten Geräte nicht mit einem LOWBAT Indikator versehen, da mir diese im Geräte Menü nicht angezeigt werden.

**Comment by Garfonso** [comment]
Habe auch nochmal rumprobiert. Die Indikatoren sind per default ausgeblendet. Mit dem Knopf kann man die einblenden: 

![devices-indikatoren](https://user-images.githubusercontent.com/620860/123949690-20e97700-d9a3-11eb-97d1-8501ab287a23.JPG)

Aber nochmal zurück... wird der Rauchmelder als Gerät "Feueralarm" erkannt, oder nicht? Damit hab ich auch was rumgespielt, aber irgendwie werden meine Feueralarme immer zu "info" -> was im Grunde "unbekannt" bedeutet (und daher von lovelace ignoriert wird)... da scheint mir irgendwas im type-detector nicht 100%ig zu passen.

**Comment by Garfonso** [comment]
Könntest du mir mal einen json Export von so einem ganzen Rauchmelder-Ordner anhängen? Dann könnte ich mal gucken, wo das genau schief läuft.

**Comment by dontobi** [comment]
Ich spiele gleich die Dev Version mal ein und teste. Anbei die JSON als ZIP.
[hm-rpc.0.OEQ0958248.json.zip](https://github.com/ioBroker/ioBroker.lovelace/files/6740888/hm-rpc.0.OEQ0958248.json.zip)

**Comment by Garfonso** [comment]
Danke für den Objektexport. Mir sind zwei Sachen aufgefallen:
1. Du hast den Rauchmelder manuell konfiguriert (für hm-rpc.0.OEQ0958248.1.STATE ). Das erklärt, warum der Sensor auftaucht (aber ohne Low bat sensor)
2. Die Rolle von hm-rpc.0.OEQ0958248.1.STATE ist "state" was falsch ist, daher wird das Gerät nicht automatisch als fireAlarm / Rauchmelder erkannt und daher auch kein entity für den Rauchmelder und die Batteriewarnung erstellt.

Zu 2.: warum ist die Rolle falsch? Ich vermute, dass du sie nicht selber geändert hast? Mich verwirrt auch etwas, dass dort bei `from` `hm-rega.0` drin steht und nicht `hm-rpc.0`. Mit hm-rega kenne ich mich allerdings nicht aus... 
Eigentlich sollte, wenn ich das richtig verstehe, die Rolle von dem STATE Objekt `sensor.alarm.fire` sein. 

Kannst du die Geräte nochmal neu anlegen lassen (oder ein einzelnes zum testen)?  -> dann sehen wir, ob der Homematic Adapter das richtig macht, oder nicht. (Vorgehen wäre m.E. Ganzen Objektbaum löschen, in Instanzeinstellung von hm-rpc.0 sagen "Geräte neueinlesen" und warten. Ggf. braucht man das löschen nicht?). 

Ansonsten wäre der workaround mal die Rolle von STATE auf `sensor.alarm.fire` zu ändern. Aber wenn das der homematic adapter nicht automatisch setzt, wäre es gut das zu wissen und da ein Issue zu erstellen.

**Comment by dontobi** [comment]
Ich hab gerade nochmal nachgesehen und den Rauchmelder Büro entfernt und neu einlesen lassen. Ergebnis: Der Rauchmelder wird nicht als Entity angezeigt. Jedoch gab es einen anderen Rauchmelder, von dem ein Entity erstellt wurde. Daher hab ich die JSON Dateien alle Rauchmelder hier angehangen. Vielleicht findest du den Grund dafür. Wie gesagt... ich hab nur den vom Büro gelöscht und neu anlegen lassen!

![image](https://user-images.githubusercontent.com/19261667/124105491-8ac95580-da63-11eb-88a6-5f112d48f65c.png)
[HM-Rauchmelder.zip](https://github.com/ioBroker/ioBroker.lovelace/files/6747276/HM-Rauchmelder.zip)

**Comment by Garfonso** [comment]
Leider ist Büro leer... 

Warum Kinderzimmer gefunden wird, verstehe ich nicht.... 
Kannst du mal auf "Attribute anzeigen" klicken und bei binary_sensor.Rauchmelder___Kinderzimmer gucken, ob bei device_class smoke steht oder was anderes?

**Comment by dontobi** [comment]
Leider kann ich das nicht mehr nachsehen, weil ich alle Rauchmelder neu eingelesen habe.

Anbei nochmal ein Export von dem Rauchmelder Büro.
[hm-rpc.0.OEQ0957889.json.zip](https://github.com/ioBroker/ioBroker.lovelace/files/6747653/hm-rpc.0.OEQ0957889.json.zip)

**Comment by Garfonso** [comment]
> Leider kann ich das nicht mehr nachsehen, weil ich alle Rauchmelder neu eingelesen habe.

Also wird für keinen der Rauchmelder mehr ein entity erkannt?

> Anbei nochmal ein Export von dem Rauchmelder Büro.
> [hm-rpc.0.OEQ0957889.json.zip](https://github.com/ioBroker/ioBroker.lovelace/files/6747653/hm-rpc.0.OEQ0957889.json.zip)

Ich verstehe immer noch nicht so ganz, warum da "hm-rega" bei "from" steht. Wie liest du die ein?

**Comment by dontobi** [comment]
So wie ich das verstehe setzt der HM-RPC auf den HM-REGA auf. Ohne den HM-REGA bekomme ich nämlich keine Kommunikation zur CCU hin.

Und die Rauchmelder sind alle frisch eingelesen worden und somit von Manipulationen durch mich befreit. Denn ich kann mich noch an ein paar Umstellungen erinnern, als ich noch die Material VIS bzw. iogo VIS verwendet habe.

**Comment by Garfonso** [comment]
Hm.. also ich nutze HM-Rega nicht und meine Homematic Geräte werden von hm-rpc eingebunden und gesteuert. *grübel* 

Jedenfalls könntest du mal versuchen von Hand die Rolle von .1.STATE auf `sensor.alarm.fire` zu setzen. Dann sollten die automatisch als Rauchmelder erkannt werden und auch die Batterie auftauchen.

**Comment by dontobi** [comment]
Ich hab den Rega Adapter nun erst einmal ausgeschaltet. Wenn die Funktionalität der HomeMatic Geräte erhalten bleibt, werde ich den Adapter deinstallieren.

Außerdem habe ich die Rollen angepasst und siehe da... Die LowBat Entities sind nun vorhanden. Die Frage ist nun, wie man dies ohne die manuelle Änderung der Rolle das hin bekommt. Ich gehe davon aus, dass dazu keine Anpassungen am Lovelace Adapter notwendig ist. Richtig?

**Comment by Garfonso** [comment]
Richtig. Lovelace hat damit eigentlich nichts zu tun (bzw ich habe support für das Rauchmelder device eingebaut, Das gab es am Anfang auch noch nicht). 

Die Homematic Geräte müssen mit der entsprechenden Rolle angelegt werden. Ich bin mir nicht ganz sicher, aber im Code von hm-rpc sah es eigentlich so aus, als ob das passiert. 

Am besten machst du aber da mal ein issue direkt mit dem Export und Erklärung, dass die Rolle von .1.State nicht passt und deshalb der type-detector das Gerät nicht findet. Da guckt dann auch jemand drauf, der sich besser mit homematic auskennt.

**Comment by dontobi** [comment]
Ich mach hier zu. Ist auf Seiten des HM-RPC Adapters gefixt worden.
