### ISSUE TITLE
Zigbee Lampe wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.lovelace#222]
**Describe the bug**  
Nach dem Update auf Version 2.0.0 wird mir eine meiner Zigbee Lampen bei der Light Card nicht richtig angezeigt. Siehe Screenshots.

**Expected behavior**  
Eigentlich sollte die Light Card ohne Probleme funktionieren. Der Unterschied der Lampen ist, dass die beiden funktionierenden Lampen von Philips Hue sind und nur Warm- bzw. Kaltweiß, sowie die Dim Funktion unterstützen. Die Lampe, die Probleme bereitet ist ein Leuchtmittel E27 von Ikea Tradfri und unterstützt mehrere Farben. Ich kann nicht ausschließen, dass es evtl. auch ein Fehler beim Zigbee Adapter ist, jedoch hat die Light Card mit Version 1.5.0 ohne Probleme geklappt.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/19261667/123743242-37ada200-d8ad-11eb-8014-adcefdba71ef.png)
![image](https://user-images.githubusercontent.com/19261667/123743322-53b14380-d8ad-11eb-9296-46aac0707af3.png)
![image](https://user-images.githubusercontent.com/19261667/123742872-ae966b00-d8ac-11eb-80ca-1a0a899a1d6b.png)

**Versions:**  
 - Adapter version: 2.0.0
 - JS-Controller version: 3.3.14
 - Node version: 14.16.1
 - Operating system: Docker Container (auf einem Raspi 4 4GB)

**Comment by Garfonso** [comment]
Bitte schick / häng einen Export des Geräts aus dem Admin an (also den "Ordner" zigbee.x.ccccccccccc... anklicken in der Objektansicht und oben auf "export", dann kriegst du ein json zum runterladen). 

Lovelace hat das Licht-System umgebaut, kann sein, dass da bestimmte Fälle nicht gehen. Danke für den Report.

**Comment by dontobi** [comment]
Anbei die JSON Datei (in einer ZIP gepackt).
[zigbee.0.ccccccfffee2dbb0.json.zip](https://github.com/ioBroker/ioBroker.lovelace/files/6732554/zigbee.0.ccccccfffee2dbb0.json.zip)

**Comment by Garfonso** [comment]
ok, war ein blöder typo. Kannst du kurz testen, ob es, wenn du von dieser URL installierst geht: `Garfonso/iobroker.lovelace#dev` (experten modus an -> adapter -> github icon -> von beliebiger URL und das reinkopieren)

**Comment by dontobi** [comment]
Hab's gerade getestet. Klappt! Danke
