### ISSUE TITLE
Hintergrundfarbe vertical/horizontal stack card ändern

### ISSUE THREAD

**Issue by DNA-Trainer** [ioBroker/ioBroker.lovelace#223]
Hallo.
Ist es möglich für die stack cards eine background variable zu erstellen, sodass man die Hintergrundfarbe
themen kann?
Ich möchte gerne mehrere stack cards mit anderer hintergrundfarbe nebeneinander haben.
Ich habe nun einiges getestet, allerdings führte kein weg zum gewünschten Ergebnis.

Ich kann zwar per card-mod und dem workaround (stack-card in custom:mod-card) die hintergrundfarbe der stack cards verändern, allerdings sind die Karten dann nicht mehr nebeneinander, sondern untereinander.

Ich habe auch schon versucht in ein custom:hui-vertical-stack-card in ein entities element zu packen, allerdings werden auch hier die karten wieder untereinander gepackt.

**Comment by Garfonso** [comment]
Hi,

Das ist nicht im Bereich dieses Adapters, der "nur" eine Übersetzung von IoBroker zu HomeAssistant und zurück zur Verfügung stellt, damit man mit Lovelace IoBroker steuern kann. 

Eigentlich sollte das mit der card mod Karte hinzukriegen sein. Warum nimmst du da die custom:mod-card? Reicht es nicht card-mod installiert zu haben und dann mit style den Hintergrund zu verändern?

**Comment by DNA-Trainer** [comment]
Erstmal sorry, dass ich im falschen Bereich bin.

Leider kann man die stack cards nicht direkt mit card-mod stylen, darum der Umweg über die custom:card
Wie gesagt, werden diese dann allerdings untereinander angezeigt. Dieses Verhalten scheint bei sämtlichen custom:cards der Fall zu sein.

Wäre schön gewesen, wenn im Quellcode von lovelace ein Attribut dafür vorhanden wäre, so ähnlich wie 
_paper-item-icon-active-color_ 
z.B. _horizontal-stack-card-background-color_

Danke jedenfalls für die Antwort, ich schaue mal weiter. Eventuell habe ich mittlerweile schon eine halbwegs funktionierende Lösung gefunden.

**Comment by Garfonso** [comment]
Brauchst dich nicht entschuldigen. Ich wollte nur klar machen, dass solche Themen out of scope sind für den Adapter bis auf Einzelfälle (z.B. Wetter-Karte). Jede Veränderung am Frontend macht Updates für ioBroker schwerer. Was es da alles gibt, erforsche ich selber auch immer noch.

Ich weiß auch nicht genau, was du erreichen willst, aber ich habe jetzt mit card-mod das hier hinbekommen:

![lovelace colored stacks](https://user-images.githubusercontent.com/620860/124018298-fe2d8180-d9e7-11eb-9303-e2f6f23919a3.JPG)

Der Code dazu sieht so aus:
```
type: vertical-stack
cards:
  - type: button
    card_mod:
      style: |
        ha-card {
          --ha-card-background: teal;
        }
    tap_action:
      action: toggle
    entity: light.Zigbee_Color
  - type: entity
    entity: binary_sensor.binary_sensor_with_custom
    card_mod:
      style: |
        ha-card {
          --ha-card-background: teal;
        }

```
Also im Grunde für jede Karte im Stack den card-mod einzeln anwenden. Es bleiben weiße (bzw. abhängig vom Theme) striche dazwischen.

Eine andere Möglichkeit könnte sein verschiedene Themes mit verschiedenen Hintergrundfarben (bzw. nur die Hintergrundfarben in den Themes festlegen) und dann der Stack-Karte ein festes Theme zuweisen (unter "Aussehen").

**Comment by DNA-Trainer** [comment]
Ich möchte erstmal anmerken, dass ich ehemaliger FHEM Nutzer bin und somit relativ neu in Sachen iobroker/lovelace.
Vielleicht gibt es da nen Trick, den ich noch nicht kenne oder so.

Um zu zeigen, was ich erreichen möchte, habe ich die Hintergründe der _stacks_ im Browser per CSS gefärbt, diese sind also normalerweise Transparent und können mit _card-mod_ nicht gestyled werden.
![Übersicht - ioBroker - Mozilla Firefox 30 06 2021 21_33_00](https://user-images.githubusercontent.com/47078064/124022102-a80f0d00-d9ec-11eb-87ea-9afc4d4c71d5.png)
`type: vertical-stack
title: Test 1
cards:
  - type: horizontal-stack
    cards:
      - type: light
        entity: light.sd_wohnzimmer_8ermopped_licht
        name: TEST
      - type: light
        entity: light.sd_wohnzimmer_stehlampe_licht
        name: TEST
        icon: mdi:floor-lamp
  - type: horizontal-stack
    cards:
      - type: light
        entity: light.sd_wohnzimmer_tv
        name: TEST
        icon: mdi:television
      - type: light
        entity: light.sd_wohnzimmer_8ermopped_licht
        name: TEST
`


Um den Hintergrund vom _horizontal/vertical stack_ zu ändern, muss ich leider den Umweg über die _custom card_ gehen und dabei kommt folgendes raus
![Übersicht - ioBroker - Mozilla Firefox 30 06 2021 21_33_04](https://user-images.githubusercontent.com/47078064/124022130-b0ffde80-d9ec-11eb-8f2a-5eeb197cab36.png)

`type: custom:mod-card
card:
  type: vertical-stack
  title: Test 1
  cards:
    - type: horizontal-stack
      cards:
        - type: light
          entity: light.sd_wohnzimmer_8ermopped_licht
          name: TEST
        - type: light
          entity: light.sd_wohnzimmer_stehlampe_licht
          name: TEST
          icon: mdi:floor-lamp
    - type: horizontal-stack
      cards:
        - type: light
          entity: light.sd_wohnzimmer_tv
          name: TEST
          icon: mdi:television
        - type: light
          entity: light.sd_wohnzimmer_8ermopped_licht
          name: TEST
card_mod:
  style: |
    ha-card {
    background-color: #2581ab;
    padding: 2px;
    }
`
Also eine Zwickmühle, den Hintergrund vom stack kann ich nur mit _custom:mod-card_ stylen, dafür sind die stacks aber untereinander. 
Lasse ich _custom:mod-card_ weg, sind die stacks nebeneinander (so wie es sein soll), dafür kann ich die aber nicht stylen.

So wie es aussieht, habe ich aber eventuell eine Lösung mittels _layout-card_ gefunden.

**Comment by Garfonso** [comment]
Als Tipp: Für solche Fragen ist das Forum auch sehr hilfreich. Da gibt es mehrere lovelace Threads wo sich auch andere rumtreiben, die sich mit dem Frontend tendentiell besser aus kennen (und es gibt auch noch Beispiele, was man alles machen kann). Oder halt ein Thema selber aufmachen (wobei da klar sein muss, dass es um Lovelace geht). 

Beispiele:
https://forum.iobroker.net/topic/35950/zeigt-her-eure-lovelace-visualisierung

Eine Anleitung (wobei da nicht mehr alles stimmt, ggf. auch hier im Ordner "docs" mal stöbern, ist aber noch nicht komplett):
https://forum.iobroker.net/topic/35937/der-ultimative-iobroker-lovelace-leitfaden-dokumentation

und der Testthread (da ruhig fragen unten rein kippen, machen eh alle):
https://forum.iobroker.net/topic/34775/test-adapter-lovelace-v1-2-x

Als Alternative gibt es auch noch nen discord server, wobei der in Richtung lovelace nicht sehr aktiv ist (da bin ich auch nur unregelmäßig).
