### ISSUE TITLE
Mehrere Kleinigkeiten

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.lovelace#235]
#1: Doppelte Entities
Bei den Rollläden wurden bei mir für jedes LEVEL Objekt zwei Entities erstellt. Siehe folgendes Beispiel:
cover.Rollladen_Buero   hm-rpc.0.NEQ0083056.1.LEVEL
inputnumber.RollladenBuero   hm-rpc.0.NEQ0083056.1.LEVEL

#2: Entities mit mehreren States
Bei meinen Ikea Schaltsteckdosen (laufen über den Zigbee Adapter) werden für ein Entity zwei States angezeigt. Aus meiner Sicht wäre ein State ausreichend. Siehe folgendes Beispiel:
switch.Steckdose1   zigbee.0.588e81fffebb4667.available / zigbee.0.588e81fffebb4667.state
Ausreichend wäre hier zigbee.0.588e81fffebb4667.state!

#3: Entity umbenennen
Bei den Entities der Homematic Thermostate wäre es sinnvoll ein Entity anders zu nennen. Siehe folgendes Beispiel:
sensor.Thermostat_Buero   hm-rpc.1.000A98A9A22E81.1.WINDOW_STATE
Ich würde mir als Namen des Entity sensor.Thermostat_BueroWindowState vorstellen.

#4: Falsches Objekt bei Temperature Entity
Bei den Homematic Thermostaten verweist das Temperature Entity auf ein falsches Objekt. Siehe folgendes Beispiel:
sensor.ThermostatBuero_Temperature   hm-rpc.1.000A98A9A22E81.1.PARTY_SET_POINT_TEMPERATURE
Richtig wäre das Objekt hm-rpc.1.000A98A9A22E81.1.ACTUAL_TEMPERATURE
Wenn der Temperatur Sollwert ebenfalls als Entity eingepflegt werden soll, wäre das passende Objekt folgendes: hm-rpc.1.000A98A9A22E81.1.SET_POINT_TEMPERATURE

#5: Falsches Objekt hinterlegt
Beim durchsehen der Entities ist mir dann noch aufgefallen, dass die Lampen die über Zigbee laufen bei den Switch Entites ein falsches Objekt hinterlegt haben. Siehe folgendes Beispiel:
switch.Badezimmer   zigbee.0.0017880106847bb7.device_query
Wenn das Licht mit dem Entity ein- bzw. ausgeschaltet werden soll, dann müsste es folgendes Objekt sein: zigbee.0.0017880106847bb7.state
Hinweis: Das Light Entity verweist auf das richtige Objekt, daher wäre ggf. das Switch Entity überflüssig (light.Badezimmer   zigbee.0.0017880106847bb7.state)

**Comment by agross** [comment]
Ich glaube durch Nummer 5 sind die meisten meiner Lichter gar nicht mehr schaltbar.

<img width="446" alt="2021-07-04_19-44-59" src="https://user-images.githubusercontent.com/16245/124394587-5aeaae00-dd00-11eb-9eae-6a0b5ce3e0ec.png">

**Comment by Garfonso** [comment]
Erstmal, sorry, dass ich in Discord nicht reagiert habe. Hatte irgendwie keine Zeit da rein zu gucken.

Zu den Punkten.

1. Das ist wegen Rückwärtskompatibilität. Stört das? Früher wurden Rolladen nur zu input_number. Jetzt gibt es halt noch das cover mit dazu, wo auch stop und rauf/runter als Knöpfe unterstützt werden. 
2. Urgs... ist ja blöd, dass das bei switch auch passiert.. :-( Das ist leider ein bug... trifft auf 5. auch zu. 
3. Der Name richtet sich in dem Beispiel nach dem Namen von ` hm-rpc.1.000A98A9A22E81`. Das grundsätzlich zu ändern würde bei allen Leuten die entity_ids verändern, also müssten sie ihre UIs neu machen... ich gebe zu, dass das nicht 100% optimal ist... vielleicht mache ich es aber für sensor/binary_sensor einfach so. Hm.
4. Das ist dann ein bug im type-detector. Am besten da melden, damit das untersucht wird: https://github.com/ioBroker/ioBroker.type-detector/issues (und am besten direkt mit JSON Export vom Gerät).

@agross: versuch mal bitte den dev-branch von mir, also von Git aus custom URL installieren und da dann `Garfonso/iobroker.lovelace#dev` eingeben. Für Lichter hab ich das rausgefilter (in 2.0.0 ist das leider kaputt). Ich wusste nicht, dass es auch andere entities betrifft.... 

@dontobi Kannst du mir für 2 und 5 JSONs zukommen lassen?

**Comment by agross** [comment]
Danke für die schnelle Reaktion. Die Lampen sind wieder schaltbar!

**Comment by dontobi** [comment]
#1: Stören tut das nicht, jedoch Stelle ich mir die Frage wie lange man Altlasten mit sich schleppt und ab wann man in Kauf nimmt, dass Fragen bzw. Beiträge von Leuten kommen, die keine Changelogs lesen. Denn wenn man sich der Altlasten entledigt, schreibt man dies sicherlich in ein Changelog und verweist außerdem auf die neue Herangehensweise.

#2 und #5: @Garfonso Ich hab die die JSON Files angehängt.

#3: Da ich Windows State nicht verwende, würde es mich also auch nicht betreffen. Jedoch könnte man auch hier bei einem größeren Versions Sprung in einem Changelog drauf hinweisen. Bei dem Sprung zu 2.0.0 musste ich bei meiner Config auch Hand anlegen, war aber auch kein all zu großer Aufwand.

#4: Wenn ich morgen dazu komme, werde ich ein Issue dazu erstellen.

Dateien:
[JSON_#2.zip](https://github.com/ioBroker/ioBroker.lovelace/files/6760540/JSON_.2.zip)
[JSON_#5.zip](https://github.com/ioBroker/ioBroker.lovelace/files/6760541/JSON_.5.zip)

**Comment by agross** [comment]
Zu 1: ich bin ebenfalls davon ausgegangen, dass 2.0.0 nach semver auch breaking changes hat, von daher hätte man das gleich mit unterbringen können.

**Comment by Garfonso** [comment]
Ja, 2.0.0 hat breaking changes. 

Das Problem von 3. ist, dass die ID an einer relativ generischen stelle festgelegt wird... es könnte ja auch zu Kollisionen kommen, das ist das größte Problem. Da hab ich irgendwie noch keine befriedigende Lösung, die für die Fälle passt, wo der Name vom Gerät völlig ausreichend / richtig ist und die Fälle, wo das nicht passt oder wo es, wie hier, mehrere entities zum gleichen Gerät gibt (also zumindest in den Fällen, wo das nicht klar ist... -> wenn ein ioBroker Gerät in mehrere entities zerlegt wird, werden die ids entsprechend länger generiert, das war der breaking change in 2.0.0. Wenn es aber für ein "device" Objekt mehrere ioBroker Geräte gibt, ist das für den Adapter in der aktuellen Struktur nicht so ganz offensichtlich... ).

**Comment by dontobi** [comment]
@Garfonso Ich hab noch etwas. Da ich einen Unterputz Schaltaktor tauschen musste und nun einen HmIP Unterputz Schaltaktor nutze, ist es notwendig geworden ein paar Entities anzupassen. Leider werden die Entities nicht sauber automatisch erstellt. Hier die Liste der Entities:

```
Entity ID	States
sensor.Steckdose_1___Wohnzimmer	hm-rpc.1.00089BE9A6ED5D.0.ACTUAL_TEMPERATURE
sensor.Steckdose_1___Wohnzimmer_0	hm-rpc.1.00089BE9A6ED5D.0.ACTUAL_TEMPERATURE
switch.Steckdose_1___Wohnzimmer	hm-rpc.1.00089BE9A6ED5D.1.STATE / hm-rpc.1.00089BE9A6ED5D.4.STATE
switch.Steckdose_1___Wohnzimmer_4	hm-rpc.1.00089BE9A6ED5D.4.STATE
```

Geschaltet wird die Steckdose mit dem Objekt hm-rpc.1.00089BE9A6ED5D.2.STATE, dass nicht angelegt wurde. Daher habe ich den Entity switch.Fernsher mit diesem Objekt angelegt.

Kannst du da etwas machen oder ist das eher etwas für den ioBroker.devices Adapter?

Anbei das JSON von dem HmIP Schaltaktor.
[hm-rpc.1.00089BE9A6ED5D.json.zip](https://github.com/ioBroker/ioBroker.lovelace/files/6786235/hm-rpc.1.00089BE9A6ED5D.json.zip)

**Comment by Garfonso** [comment]
Huch.. was ist das für ein Schaltaktor? Warum hat der so viele States & Channels. Urgs...
An der Stelle macht Lovelace, was der Type-Detector erkennt. Ich sehe da die folgenden Geräte:

```
2021-07-08 19:55:33.423  - debug: lovelace.0 (55664) [Type-Detector] Created auto device: switch.Steckdose_1___Wohnzimmer - socket - hm-rpc.1.00089BE9A6ED5D
2021-07-08 19:55:33.424  - debug: lovelace.0 (55664) [Type-Detector] Created auto device: sensor.Steckdose_1___Wohnzimmer - temperature - hm-rpc.1.00089BE9A6ED5D
2021-07-08 19:55:33.425  - debug: lovelace.0 (55664) [Type-Detector] device hm-rpc.1.00089BE9A6ED5D.0.ACTUAL_TEMPERATURE_STATUS - info - hm-rpc.1.00089BE9A6ED5D is not yet supported
2021-07-08 19:55:33.431  - debug: lovelace.0 (55664) [Type-Detector] Created auto device: sensor.Steckdose_1___Wohnzimmer_0 - temperature - hm-rpc.1.00089BE9A6ED5D.0
2021-07-08 19:55:33.432  - debug: lovelace.0 (55664) [Type-Detector] device hm-rpc.1.00089BE9A6ED5D.0.ACTUAL_TEMPERATURE_STATUS - info - hm-rpc.1.00089BE9A6ED5D.0 is not yet supported
2021-07-08 19:55:33.434  - debug: lovelace.0 (55664) [Type-Detector] Created auto device: switch.Steckdose_1___Wohnzimmer_4 - socket - hm-rpc.1.00089BE9A6ED5D.4
2021-07-08 19:55:33.435  - debug: lovelace.0 (55664) [Type-Detector] device hm-rpc.1.00089BE9A6ED5D.4.COMBINED_PARAMETER - info - hm-rpc.1.00089BE9A6ED5D.4 is not yet supported

```

Irgendwie sehe ich nicht so viele Geräte im Devices Tab, was mich noch etwas verwirrt... 
Allerdings ist es auch etwas "Gemein", dass es so viele Zustände mit Rolle "State" gibt... 

Also ich sehe da gerade nicht, wo ich was machen könnte (was da noch fehlt ist support für die Strommessung in lovelace, das ist noch nicht implementiert und muss ich gucken, wie das am besten geht).

**Comment by dontobi** [comment]
Ist halt ein HomeMatic IP Gerät und kann deshalb auch mehr, als ein normaler HomeMatic Aktor. Ich kann damit leben, dass ich ein paar Entities manuell anlegen muss.

**Comment by dontobi** [comment]
Ich habe heute morgen den Lovelace Adapter (Dev Tree) aktualisiert und seitdem werden die Rollläden nicht mehr korrekt angezeigt. Die Entities haben jeweils 2 Objekte.

cover.Rollladen___Buero	hm-rpc.0.NEQ0083056.0.AES_KEY / hm-rpc.0.NEQ0083056.1.LEVEL

**Comment by Garfonso** [comment]
Hm.. da hat sich in lovelace nichts dran getan. Aber der type-detector hatte ein Update... hm... den AES_KEY als Level ist sicherlich nicht rightig... was für eine Rolle hat der denn? Mach bei type-detector / homematic mal ein issue auf.

**Comment by dontobi** [comment]
Den Grund für die doppelten Objekten bei den Rollläden habe ich nun herausgefunden. Siehe folgender Bug Report: https://github.com/ioBroker/ioBroker.devices/issues/84
