### ISSUE TITLE
Icons are not highlighted consistently in 'entities card'

### ISSUE THREAD

**Issue by grisia** [ioBroker/ioBroker.lovelace#236]
In 'entities card' only icons of entities with data-domain='light' is 'highlighted' when active.

In the first picture data domain is binary_sensor:
![image](https://user-images.githubusercontent.com/13525554/124654234-99b66a80-de9e-11eb-9cc2-a48f4fe927eb.png)
Corresponding html part (data-domain attribute is missing):
```html
<ha-icon style="" data-state="on"></ha-icon>
```

Second picture shows entity with data domain light:
![image](https://user-images.githubusercontent.com/13525554/124654424-d08c8080-de9e-11eb-8e23-35d5e429d57a.png)
```html
<ha-icon style="" data-domain="light" data-state="on"></ha-icon>
```

When adding the data-domain attribute (in browser development tools) the style is correct set.

```html
<ha-icon style="" data-domain="binary_sensor" data-state="on"></ha-icon>
```

**Comment by grisia** [comment]
Applying following patch to *iobroker/node_modules/iobroker.lovelace/hass_frontend/frontend_latest/chunk.1e15b96d1e9e0fd6b4b6.js* do the trick for me.

```diff
--- chunk.1e15b96d1e9e0fd6b4b6.js       2021-08-16 18:27:53.027644681 +0200
+++ chunk.1e15b96d1e9e0fd6b4b6.js.mod   2021-08-16 18:27:41.727720764 +0200
@@ -83,7 +83,7 @@
       </div>`;if(!this._showIcon)return a.dy``;const t=e?(0,c.N)(e):void 0;return a.dy`
       <ha-icon
         style=${(0,i.V)(this._iconStyle)}
-        data-domain=${(0,s.o)(this.stateColor||"light"===t&&!1!==this.stateColor?t:void 0)}
+        data-domain=${t}
         data-state=${e?(0,n.q)(e):""}
         .icon=${this.overrideIcon||(e?(0,l.M)(e):"")}
       ></ha-icon>
```

![image](https://user-images.githubusercontent.com/13525554/129598350-73a72814-cf66-4425-8b42-9117e202869f.png)

Variable `t` contains the data domain, why not just use it?

**Comment by Garfonso** [comment]
Hi, sorry for the delay. I just checked the code (which is not mine/ours but from HASS, i.e. [here](https://github.com/home-assistant/frontend)). For `light` entity the highlighting is always active. For all other domains you have to set `state_color` to true. 

You can set `state_color: true` for the complete elements card and it will activate highlighting for all lines that do not have a custom config. If you do a custom config for a line, you have to set `state_color: true` there, too. 

So this works as intended (if state_color does not work for you, please report back).
