### ISSUE TITLE
Scrollbar bei Charts

### ISSUE THREAD

**Issue by wuliwux** [ioBroker/ioBroker.lovelace#246]
Hi, in fullscreen with charts the charts has scrollbars (chrome).

![image](https://user-images.githubusercontent.com/1975703/128402826-b1a3ab08-d1c3-433b-8581-bf2f73d180ca.png)

i think the solution is to change the set of the width style property from:
`<div id="chartTarget" style="height: 160px; width: 100%;">`

to:
`<div id="chartTarget" style="height: 160px; width: **calc( 100% - 1px)**;">`

can this changed by the developer?

greets
wuliwux

**Comment by Garfonso** [comment]
🤔 Such things should be done upstream. It is possible that it is already fixed there. 
Currently I'm on vacation, when I come back, I will try to reproduce and see if an update of the Frontend already fixes the issue.

**Comment by Garfonso** [comment]
I upgraded the frontend to the december release. Could you try again with a 2.1.x version and see if the issue persists, please?

**Comment by wuliwux** [comment]
hi, it works and look great!
greets
wuliwux

**Comment by Garfonso** [comment]
Thanks for the feedback.
