### ISSUE TITLE
custom cards using custom-card-helpers

### ISSUE THREAD

**Issue by kurt4160** [ioBroker/ioBroker.lovelace#248]
**Is your feature request related to a problem? Please describe.**
Some custom cards use in new versions "custom-card-helpers" and can't get imported into lovelace.
For example: https://github.com/iantrich/config-template-card
so I have to use a very old version of the custom card.

**Describe the solution you'd like**
Is it possible to install custom-card-helpers in lovelace/iobroker?

**Additional context**
custom-card-helpers: https://github.com/custom-cards/custom-card-helpers

Kurt

**Comment by Garfonso** [comment]
I just tried config-template-card and it works fine. The custom-card-helpers are already included in the js-file in the release: https://github.com/iantrich/config-template-card/releases/ -> always download from the release link!

**Comment by Garfonso** [comment]
if you happen to find a card that needs card-helpers and they are not included, you probably have to build the custom-card-helpers yourself and "install" the result js file.
