### ISSUE TITLE
Adapter Stoppt bei unbekannten Datenpunkt (v2.0.6)

### ISSUE THREAD

**Issue by XBiT2k** [ioBroker/ioBroker.lovelace#257]
Hallo,

Wird in einem Markdown ein Datenpunkt angezeigt mit z.B. `{viessmannapi.0.XXXXX.0.features.heating.circuits.0.circulation.pump.properties.status.value}`
und dieser Datenpunkt existiert nicht mehr oder wurde gelöscht, stürzt der Adapter ab wenn die Seite mit dem fehlenden Datenpunkt aufgerufen wird.
(Spätestens nach einen Adapterneustart)

LOG:
`
<html>
<body>

host.IoBroker | 2021-09-08 18:25:46.016 | error | instance system.adapter.lovelace.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
lovelace.0 | 2021-09-08 18:25:45.250 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
lovelace.0 | 2021-09-08 18:25:45.237 | error | Cannot read property 'val' of undefined
lovelace.0 | 2021-09-08 18:25:45.236 | error | TypeError: Cannot read property 'val' of undefined at getSpecialValues (/opt/iobroker/node_modules/iobroker.lovelace/lib/bindings.js:143:17) at Object.formatBinding (/opt/iobroker/node_modules/iobroker.lovelace/lib/bindings.js:156:21) at /opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:2582:50 at runNextTicks (internal/process/task_queues.js:62:5) at processImmediate (internal/timers.js:434:9)
lovelace.0 | 2021-09-08 18:25:45.234 | error | unhandled promise rejection: Cannot read property 'val' of undefined
lovelace.0 | 2021-09-08 18:25:45.233 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>`

Beste Grüße

**Comment by Garfonso** [comment]
Danke für den Report.
Kannst du von `https://github.com/Garfonso/ioBroker.lovelace` installieren und gucken, ob es dann geht? 
(in Admin Experten Ansicht anmachen ->bei "Adapter" gibt es dann einen Knopf von Git/einer URL zu installieren da die URL einfügen).

**Comment by XBiT2k** [comment]
Hallo Garfonso

Ja mit der Version geht es Adapter stürzt nicht mehr ab und die Werte sind halt einfach leer weil nicht mehr vorhanden.

Super Arbeit und Besten Dank
XBiT2k
