### ISSUE TITLE
Setting a new 'level.tilt' is not working

### ISSUE THREAD

**Issue by ElRedef** [ioBroker/ioBroker.lovelace#258]
Hello,

I have an cover (Jalousie) object with level.blind and value.blind. Both works well. 

It also has an level.tilt. The actual value is shown in lovelace. But it is not written back into the object tree if I adjust the slider. (If I write direct in the object tree it adjusts the real cover and the value in lovelace.)

I experimented a lot, also with different common sections. But no success. 

Here is an example (just for experiments) of this in object tree:

{
  "common": {
    "name": "Neuer Zustand",
    "type": "number",
    "role": "level.tilt",
    "read": false,
    "write": true,
    "update": false,
    "unit": "%",
    "max": 100,
    "min": 0
  },
  "type": "state",
  "_id": "knx.0.Jalousien_OG.TreppeLinks.Neuer_Zustand",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1631819895799
}

Additional observation: The value of level.tilt is not shown as %. At level.blind i shows %. But this seems to be an issue also present in 'original' lovelace. 

Best regards
Johannes

**Comment by Garfonso** [comment]
Hi,

seems I missed a service call there and there also was a bug with tilt. Can you test to install from my fork: `https://Garfonso/iobroker.lovelace` (in Admin->adapters enable expert mode and install from custom url).

**Comment by ElRedef** [comment]
Wow! What a reaction time.

Works on my side! Thank you very much!

**Comment by Garfonso** [comment]
should be in latest, now.
