### ISSUE TITLE
Issue with Hue Brightness

### ISSUE THREAD

**Issue by ElRedef** [ioBroker/ioBroker.lovelace#279]
Hallo,

ich habe Hue Lampen die ich mit Lovelace ansteuere. Diese sind als "entities" angelegt.

Wenn ich in den erweiteren Dialog gehe kann ich dort Farbe und Helligkeit etc. einstellen. Wenn ich die Helligkeit ziehe springt diese nach ca 2 Sekunden wieder auf 100%.  Ich glaube das hat damit zu tun dass der Helligkeitsslider sich auf mehr als auf 'level.dimmer' auswirkt. Nämlich auch auf level.color.green und level.color.red (aber nicht auf blau)

Zur Verdeutlichung ein Screenshot des Dialoges und der Lampe im Objektbaum direkt nach dem ziehen des sliders (aber schon wieder auf 100% gesprungen). In Grün die neuen Werte

Schreibe ich in level.dimmer im Objektbaum funktioniert es wunderbar. Wenn ich mit einem 'slider'entity-row' testweise in lovelace bediene funktioniert es ebenfalls. 

So ist der State und der Testslider angelegt:
` entity: light.Stehlampe_oben`

`  type: custom:slider-entity-row`
`    entity: light.Stehlampe_oben`
 `   name: Stehlampe oben`

Soweit ich das beobachten konnte ist das mit allen Lichter mit Farben (light.color) und nicht mit Birnen die man nur dimmen kann. 

![states](https://user-images.githubusercontent.com/66745270/141813178-681ef3bf-0185-4e08-8c7a-ce579ffc464c.JPG)
![einstellungen](https://user-images.githubusercontent.com/66745270/141813180-ba078a0c-9b3e-4e14-a7be-bf7df6ad560a.JPG)

**Comment by Garfonso** [comment]
Hi.

Das kann ich hier so nicht reproduzieren. Ich habe viele Lampen mit Farbe, die ich auch regelmäßig über lovelace steuere... hm. 

Ich weiß ehrlich gesagt auch nicht so richtig, wo das herkommen soll.

Vielleicht noch interessant: Welche Version von lovelace ist das?

Was zur Eingrenzung auch interessant wäre, ist bei dem "grün" Datenpunkt history anmachen mit "sender" und gucken, wer daran rumschaltet. "Nach ca. 2 Sekunden" hört sich etwas danach an, dass die Lampe halt ein update schickt.

**Comment by ElRedef** [comment]
Hi,

Lovelace Version 2.0.6

Sind deine Farblampen Hue? 
Die Hue Lampen sind ja irgendwie besonders (z.b. 2 mal level.dimmer, das level.color.hue Attribut)

Versuch:

1. Alle Datenpunkte der Lampe auf History geschaltet.
2. Auf 67% gestellt -> springt auf 100%
3. Auf 49% gestellt -> hat funktioniert (ja, manchmal tut es)
4. auf 22% gestellt -> springt auf 100%
5. auf 90% mit dem Custom Slider gestellt -> hat funktioniert
6. Historie angeschaut und von Änderungen einen Screenshot gemacht -> siehe unten

Ergebnis: Lovelace schreibt keinen der Punkte ????? 
Aber welchen dann? Ich habe mal einen Screenshot angehängt aus dem Einstellungsdialog. 

Der Level enthält exakt das Resultat von oben: 100/49/100/90


![Entitaeten](https://user-images.githubusercontent.com/66745270/142076028-9dbaf3a8-afff-4b9a-913f-f51c59cf4cb2.JPG)

Anmerkung zum Lesen: Der Versuch beginnt um 20:31 Uhr. Alle Datenpunkte vorher kannst du ignorieren. 

![xy](https://user-images.githubusercontent.com/66745270/142075329-408b3c10-fdc6-431d-a53e-0fe509041355.JPG)
![b](https://user-images.githubusercontent.com/66745270/142075334-9d430ec3-1dbe-43df-85c8-e9002ffc1f00.JPG)
![bri](https://user-images.githubusercontent.com/66745270/142075336-4c4b81f1-6985-4d29-a52e-0c9baeb154b2.JPG)
![g](https://user-images.githubusercontent.com/66745270/142075337-ece1c834-187e-464c-bc98-615e2a069f0c.JPG)
![level](https://user-images.githubusercontent.com/66745270/142075339-aadc780e-dd13-4be0-be77-6de57becfa96.JPG)
![r](https://user-images.githubusercontent.com/66745270/142075340-191e8c09-1784-4a98-8028-c112a8ac5bdb.JPG)
![sat](https://user-images.githubusercontent.com/66745270/142075343-4ae8de33-89be-4b75-a3c4-5235ef7f8c8e.JPG)

**Comment by ElRedef** [comment]
Hmm,

versuche sind dann gut wenn Sie sich reproduzieren lassen. Der oben lässt sich nicht reproduzieren. 
Jetzt schreibt lovelace zuverlässig in level.color.blue und einmal sogar in level.dimmer (ich kann nicht sagen ob das ein Versuch war bei dem nicht auf 100% gesprungen wurde). 

Ich vermute die Unzuverlässigkeit der Versuche liegen am HistoryAdapter bzw. an meiner Konfiguration von ihm. (Schmeisst evtl. zu schnelle Wertänderungen wieder raus). Muss ich mir wann anders anschauen (zu müde gerade). 

Ich denk aber: Lovelace schreibt manchmal nicht level.dimmer sondern level.color.blue


![b](https://user-images.githubusercontent.com/66745270/142079432-18966ff0-85bc-4f57-b06a-39966d17da98.JPG)

![level](https://user-images.githubusercontent.com/66745270/142079444-586b4595-bce7-4097-9547-ce758383dc89.JPG)

**Comment by ElRedef** [comment]
Versuch 3:

Erkenntnis: Schaue ich dem History Adapter 'live' zu (mit offenem Datenpunktfenster) zeigt er mehr an. Schliese und öffne ich das Fenster sind manche Datenpunkte weg (Vermutung: Wenn Ack == false )

Was unten mit blau gezeigt wurde passiert mit allen 3 Farben (keine Screenshots gemacht).

Erkentnis:
- Lovelace schreibt in diesem Dialog in die drei Farben und bekommt aber Ack = false. Danach schickt die Lampe wohl ihren Zustand.
- Der Wert den Lovelace in die Farbe schreibt ist nicht der Helligkeitswert. Der Wert ist von der Farbe abhängig (Vermutlich aktueller Farbwert)
- Lovelace schreibt in  Level. Ack aber auch false
- Die Custom Slider Entity schreibt keine Farbwerte. Er schreibt aber den Level. Bekommt aber trotzdem Ack=False


Level (Live):
![level_vorher](https://user-images.githubusercontent.com/66745270/142182278-dda3bdb5-1865-4038-a3fb-dd3aace8bd7c.JPG)

Level (Fenster zu und wieder auf):
![level_nachher](https://user-images.githubusercontent.com/66745270/142182558-79d97a12-36b3-40f5-8412-af4c5f1b0d25.JPG)

b (Live):

![b_vorher](https://user-images.githubusercontent.com/66745270/142182603-d55dc9e9-aed8-4344-9007-5dd56f1c769c.JPG)

b (Fenster zu und wieder auf)
![b_nachher](https://user-images.githubusercontent.com/66745270/142182651-b690ea4a-196c-42fe-93c0-12c7149ec9a0.JPG)

**Comment by Garfonso** [comment]
zur Erklärung mit dem `ack`: `ack` = `false` bedeutet im ioBroker Umfeld quasi "Befehl" und `ack` = `true` bedeutet, dass der Wert vom Gerät gemeldet wurde. Insofern setzt lovelace immer ack = false, wenn es irgendwo einen State ändert. :-)

Kannst du einen Export von dem kompletten Objektbaum machen? (in admin -> objekte). Dann guck ich mal, ob mir dabei was auffällt... 

Es ist etwas merkwürdig, dass die Farben mitgesteuert werden. Das "sollte" eigentlich nicht passieren. Bei meinen tests gestern passierte das auch nicht... Meine Lampen sind tatsächlich nicht hue (nicht direkt zumindest ;-) ). Wenn du mir den Objektbaum schickst, kann ich aber gucken, wie die Objekte vom type-detector den Funktionen einer Lampe zugeordnet werden und vielleicht kann ich dann was sehen.

**Comment by ElRedef** [comment]
[hue.0.Stehlampe_oben.txt](https://github.com/ioBroker/ioBroker.lovelace/files/7557719/hue.0.Stehlampe_oben.txt)

Hiermit der Export

**Comment by ElRedef** [comment]
Hi,

noch ein Versuch.
Gedanke: Eigentlich ist es doch nichts böses den korrekten Farbwert  zu schreiben. Das müsste die Lampe doch abkönnen. 

Ich habe per Script versucht nach zu machen was lovelace tut.
`
setState('hue.0.Stehlampe_oben.b',70)
setState('hue.0.Stehlampe_oben.r',60)
setState('hue.0.Stehlampe_oben.g',60)
setState('hue.0.Stehlampe_oben.level',70)
`
Mit mehreren unterschiedlichen Werten probiert. Funktioniert immer korrekt(springt nie auf 100)

Es muss also beim Verhalten von Lovelace noch eine Besonderheit geben

**Comment by Garfonso** [comment]
Hm.. ok.. es scheint zum Teil vom Frontend zu kommen.. und zwar jenachdem, was die Lampe zurück meldet. Muss ich nochmal im Code gucken... ich sollte auch das Frontened nochmal aktualisieren..

Also es kann da passieren, dass lovelace (also das Frontend schon) den befehl gibt Farbe und Helligkeit zu setzen, wenn man am Helligkeitsslider schiebt. Dabei hab ich dann bei mir gesehen, dass ich Helligkeit auf ~80% setze, aber in der Farbe [255,0,0] (also volles rot) drin stand. Das würde ich als Lampe jetzt auch so interpretieren, dass Helligkeit auf 100% gehen soll (sonst müsste man ca. [200, 0, 0] setzen für 80% Helligkeit).

**Comment by ElRedef** [comment]
Ich habe mit dem Geräteadapter eine "HueLampe" angelegt. Diese hat keine r,g,b Attribute sondern nur ein 'hue' Attribut für die Farbe.

Diese Lampe kann man ohne Probleme dimmen (das hier beschriebene Phänomen tritt also nicht auf). 
Die Farbe kann man auch einstellen. Allerdings kann die Farbe nicht gelesen werden, soll heißen Lovelace zeigt die aktuelle Farbe nicht an.

Für mich ist das verschmerzbar und ein guter Workaround. Wenn du weiter an dem Thema dran bleiben willlst helfe ich aber auch gerne weiter mit!

Auf jeden Fall vielen Dank für deine ganze Mühe mir zu helfen! 

Hier noch das aktuelle Gerät (Ist eine andere Lampe, hatte aber vorher den selben Effekt):


![hue](https://user-images.githubusercontent.com/66745270/142925608-6778b740-e25e-4c0d-8be4-3cc4ae6e709f.JPG)

**Comment by Garfonso** [comment]
still need to find time to look into it.

**Comment by Garfonso** [comment]
sollte mit neueren Versionen nicht mehr passieren, da sich an dem Code *sehr* viel geändert hat, auch im frontend.
