### ISSUE TITLE
Adapter Rot V 0.0.2 und 0.0.3

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.lovelace#3]
Edit: Er wird Grün und nach 2-3 Sekunden Rot......
Neustart das selben Problem.

**Screenshots & Logfiles**  
`

lovelace.0 | 2019-06-03 09:08:34.839 | info | cleaned everything up...
-- | -- | -- | --
lovelace.0 | 2019-06-03 09:08:33.829 | info | cleaned everything up...
lovelace.0 | 2019-06-03 09:08:33.829 | error | at Manager.Emitter.emit (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
lovelace.0 | 2019-06-03 09:08:33.829 | error | at Manager.<anonymous> (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
lovelace.0 | 2019-06-03 09:08:33.829 | error | at Socket.onpacket (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:236:12)
lovelace.0 | 2019-06-03 09:08:33.829 | error | at Socket.onack (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:312:9)
lovelace.0 | 2019-06-03 09:08:33.829 | error | at Socket.<anonymous> (C:\ioBroker\node_modules\iobroker.js-controller\lib\states\statesInMemClient.js:157:27)
lovelace.0 | 2019-06-03 09:08:33.829 | error | at that.states.getStates (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:4540:25)
lovelace.0 | 2019-06-03 09:08:33.829 | error | at adapter.getForeignStates (C:\ioBroker\node_modules\iobroker.lovelace\lib\server.js:1562:29)
lovelace.0 | 2019-06-03 09:08:33.829 | error | at Array.forEach (<anonymous>)
lovelace.0 | 2019-06-03 09:08:33.829 | error | at ids.forEach (C:\ioBroker\node_modules\iobroker.lovelace\lib\server.js:1570:33)
lovelace.0 | 2019-06-03 09:08:33.829 | error | at setJsonAttribute (C:\ioBroker\node_modules\iobroker.lovelace\lib\server.js:109:24)
lovelace.0 | 2019-06-03 09:08:33.829 | error | TypeError: Cannot read property 'split' of undefined
lovelace.0 | 2019-06-03 09:08:33.829 | error | uncaught exception: Cannot read property 'split' of undefined

`

**Versions:**  
Platform: Windows
Architecture: x64
CPUs: 4
Speed: 3912 MHz
Model: Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
RAM: 7.9 GB 
Node.js: v8.16.0
NPM: 6.4.1
ioBroker.js-controller: 1.5.12
Admin: 3.6.3

**Additional context**

**Comment by holger05** [comment]
Bei mir läuft die 0.02:


ubuntu

Betriebssystem
    linux
Architektur
    x64
CPUs
    1
Geschwindigkeit
    1497 MHz
Modell
    Common KVM processor
RAM
    1.95 GB
System Betriebszeit
    10 T. 05:09:12
Node.js
    v8.16.0
NPM
    6.4.1
Festplatte Größe
    9.78 GB
Festplatte frei
    3.5 GB
Anzahl der Adapter
    277
Betriebszeit
    10 T. 05:09:00
Aktive Instanzen
    26
Hostname
    ubuntu

**Comment by sigi2345** [comment]
Also, was neues: 
Adapter auf ein neues System installiert. Kein Fehler.
Aber wenn man eine Falsche ID eingibt kommt der Fehler.

**Comment by GermanBluefox** [comment]
Please try the version from github

**Comment by sigi2345** [comment]
Ok, Adapter Grün, Danke!
LOG:
`

lovelace.0 | 2019-06-04 23:40:00.473 | debug | sendTo "getHistory" to system.adapter.history.0 from system.adapter.lovelace.0
-- | -- | -- | --
lovelace.0 | 2019-06-04 23:40:00.472 | debug | Get history for sensor.Aussentemperatur from 2019-06-03T21:40:00.467Z to 2019-06-04T21:40:00.467Z
lovelace.0 | 2019-06-04 23:38:01.391 | debug | sendTo "getHistory" to system.adapter.history.0 from system.adapter.lovelace.0
lovelace.0 | 2019-06-04 23:38:01.391 | debug | Get history for sensor.Aussentemperatur from 2019-06-03T21:38:01.285Z to 2019-06-04T21:38:01.285Z
lovelace.0 | 2019-06-04 23:35:55.730 | debug | sendTo "getHistory" to system.adapter.history.0 from system.adapter.lovelace.0
lovelace.0 | 2019-06-04 23:35:55.730 | debug | Get history for sensor.Aussentemperatur from 2019-06-03T21:35:55.726Z to 2019-06-04T21:35:55.726Z
lovelace.0 | 2019-06-04 23:35:51.793 | debug | sendTo "getHistory" to system.adapter.history.0 from system.adapter.lovelace.0
lovelace.0 | 2019-06-04 23:35:51.793 | debug | Get history for sensor.Aussentemperatur from 2019-06-03T21:35:51.790Z to 2019-06-04T21:35:51.790Z
lovelace.0 | 2019-06-04 23:35:51.763 | debug | IoB Subscribe on hue.0.Philips_hue.Schlafzimmer.level
lovelace.0 | 2019-06-04 23:35:51.763 | debug | IoB Subscribe on hue.0.Philips_hue.Schlafzimmer.on
lovelace.0 | 2019-06-04 23:35:39.864 | debug | sendTo "getHistory" to system.adapter.history.0 from system.adapter.lovelace.0
lovelace.0 | 2019-06-04 23:35:39.864 | debug | Get history for sensor.Aussentemperatur from 2019-06-03T21:35:39.860Z to 2019-06-04T21:35:39.860Z
lovelace.0 | 2019-06-04 23:35:39.829 | debug | IoB Subscribe on hue.0.Philips_hue.Bad.level
lovelace.0 | 2019-06-04 23:35:39.829 | debug | IoB Subscribe on hue.0.Philips_hue.Bad.on
lovelace.0 | 2019-06-04 23:35:19.102 | debug | sendTo "getHistory" to system.adapter.history.0 from system.adapter.lovelace.0
lovelace.0 | 2019-06-04 23:35:19.101 | debug | Get history for sensor.Aussentemperatur from 2019-06-03T21:35:19.097Z to 2019-06-04T21:35:19.097Z
lovelace.0 | 2019-06-04 23:35:19.046 | debug | IoB Subscribe on linkeddevices.0.Wetter.temp_value
lovelace.0 | 2019-06-04 23:35:17.306 | debug | sendTo "getHistory" to system.adapter.history.0 from system.adapter.lovelace.0
lovelace.0 | 2019-06-04 23:35:17.305 | debug | Get history for sensor.Aussentemperatur from 2019-06-03T21:35:17.301Z to 2019-06-04T21:35:17.301Z
lovelace.0 | 2019-06-04 23:35:13.087 | debug | sendTo "getHistory" to system.adapter.history.0 from system.adapter.lovelace.0
lovelace.0 | 2019-06-04 23:35:13.087 | debug | Get history for sensor.Aussentemperatur from 2019-06-03T21:35:13.082Z to 2019-06-04T21:35:13.082Z
lovelace.0 | 2019-06-04 23:34:51.273 | warn | No code is defined! To provide the code add to object lovelace.0.control.alarm native.alarm_code with desired code
lovelace.0 | 2019-06-04 23:34:51.272 | debug | XXX
lovelace.0 | 2019-06-04 23:34:47.212 | debug | XXX
lovelace.0 | 2019-06-04 23:34:32.075 | debug | IoB Subscribe on lovelace.0.control.alarm
lovelace.0 | 2019-06-04 23:34:31.072 | debug | XXX
lovelace.0 | 2019-06-04 23:34:25.512 | debug | XXX
lovelace.0 | 2019-06-04 23:34:19.765 | warn | No code is defined! To provide the code add to object lovelace.0.control.alarm native.alarm_code with desired code
lovelace.0 | 2019-06-04 23:34:19.763 | debug | XXX
lovelace.0 | 2019-06-04 23:33:29.208 | debug | HASS Subscribe: persistent_notifications_updated
lovelace.0 | 2019-06-04 23:33:29.184 | debug | get config: false
lovelace.0 | 2019-06-04 23:33:29.040 | debug | Get translations: de
lovelace.0 | 2019-06-04 23:33:29.040 | debug | Get USER Data: language
lovelace.0 | 2019-06-04 23:33:29.032 | debug | HASS Subscribe: themes_updated
lovelace.0 | 2019-06-04 23:33:29.031 | debug | HASS Subscribe: service_removed
lovelace.0 | 2019-06-04 23:33:29.031 | debug | HASS Subscribe: service_registered
lovelace.0 | 2019-06-04 23:33:29.030 | debug | HASS Subscribe: component_loaded
lovelace.0 | 2019-06-04 23:33:29.029 | debug | HASS Subscribe: state_changed
lovelace.0 | 2019-06-04 23:33:28.916 | debug | HASS Auth: 61db193a67e606102717d9bcb43ec3d72379971763c4308dd13d64dfd74a348b
lovelace.0 | 2019-06-04 23:33:24.986 | error | Invalid attribute name for {"friendly_name":"Multimedia Badzimmer","entity_picture":"./adapter/alexa2/icons/echo_dot.png","icon":"mdi:play-network","media_content_type":"unknown","supported_features"
lovelace.0 | 2019-06-04 23:33:24.983 | error | Invalid attribute name for {"friendly_name":"Multimedia Küche","entity_picture":"./adapter/alexa2/icons/echo_dot.png","icon":"mdi:play-network","media_content_type":"unknown","supported_features":174
lovelace.0 | 2019-06-04 23:33:24.978 | error | Invalid attribute name for {"friendly_name":"Multimedia roomLivingRoom","entity_picture":"./adapter/alexa2/icons/echo_dot.png","icon":"mdi:play-network","media_content_type":"unknown","supported_feat
lovelace.0 | 2019-06-04 23:33:24.972 | debug | Create manual device: alarm_control_panel.defaultAlarm - lovelace.0.control.alarm
lovelace.0 | 2019-06-04 23:33:24.971 | debug | Create manual device: sensor.Aussentemperatur - linkeddevices.0.Wetter.temp_value
lovelace.0 | 2019-06-04 23:33:24.969 | debug | Create manual device: sensor.Aussentemperatur - daswetter.0.NextHours.Location_1.Day_1.current.temp_value
lovelace.0 | 2019-06-04 23:33:24.769 | debug | AUTO Device detected: yamaha.0.Commands => switch
lovelace.0 | 2019-06-04 23:33:24.769 | debug | AUTO Device detected: alexa2.0.Echo-Devices.G090LF1182231CD6 => switch
lovelace.0 | 2019-06-04 23:33:24.769 | debug | AUTO Device detected: alexa2.0.Echo-Devices.G090LF1182231CD6 => geo_location
lovelace.0 | 2019-06-04 23:33:24.769 | debug | AUTO Device detected: alexa2.0.Echo-Devices.G090LF11804214T6 => switch
lovelace.0 | 2019-06-04 23:33:24.769 | debug | AUTO Device detected: alexa2.0.Echo-Devices.G090LF11804214T6 => geo_location
lovelace.0 | 2019-06-04 23:33:24.769 | debug | AUTO Device detected: alexa2.0.Echo-Devices.G090LF09643501XG => switch
lovelace.0 | 2019-06-04 23:33:24.769 | debug | AUTO Device detected: alexa2.0.Echo-Devices.G090LF09643501XG => geo_location
lovelace.0 | 2019-06-04 23:33:24.769 | debug | AUTO Device detected: hue.0.Philips_hue.Schlafzimmer => light
lovelace.0 | 2019-06-04 23:33:24.769 | debug | AUTO Device detected: hue.0.Philips_hue.Bad => light
lovelace.0 | 2019-06-04 23:33:24.769 | debug | [Type-Detector] device hm-rpc.1.NEQ1662322.1.INHIBIT - info - hm-rpc.1.NEQ1662322.1 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.769 | debug | [Type-Detector] device hm-rpc.1.NEQ1662322.4.DECISION_VALUE - info - hm-rpc.1.NEQ1662322.4 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.769 | debug | [Type-Detector] device hm-rpc.1.NEQ1662322.5.DECISION_VALUE - info - hm-rpc.1.NEQ1662322.5 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.769 | debug | [Type-Detector] device hm-rpc.1.NEQ1662322.2.BOOT - info - hm-rpc.1.NEQ1662322.2 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.769 | debug | [Type-Detector] device hm-rpc.1.NEQ1662322.3.DECISION_VALUE - info - hm-rpc.1.NEQ1662322.3 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.769 | debug | [Type-Detector] device hm-rpc.1.NEQ1662322.6.DECISION_VALUE - info - hm-rpc.1.NEQ1662322.6 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.769 | debug | [Type-Detector] device hs100.0.192_168_178_43.totalNow - info - hs100.0.192_168_178_43.totalNow is not yet supported
lovelace.0 | 2019-06-04 23:33:24.769 | debug | [Type-Detector] device hs100.0.192_168_178_43.totalMonthNow - info - hs100.0.192_168_178_43.totalMonthNow is not yet supported
lovelace.0 | 2019-06-04 23:33:24.768 | debug | [Type-Detector] device hs100.0.192_168_178_43.sw_ver - info - hs100.0.192_168_178_43.sw_ver is not yet supported
lovelace.0 | 2019-06-04 23:33:24.768 | debug | [Type-Detector] device hs100.0.192_168_178_43.state - info - hs100.0.192_168_178_43.state is not yet supported
lovelace.0 | 2019-06-04 23:33:24.768 | debug | [Type-Detector] device hs100.0.192_168_178_43.power - info - hs100.0.192_168_178_43.power is not yet supported
lovelace.0 | 2019-06-04 23:33:24.768 | debug | [Type-Detector] device hs100.0.192_168_178_43.model - info - hs100.0.192_168_178_43.model is not yet supported
lovelace.0 | 2019-06-04 23:33:24.768 | debug | [Type-Detector] device hs100.0.192_168_178_43.mac - info - hs100.0.192_168_178_43.mac is not yet supported
lovelace.0 | 2019-06-04 23:33:24.768 | debug | [Type-Detector] device hs100.0.192_168_178_43.last_update - info - hs100.0.192_168_178_43.last_update is not yet supported
lovelace.0 | 2019-06-04 23:33:24.768 | debug | [Type-Detector] device hs100.0.192_168_178_43.hw_ver - info - hs100.0.192_168_178_43.hw_ver is not yet supported
lovelace.0 | 2019-06-04 23:33:24.767 | debug | [Type-Detector] device hm-rpc.1.NEQ1818500.1.ERROR - info - hm-rpc.1.NEQ1818500.1 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.767 | debug | [Type-Detector] device hm-rpc.1.NEQ1826414.1.ERROR - info - hm-rpc.1.NEQ1826414.1 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.767 | debug | [Type-Detector] device hm-rpc.1.NEQ1826414.0.AES_KEY - info - hm-rpc.1.NEQ1826414 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.767 | debug | [Type-Detector] device hm-rpc.1.NEQ1818500.0.AES_KEY - info - hm-rpc.1.NEQ1818500 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.767 | debug | [Type-Detector] device hm-rpc.1.OEQ0926852.1.ERROR - info - hm-rpc.1.OEQ0926852.1 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.767 | debug | [Type-Detector] device hm-rpc.1.OEQ0926852.0.AES_KEY - info - hm-rpc.1.OEQ0926852 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.767 | debug | [Type-Detector] device hm-rpc.0.CUX2801003.4.CMD_EXEC - info - hm-rpc.0.CUX2801003.4 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.767 | debug | [Type-Detector] device hm-rpc.0.CUX2801006.9.CMD_EXEC - info - hm-rpc.0.CUX2801006.9 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.760 | debug | [Type-Detector] device hm-rpc.0.CUX2801006.16.CMD_EXEC - info - hm-rpc.0.CUX2801006.16 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.760 | debug | [Type-Detector] device hm-rpc.0.CUX2801006.15.CMD_EXEC - info - hm-rpc.0.CUX2801006.15 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.760 | debug | [Type-Detector] device hm-rpc.0.CUX2801006.14.CMD_EXEC - info - hm-rpc.0.CUX2801006.14 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.760 | debug | [Type-Detector] device hm-rpc.0.CUX2801006.13.CMD_EXEC - info - hm-rpc.0.CUX2801006.13 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.760 | debug | [Type-Detector] device hm-rpc.0.CUX2801006.12.CMD_EXEC - info - hm-rpc.0.CUX2801006.12 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.760 | debug | [Type-Detector] device hm-rpc.0.CUX2801006.11.CMD_EXEC - info - hm-rpc.0.CUX2801006.11 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.760 | debug | [Type-Detector] device hm-rpc.0.CUX2801006.10.CMD_EXEC - info - hm-rpc.0.CUX2801006.10 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.760 | debug | [Type-Detector] device hm-rpc.0.CUX2801006.8.CMD_EXEC - info - hm-rpc.0.CUX2801006.8 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.760 | debug | [Type-Detector] device hm-rpc.0.CUX2801006.7.CMD_EXEC - info - hm-rpc.0.CUX2801006.7 is not yet supported
lovelace.0 | 2019-06-04 23:33:24.760 | debug | [Type-Detector] device hm-rpc.0.CUX2801006.6.CMD_EXEC - info - hm-rpc.0.CUX2801006.6 is not yet supported

`

**Comment by sigi2345** [comment]
Hinweis:
Der Adapter verliert bzw. findet zeitweise die entities (ID)

**Comment by holger05** [comment]
Warum beginnen deine ersten Entities mit einem Punkt (ohne Typ) davor? Versuche die doch mal fest auf einen Wert zu stellen. Haustür = lock, Heizkörper = climate.
![grafik](https://user-images.githubusercontent.com/33962350/58939169-e0dd4900-8776-11e9-87a3-6dda1b13c1f0.png)

**Comment by GermanBluefox** [comment]
Option "auto" bei den Typen funktioniert noch nicht.

**Comment by GermanBluefox** [comment]
Gibt es hier was neues mit 0.1.0?

**Comment by sigi2345** [comment]
> Gibt es hier was neues mit 0.1.0?

Läuft bis jetzt stabil.

**Comment by sigi2345** [comment]
![Screenshot (3403)](https://user-images.githubusercontent.com/41079106/59101764-54738780-892a-11e9-9a2c-23addf1b859b.png)
![Screenshot (3404)](https://user-images.githubusercontent.com/41079106/59101765-54738780-892a-11e9-947e-95ba4356902d.png)
