### ISSUE TITLE
Scenes and Javascript Values are not updated - only after restart of Lovelace adapter

### ISSUE THREAD

**Issue by arndth** [ioBroker/ioBroker.lovelace#303]
**Describe the bug**  
I have created manual variables and added these as sensor or light to Lovelace. But they do not get updated. One is related to number increased with JS and the other is related to a scene which considers the status auf 7 lights. 

It shows initially the status but it gets no updates. Only after restart of Lovelace adapter it receives an update.
I was thinking if this was related to this issue: https://github.com/ioBroker/ioBroker.lovelace/issues/93 or maybe there is an issue in current lovelace release and I have to get an earlier version. 

Somewhere in Lovelace there was also an error which might was corrected with latest version:
https://community.home-assistant.io/t/values-not-updating-unless-i-refresh-page/264941/7

Has someone similiar issues? Or can confirm the behaviour?

Node.js Version:v14.18.1 
JS Controller: 3.3.22
OS: ubuntu

**Comment by Garfonso** [comment]
Hi,

how are the entities used in your configuration?

The adapter scans your configuration (i.e. the lovelace cards you defined and so on) and tries to figure out which entities you use and which not. It will only subscribe the used entities for updates. 
Your issue sounds like the adapter does not understand that you use the entities in question and therefore does not subscribe to updates. 

There were some issues with that in the past with mini-graph-card and also tankerkoenig, which should be fixed (sadly that is not yet in latest... if you want to try, you can try to install from github https://github.com/ioBroker/ioBroker.lovelace and see if that fixes the issue for you - it should add everything that looks like an entity_id in the lovelace configuration to the subscriptions).

Currently the auto-entities-card will still cause this issue (and maybe other cards that use a regular expression filter on entity ids).

**Comment by arndth** [comment]
Booth in combination of the button-card.. 
How can I update an update via github? Or do I need a new instance?

            - type: 'custom:button-card'
              template: chip_icon_briefkasten
              variables:
                ulm_chip_icon_state_icon: '📫'
                ulm_chip_icon_state_entity: sensor.NewMail

**Comment by Garfonso** [comment]
Ok, that should be fixed in next version.

You can install via admin. Go to adapters, enable expert mode and then there should be a button above the adapters table with github icon. That will allow to install an adapter by URL (third tab in the new window, if you press the button).

If something goes wrong, you can go back with the plus-sign at the end of the line for an adapter (only visible in expert mode, too).

**Comment by arndth** [comment]
works - Thanks you! 💯
