### ISSUE TITLE
Gauge card wrong visualization

### ISSUE THREAD

**Issue by aendue** [ioBroker/ioBroker.lovelace#320]
**Describe the bug**  
Gauge Card visualization faulty
Line of current state is displaced.

**To Reproduce**  
1. Create gauge card in visa
2. Add sensor value
YAML:

type: gauge
min: 0
max: 100
entity: sensor.Kinderzimmer_Stellantrieb_1

**Screenshots & Logfiles**  
See attached

**Versions:**  
 - Adapter version: v2.0.6
 - JS-Controller version: 3.3.22
 - Node version: v12.22.5
 - Operating system: linux (unraid docker)

<img width="869" alt="Bildschirmfoto 2022-02-08 um 20 25 38" src="https://user-images.githubusercontent.com/8988228/153202028-00d21b85-3f77-4a20-aaf7-31ac82c43339.png">

**Comment by Garfonso** [comment]
Can you check with current (2.2.) beta release?

**Comment by RobertTUB** [comment]
Hi! I run into the same issue a few weeks ago. There was a pull request in https://github.com/home-assistant/frontend/pull/11363 which fixed the issue in HA. The commits are included in Tag 20220124 of the HA Frontend repo. I got a little lost in how the projects are related but the changes SHOULD be included in the current Tag 2.2 of this repo  - at least I thought so. What am I missing?

**Comment by Garfonso** [comment]
No. 

Regarding the "how the projects are related": we maintain our own fork of HomeAssistant Fronted ([here](https://github.com/Garfonso/home-assistant-polymer/tree/iob) and [here](https://github.com/GermanBluefox/home-assistant-polymer/tree/iob), it is not merged that often..., which is partly my fault).

The current stable / latest releases are still on a 2021 version of the frontend. Sadly, there is no easy way to see that, so you'll have to search through the changelog, and it seems 2.1.0 was the last frontend update: https://github.com/ioBroker/ioBroker.lovelace/blob/master/CHANGELOG_OLD.md#210-2022-01-06

The version currently on git is updated to 20220706.0. But I did not yet manage to create a new release... I plan to do that soonish, but can not promise anything.
You can try to install the adapter from GitHub and see if the issue persists. It should be gone, as you found out by research in the home-assistant repository. But I could never reproduce the issue, so I can not be sure.

**Comment by RobertTUB** [comment]
Hi! Thanks for the last release build, that fixed the issue - at least for me :)

**Comment by Garfonso** [comment]
Tahnks for reporting back.
