### ISSUE TITLE
Lovelace warning message: Got duplicate for entity with homee - ioBroker - lovelace

### ISSUE THREAD

**Issue by knirsch1** [ioBroker/ioBroker.lovelace#358]
I am using "homee" as a smarthome gateway. I use ioBroker and the "[homee-connector](https://github.com/Apollon77/ioBroker.homee)" to synchronize the sensors and actuators. My dashboard I currently have in the VIS is to be solved by lovelace. 

Lovelace - shows an error message for each connected sensor or actuator. The messages are created per sensor/actuator about every 10min. The error log fills up very quickly with this. 

**Target:**
Do you guys have a solution? Is it because of the configuration?

**Example:**
_Got duplicate for entity sensor.TemperatureAndHumiditySensor_131_Temperature_685. Overwriting old value. Was for homee.0.TemperatureAndHumiditySensor-131.Temperature-685 and new one is for homee.0.TemperatureAndHumiditySensor-131.Temperature-685_

![Bildschirmfoto 2022-05-10 um 12 49 17](https://user-images.githubusercontent.com/105284628/167614203-26764114-a511-4882-aedb-136b76b30028.png)

I have connected sensors like this. The warning message also comes when I change the "Entity name".

![Bildschirmfoto 2022-05-10 um 12 50 19](https://user-images.githubusercontent.com/105284628/167614247-4ed18793-dbf8-4d1d-b80b-fa3c8d636ff2.png)

 It also makes no difference if I set it at "Alias.0.* or "Check the alarm code....". 
![Bildschirmfoto 2022-05-10 um 12 51 23](https://user-images.githubusercontent.com/105284628/167614276-9fd1d18f-b1fc-46b2-8ef8-4661688d0d93.png)

**Comment by Garfonso** [comment]
This is actually a bug in the current version. It is already fixed, but not yet released (working on it, sorry).

It only happens for manually configured devices. Temperature sensors should be automatically detected. If every sensor is in a separate folder (or device) you could disable the lovelace settings and add room & function (if not happend already) to the folders (i.e. homee.0.TemperatureAndHumiditySensor-131 in the example) and they should be auto detected (entity id is then based on device name).

**Comment by knirsch1** [comment]
Great, thanks for the info. Do you have a tendency when the new version with the fixed bug will be released? Maybe in Q2 of this year?

**Comment by Garfonso** [comment]
Should be close.

**Comment by Garfonso** [comment]
this is now in beta.

**Comment by knirsch1** [comment]
I manually installed version 2.20 into ioBroker last night. So far, there are no more warnings on the linked sensors.
