### ISSUE TITLE
RequestForComment - Enhancement common.states

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.lovelace#359]
Hi @Garfonso,

we plan to enhance the definition of common.states  definitoipn as described in https://github.com/ioBroker/ioBroker.docs/pull/387/files

Please provide feedback and also an info if you would support this as adjustment in the adapter in the future.

Thank you

Ingo

**Comment by Garfonso** [comment]
Thanks for the hint. The feature is already supported by lovelace (where possible). :-)
