### ISSUE TITLE
Adapter startet nicht (Fehler im LOG)

### ISSUE THREAD

**Issue by overfl0w72** [ioBroker/ioBroker.lovelace#37]
Nabend zusammen, erstmal danke für den vielversprechenden Adapter.
Leider kommt bei mir nach der Installation sobald ich den Adapter starte ein Error mit folgendem Inhalt:

`

Caught | 2019-09-22 20:26:37.444 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.lovelace/node_modules/ws/index.js:3:19)
-- | -- | -- | --
Caught | 2019-09-22 20:26:37.444 | error | by controller[0]: at require (internal/module.js:20:19)
Caught | 2019-09-22 20:26:37.444 | error | by controller[0]: at Module.require (module.js:504:17)
Caught | 2019-09-22 20:26:37.444 | error | by controller[0]: at Function.Module._load (module.js:445:3)
Caught | 2019-09-22 20:26:37.443 | error | by controller[0]: at tryModuleLoad (module.js:453:12)
Caught | 2019-09-22 20:26:37.443 | error | by controller[0]: at Module.load (module.js:494:32)
Caught | 2019-09-22 20:26:37.443 | error | by controller[0]: at Object.Module._extensions..js (module.js:586:10)
Caught | 2019-09-22 20:26:37.443 | error | by controller[0]: at Module._compile (module.js:549:28)
Caught | 2019-09-22 20:26:37.443 | error | by controller[0]: at Object.runInThisContext (vm.js:97:10)
Caught | 2019-09-22 20:26:37.443 | error | by controller[0]: at createScript (vm.js:56:10)
Caught | 2019-09-22 20:26:37.443 | error | by controller[0]: SyntaxError: Unexpected token ...
Caught | 2019-09-22 20:26:37.443 | error | by controller[0]: ^^^
Caught | 2019-09-22 20:26:37.442 | error | by controller[0]: ...options
Caught | 2019-09-22 20:26:37.442 | error | by controller[0]: /opt/iobroker/node_modules/iobroker.lovelace/node_modules/ws/lib/websocket.js:347
Caught | 2019-09-22 20:26:06.657 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.lovelace/node_modules/ws/index.js:3:19)
Caught | 2019-09-22 20:26:06.657 | error | by controller[0]: at require (internal/module.js:20:19)
Caught | 2019-09-22 20:26:06.657 | error | by controller[0]: at Module.require (module.js:504:17)
Caught | 2019-09-22 20:26:06.656 | error | by controller[0]: at Function.Module._load (module.js:445:3)
Caught | 2019-09-22 20:26:06.656 | error | by controller[0]: at tryModuleLoad (module.js:453:12)
Caught | 2019-09-22 20:26:06.656 | error | by controller[0]: at Module.load (module.js:494:32)
Caught | 2019-09-22 20:26:06.656 | error | by controller[0]: at Object.Module._extensions..js (module.js:586:10)
Caught | 2019-09-22 20:26:06.656 | error | by controller[0]: at Module._compile (module.js:549:28)
Caught | 2019-09-22 20:26:06.656 | error | by controller[0]: at Object.runInThisContext (vm.js:97:10)
Caught | 2019-09-22 20:26:06.656 | error | by controller[0]: at createScript (vm.js:56:10)
Caught | 2019-09-22 20:26:06.653 | error | by controller[0]: SyntaxError: Unexpected token ...
Caught | 2019-09-22 20:26:06.653 | error | by controller[0]: ^^^
Caught | 2019-09-22 20:26:06.653 | error | by controller[0]: ...options
Caught | 2019-09-22 20:26:06.652 | error | by controller[0]: /opt/iobroker/node_modules/iobroker.lovelace/node_modules/ws/lib/websocket.js:347

`

Ich hoffe jemand kann mir weiterhelfen.. Danke im Voraus

Gruß overfl0w

**Comment by GermanBluefox** [comment]
Bitte node.js 8 benutzen
