### ISSUE TITLE
instances objects without function

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.lovelace#379]
**Describe the bug**  
Objects under instances have no function. Nothing is happen when using them.
They also are not acknowledged.

**To Reproduce**  
1. Go to 'object tab'
2. Open the tree for lovelace.0.instances
3. Try to control any of the objects listet there

**Expected behavior**  
Something should happen, show toast message, refresh view or for what ever the objects are.

**Screenshots & Logfiles**  
Nothing to show, no information in the log, also not in debug mode. 

**Versions:**  
 - Adapter version: 2.2.0
 - JS-Controller version: 4.0.23
 - Node version: 18.7.0
 - Operating system: ubuntu

**Additional context**  
None for now

**Comment by Jey-Cee** [comment]
I dont know. Isn't it installed by default?

**Comment by Garfonso** [comment]
No, it isn't. But it is required to control the frontend. 

Just checked... I thought that I would only create the necessary states, if browser_mod is installed. But it seems I broke that and the root objects in instances are always created. If browser_mod is correctly installed, a new sub folder (device) for each instance will be created, too. 

Probably it would be a good idea to install it by default... not sure how to do that, though. Hm.

**Comment by Jey-Cee** [comment]
Is it now installed by default?

**Comment by Garfonso** [comment]
browser_mod is installed by default since version 3.0.0.
