### ISSUE TITLE
Kartenkonfiguration - Entität im Dropdown nicht auswählbar / Liste nicht scrollbar - Chrome / Edge

### ISSUE THREAD

**Issue by K2ij3** [ioBroker/ioBroker.lovelace#384]
**Describe the bug**  
Browser: Chrome & Edge
Bei der Konfiguration einer neuen Karte sind die Entitäten im Dropdown-Menü nicht auswählbar.
Im Dropdown Menü ist ein scrollen und auswählen nicht möglich
Nur mittels der Cursor Tasten kann einen Entität ausgewählt werden

**To Reproduce**  
1. Lovelace in Chrome oder Edge öffnen
2. "Benutzeroberfläche konfigurieren"
3. "Karte Hinzufügen"
4. Beliebige Karte auswählen
5. Unter Entität auf den kleinen Pfeil nach unten klicken
6. Liste ist nicht scrollbar / Entitäten sind nicht anklickbar

**Expected behavior**  
Liste scrollbar / Entitäten anklickbar (in FireFox i.O.)

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/62553223/189619849-b0b89159-0d5a-4b67-8553-57eb8aefdd09.png)

**Versions:**  
 - Adapter version: 2.2.0
 - JS-Controller version: 4.0.23
 - Node version: 16.16.0
 - Operating system: Linux Debian Buster

**Comment by wuliwux** [comment]
hallo,

leider das selbe. gibt es hierfür eine Lösung?

lg

**Comment by Garfonso** [comment]
Das ist vermutlich ein Bug im HomeAssistant framework. Ich arbeite daran die neueste Version zu integrieren. Wer mutig ist, kann schonmal versuchen den adapter von Github zu installieren (kann aber bei theme & custom cards updates erfordern) und gucken, ob es da besser geht.

**Comment by wuliwux** [comment]
ja super, klappt mit der github version!
wann kommt die neue ins "normale" repo?

lg
