### ISSUE TITLE
State mapping in standard cards

### ISSUE THREAD

**Issue by pafade89** [ioBroker/ioBroker.lovelace#386]
**Is your feature request related to a problem? Please describe.**
Its not a related problem but it makes thinks more easy.

**Describe the solution you'd like**
Map states in JAML like for example in the [custom banner-card](https://github.com/nervetattoo/banner-card)

**Comment by Garfonso** [comment]
What?

What means "map states"? What are "states"? And what exactly is custom banner card doing?

**Comment by pafade89** [comment]
Ok Thx
