### ISSUE TITLE
Theme YAML is barely visible when using the dark theme

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.lovelace#398]
**Describe the bug**  
The adapter's Theme settings (YAML section) are barely visible when ioBroker is used with dark mode.

**To Reproduce**  
1. Enable dark for ioBroker theme

**Expected behavior**  
Text should be visible

**Screenshots & Logfiles**  
<img width="280" alt="2022-11-01_19-45-18" src="https://user-images.githubusercontent.com/16245/199313570-5060fef9-c96f-4f0f-8ec7-1961fcd8627f.png">

I typed `hello`.

**Versions:**  
 - Adapter version: 3.0.0

**Comment by agross** [comment]
Unstale

**Comment by agross** [comment]
Closing this because version 4.1.10 has good contrast.

**Comment by Garfonso** [comment]
Huh? I didn't change anything, to be honest. :-)

**Comment by agross** [comment]
Perhaps iobroker.admin provides the styles and they've been fixed? I don't know either, but it's looking good.

<img width="296" alt="2024-06-17_20-31-10" src="https://github.com/ioBroker/ioBroker.lovelace/assets/16245/fb5a8cc7-1ff1-4745-a855-d518a2fb779f">
