### ISSUE TITLE
"Reload of entities" nach Ändern eines DP Typs

### ISSUE THREAD

**Issue by holger05** [ioBroker/ioBroker.lovelace#4]
Nach dem Ändern eines Datenpunkt Typs in der Objektstuktur, muss die Liste der Entities neu eingelesen werden.
Auch taucht die neue "Entity" erst nach dem "Reload" des GUI-Editors in den Listen dort auf.

**Comment by GermanBluefox** [comment]
So ist das. Und wird nicht geändert. Sonst würde "Reload button" gar nicht da sein.
Lovelace hat aktuell keine Möglichkeit.

**Comment by GermanBluefox** [comment]
Dadurch, dass lovelace subscribed sich auf ALLE Objekte, ist es aus Performance Gründen nicht möglich.
