### ISSUE TITLE
ERR_CONNECTION_REFUSED after update to version 3.0.1

### ISSUE THREAD

**Issue by AxelRHD** [ioBroker/ioBroker.lovelace#408]
**Describe the bug**  
I can't reach the UI after updating. Server was restarted afterwards, but that didn't help either. Tried the IP adress without luck.

**To Reproduce**  
Updated to version 3.0.1

**Expected behavior**  
Finding a usable UI...

**Screenshots & Logfiles**  
Instance is running: 
![image](https://user-images.githubusercontent.com/16512322/206780777-e5f1237a-60b3-49c0-b846-db2f6987b5b6.png)

Port is exposed and reachable: 
![image](https://user-images.githubusercontent.com/16512322/206780904-c7cb67b3-4561-43d3-ac5b-8683a75b398e.png)

**Versions:**  
 - Adapter version: 3.0.1
 - JS-Controller version: 4.0.23
 - Node version: <node-version> v16.18.0
 - Operating system: DietPi

**Comment by Garfonso** [comment]
Please, after a major update (i.e. Version 2.x to 3.x) clear the browser cache. This might already solve your issue.

**Comment by AxelRHD** [comment]
Clearing the cache didn't have an effect. I switched from IPv4 to IPv6. Now the page is reachable again.
