### ISSUE TITLE
Wetter Widget ohne Symbole (nur Text)

### ISSUE THREAD

**Issue by WW1983** [ioBroker/ioBroker.lovelace#41]
Hallo zusammen

Das Wetter Widght zeigt bei mir keine Symbole sondern nur Text an. Installierte Lovelace Version 0.2.0

**Comment by klotzma** [comment]
Kann ich bestätigen, zeigt bei mir ebenfalls keine Symbole an!
![wetterl](https://user-images.githubusercontent.com/45261052/71311960-f15cc480-2425-11ea-8acc-27803a2b46f2.png)

**Comment by Pendora2017** [comment]
Ist bei mir leider auch so:
![Unbenannt](https://user-images.githubusercontent.com/28994273/72434547-2f86a300-379c-11ea-8e79-0a820142fbfe.JPG)

Original Wetter Widget von lovelace verwendet.
lovelace Version: 1.0.8 / ioBroker

**Comment by eric1905** [comment]
Kann ich bei mir auch bestätigen

![image](https://user-images.githubusercontent.com/4967207/73547816-fdce3700-443f-11ea-8c3e-c695185f5f11.png)

**Comment by eric1905** [comment]
Laut Kommentaren in : https://www.smarthome-tricks.de/software-iobroker/iobroker-visualisierung-mit-lovelace-teil-7-das-wetter-widget/ 
tritt es zwischen 0.1.5 und 0.2.1 auf

**Comment by fullcavediver** [comment]
Das Problem ist immer noch nicht behoben. https://www.smarthome-tricks.de/software-iobroker/iobroker-visualisierung-mit-lovelace-teil-7-das-wetter-widget/#comment-2057
Mittlerweile habe ich Version 1.0.9 im Einsatz

**Comment by mijado** [comment]
Auch in 1.1.12 ist der Fehler noch vorhanden.

**Comment by Marmi86** [comment]
Gin es dazu schon ein Fix?

**Comment by Garfonso** [comment]
Bisher nicht. Habe mich mit Wetter noch nicht näher beschäftigt.
Adapter ist "daswetter", ja?
Welche Objekte wurden denn mit raum/funktion versehen? Und wie sieht das Wetter-Gerät im Geräte-Adapter aus?

**Comment by Garfonso** [comment]
Es würde mir helfen, wenn jemand die Infos aus den Kommentaren bei Smarthome-Tricks hier kurz zusammenfasst.

**Comment by Marmi86** [comment]
> Bisher nicht. Habe mich mit Wetter noch nicht näher beschäftigt.
> Adapter ist "daswetter", ja?
> Welche Objekte wurden denn mit raum/funktion versehen? Und wie sieht das Wetter-Gerät im Geräte-Adapter aus?

Genau habe es mit yr und Das Wetter versucht wie ihn Smarthome Tricks HP beschrieben, bis auf die Logos wird alles angezeigt
Neuste Adapter für Wetter und lovelace sind  installiert

**Comment by Garfonso** [comment]
Puh... das gibt keinen einfachen fix... keine Ahnung, wie wir das am besten angehen.
Das Problem ist hier, dass anscheinend HomeAssistant/lovelace die Behandlung der Wettervorsage völlig verändert hat. Dort wird nun eine Zeichenkette für die Beschreibung des Wetters erwartet, siehe hier: https://developers.home-assistant.io/docs/core/entity/weather

Dieser wird dann von lovelace selber in icon usw. umgewandelt. Daher steht dort nur der Pfad des icons, was lovelace als Wetterbeschreibung versucht zu interpretieren, was aber nicht klappt -> daher gibt es keine Bilder...

Das Problem: Eine vergleichbare Wetterbeschreibung, wie sie lovelace da erwaret, sehe ich aktuell von "daswetter" nicht (und auch nicht unbedingt von anderen Wetter adaptern? *grübel*).

**Comment by klotzma** [comment]
In einer alten Version hat es ja die Bilder angezeigt.

**Comment by WW1983** [comment]
Es gibt ja eine funktionierende Wetter-Card von Accuweather. Allerdings wurden da wohl Anpassungen beim Typ-Detector vorgenommen. Kann man daraus nichts ableiten?

**Comment by Garfonso** [comment]
> In einer alten Version hat es ja die Icons angezeigt.

Ja, die lovelace Version halt auch aktualisiert. Heute geht es so nicht mehr mit der Karte.



> Es gibt ja eine funktionierende Wetter-Card von Accuweather. Allerdings wurden da wohl Anpassungen beim Typ-Detector vorgenommen. Kann man daraus nichts ableiten?

Daraus könnte man ableiten eine eigene Karte für den IoBroker für Wetter zu machen. Dazu bin ich aber leider nicht in der Lage (UI ist nicht mein Ding). Ansonsten ist der Weg, den der AccuWeather Adapter gegangen ist ziemlich ungünstig, der hieße, dass man für jeden Adapter einen eigenen Typ und eine eigene Karte bräuchte, was kann nicht das Ziel sein.

Es könnte noch einem anderen Weg geben. Man kann im Theme eigene Bilder definieren. Vielleicht kann ich damit was hacken. Habe mich allerdings mit den Themes bisher nicht auseinander gesetzt.

**Comment by nowi967** [comment]
Also man könnte mit dieser Card probieren: https://github.com/bramkragten/weather-card/
Man kann lokale Icons bei der Card hinterlegen und dort ließen sich bis jetzt WU, OW und daswetter einbinden.
Leider werden dort auch keine Symbole angezeigt aber vllt. bekommt das ja jemand damit gefixed.

**Comment by Garfonso** [comment]
Die Symbole lassen sich durch CSS Variablen bei der anderen Karte auch anpassen.

Ich habe jetzt rausgefunden, warum es nicht mehr geht. Es gabe eine Änderung im Lovelace Fork von Bluefox, die einfach das Icon darstellt und den "state" quasi ignoriert. Die ist aber bei einem update von Lovelace unter den Tisch gefallen. 

Ich versuche gerade Lovelace noch einmal zu aktualisieren und das da wieder einzubauen. Man sollte aber ggf. versuchen den AccuWeather-Weg etwas zu generalisieren und für andere Adapter auch nutzbar zu machen. Ich habe ein paar Ideen dazu, aber noch nicht so richtig etwas abschließendes (vermutlich ist der beste Weg irgendwo eine Übersetzung von den icons auf die lovelace-states zu machen, dann ist z.B. auch die History hübsch usw und die manuelle Änderung nicht mehr wichtig?).

**Comment by Garfonso** [comment]
![Lovelace_Wetter_Progress](https://user-images.githubusercontent.com/620860/85339772-1ae5ce00-b4e5-11ea-8078-e538d03fe0c5.JPG)

Langsame Fortschritte... *seufz* (Ich mag UI Arbeit und Javascript kompilieren nicht so gerne... ;-) ). Egal. Also neueste Version von Lovelace (20.06.2020) hab ich fast am laufen, hab schonmal das Icon-Display für "unser" Wetter-Entity wieder reingehackt (Problem war: die ganze Karte ist komplett anders configuriert -> daher ist die Änderung damals übersehen worden). 
Frage wäre, was da hin sollte wo jetzt "Nicht verfügbar" steht (da stand sonst der Icon-Pfad. In der Lovelace-Welt steht da eine Ein-Wortbeschreibung für das Wetter, die wir aber nicht haben... bin gerade etwas ratlos).

Was auch noch nicht geht (aber das ist ein anderes Problem, nur weil ich gerade jemand mein Herz ausschütten will), sind custom-cards. Die werden in der neuen Version alle nicht gefunden. K.a. was ich da falsch gemacht habe.

**Comment by WW1983** [comment]
@Garfonso 
Tolle Arbeit! Und nicht nur auf die Wetter-Card. Ingesamt mit Lovelace

Ich glaube bei "nicht verfügbar" Stand ursprünglich der Ort. Was sinnvolleres fällt mir auch nicht.

**Comment by Garfonso** [comment]
fixed in #94
