### ISSUE TITLE
Sensor card overlapps border

### ISSUE THREAD

**Issue by pafade89** [ioBroker/ioBroker.lovelace#410]
**Describe the bug**  
See title =)

**Expected behavior**  
Don´t overlapp. 

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/113902279/207981085-6ea17313-a4e5-4628-8fbf-80d34c776fdc.png)

**Versions:**  
 - Adapter version: 3.0.1
 - JS-Controller version: 4.0.23
 - Node version: 16.18.1
 - Operating system: Debian

**Comment by pafade89** [comment]
Can this be fixed in the adapter or does it have to be fixed in the next lovelace update?

**Comment by Garfonso** [comment]
This probably needs to be fixed with a lovelace update. 

On the other hand, I don't really see this issue over here, but I also do not have rounded corners. So probably that is why. 

I'll try to get a lovelace update ready before the summer vacations.

**Comment by pafade89** [comment]
Thank you very much.
