### ISSUE TITLE
Enitity - input_select funktioniert nicht

### ISSUE THREAD

**Issue by WW1983** [ioBroker/ioBroker.lovelace#42]
Hallo zusammen,

die manuelle Zuordnung als "input_select" funktioniert nicht. Ich erhalte eine Fehlermeldung bei der Auswahl in der UI

**Comment by algar42** [comment]
input_select should work Ok in upcoming version 0.2.5. from here https://github.com/algar42/ioBroker.lovelace

**Comment by WW1983** [comment]
thank you @algar42
