### ISSUE TITLE
Question: Lovelace support in devices like in the Homematic adapter

### ISSUE THREAD

**Issue by schmupu** [ioBroker/ioBroker.lovelace#43]
The Lovelace adapter finds all information (entity) for the homematic adapter by it self and the user has not add the entity by it self under objects. 
What do I have to do to provide this options in my adapters too? I would like to add this features in the shelly and lupusec adapter.

<img width="1058" alt="Bildschirmfoto 2019-10-15 um 20 52 01" src="https://user-images.githubusercontent.com/38919572/66860744-0896b600-ef8e-11e9-9c5d-931d4b0de9cc.png">

**Comment by Garfonso** [comment]
You still need help with that? Have a look at iobroker.type-detector ( https://github.com/ioBroker/ioBroker.type-detector ). That is how devices are detected and entities with advanced attributes are created.
Basically roles and types must be correct.
