### ISSUE TITLE
Missing data in history graph

### ISSUE THREAD

**Issue by volkerrichert** [ioBroker/ioBroker.lovelace#431]
**Describe the bug**  
I track my solar production and want to display the result in am graph. But only parts of data is shown.

**To Reproduce**  
1. add a graph (e.g. mini graph)
2. select a range with more than 2000 datapoints

**Expected behavior**  
All data should be returned

**Screenshots & Logfiles**  
the first request will only returns 2001 data points
![image](https://user-images.githubusercontent.com/640914/226642216-39584b7f-4bc1-4cf6-8926-3d25dd659e99.png)
as you can see a lot of data is missing between 2000 & 2001.

This will result in a graph like so
![image](https://user-images.githubusercontent.com/640914/226642550-2f37b1e0-f4b9-4566-8c50-311d7d0dfa27.png)

But there are many more data available. If i reduce the time interval to 3h all data (approx. 1800 entries) will be shown
![image](https://user-images.githubusercontent.com/640914/226643090-9f14cda0-e8a5-462a-a341-22b26d1d35ac.png)

**Comment by Garfonso** [comment]
There is a setting in the instance settings that restricts the number of retrieved data points from history and IIRC the default is set to 2000. Please check that setting.

**Comment by volkerrichert** [comment]
OMG.... THX.
