### ISSUE TITLE
Übersetzung falsch

### ISSUE THREAD

**Issue by Eistee82** [ioBroker/ioBroker.lovelace#444]
https://github.com/ioBroker/ioBroker.lovelace/blob/186a3335b0acb2b57512fa9a0bc0d3438f616e81/admin/i18n/de/translations.json#L48

**Comment by Garfonso** [comment]
Und warum ist das falsch?
Wo taucht die Übersetzung denn auf?

Soweit ich das sehe, sollte die Übersetzung für einen binären Helligkeitssensor (also nur mit den Zuständen "Hell" und "Dunkel" bzw. "true" "false") genutzt werden. Bei einem kurzen Test funktioniert das auch alles, wie gedacht.

**Comment by Eistee82** [comment]
In anderen Adaptern ist Light aber Licht bzw. Lampe. Und dort taucht dann statt Licht immer Hell/Dunkel auf was total verwirrend ist. Light sollte mit Licht übersetzt werden.

**Comment by Garfonso** [comment]
Dafür kann Lovelace ja nichts. Und Lovelace selber nutzt "light" und übersetzt das mit "Licht". 

Das ist also ein admin Problem. Guck mal, ob es da schon ein issue gibt, sonst erstell dort eins.

**Comment by Eistee82** [comment]
Das ist kein Admin Problem sondern Light bedeutet nun mal im englischen nicht Hell/Dunkel sondern Licht. Es gibt im Admin nur eine Übersetzung für englisch. Die Adapter steuern lediglich Adapterspezifische Übersetzungen bei. aber das ändert nichts daran das es Übersetzungen sind und nicht irgendwelche Fantasietexte die irgendwem da an der Stelle besser gefallen.

**Comment by mcm1957** [comment]
Bevor ihr euch die Augen auskratzt - was ich nicht hoffe:
Lt. Langenscheidt bedeutet light sowohl Licht als auch Helligkeit.

![image](https://github.com/ioBroker/ioBroker.lovelace/assets/28575778/8088472c-7370-40e4-8c18-b7895fcd9368)

Und ja, Übersetzungen eines Adapters dürfen Übersetzungen eines anderen Adapters nicht ändern. 
Das muss allerdings Admin lösen.
