### ISSUE TITLE
Thermostat Card shows old values

### ISSUE THREAD

**Issue by nevermind2001** [ioBroker/ioBroker.lovelace#46]
If i open lovelace in the Browser (Windows/Android) or reload the Page, the Thermostat Card shows me old values (Temperature). After a while (1-2 min) or if i change the Temperature (pe. via CCU) the correct value is loaded. If i reload the page again the old value appears.

![1570709744972-lovelace3](https://user-images.githubusercontent.com/44928988/67271454-d66be380-f4ba-11e9-9461-3d9c68995c6e.gif)

Version 0.2.1 installed

**Comment by algar42** [comment]
for me thermostat card does not work at all:
for target temperature it always shows N/A and if I try to change the value it remains N/A and set the IoB state to null
![image](https://user-images.githubusercontent.com/40002726/67679468-328ea600-f99a-11e9-86d5-0a167887c4a3.png)

Also, on lovelace start Thermostat card shows Unknown value for temperature until it gets updated in IoB - i.e. lovelace does not read current state on start.

**Comment by algar42** [comment]
Issue seems to be fixed in v 0.2.5. 
Please test from here : https://github.com/algar42/ioBroker.lovelace.git

**Comment by JB1985** [comment]
I am using Version 1.0.5 but the thermostat card not work:

![image](https://user-images.githubusercontent.com/9932751/70213640-1cfb6180-173a-11ea-8c5b-1ae0b7a12c5f.png)

**Comment by nevermind2001** [comment]
> 
> 
> Issue seems to be fixed in v 0.2.5.
> Please test from here : https://github.com/algar42/ioBroker.lovelace.git

I´m now on 1.0.6 and still have the same Problem.

**Comment by nevermind2001** [comment]
I tested again: If i restart the Adapter it works again. After that i restarted ioBroker (rebooted the VM) and the Issue was back. Then restarting Adapter -> issue solved.

So every time i reboot the VM (for example to Backup the VM) the bug comes back until i restart the Adapter.

**Comment by nevermind2001** [comment]
Hmmm ... no. Maybe this not causing the Problem. I´m not sure why and when the Problem is resolved or not. For now i think the Problem was temporarily fixel when i restart the Adapter while lovelace ui is opend in the Browser ... :/

**Comment by algar42** [comment]
This issue is connected with #59. UI stops showing correct values if, say, you open it on another device.

**Comment by algar42** [comment]
This seems to be fixed in PR and https://github.com/algar42/ioBroker.lovelace

**Comment by agross** [comment]
Hi,

how did you get the Thermostat entities to show up in the first place? I'm running ioBroker connected to a CCU and I assigned funcHeating and a room to my wall thermostats. Still, the Lovelace instance does not detect it as an entity. The debug log shows nothing w.r.t. my thermostats.

Thanks,

Alex

**Comment by agross** [comment]
Alright, this was a firewall issue. The CCU was unable to report back to ioBroker.

**Comment by Garfonso** [comment]
> This seems to be fixed in PR and https://github.com/algar42/ioBroker.lovelace

After the merge, is this fixed for you @algar42 ?
How about @nevermind2001 and @JB1985?

**Comment by algar42** [comment]
@Garfonso Yes, the states update process seems to be working fine. For thermostats as well.

**Comment by JB1985** [comment]
@Garfonso for me it works too.

**Comment by Garfonso** [comment]
Thanks for the feedback.
