### ISSUE TITLE
State .blackout has no existing object

### ISSUE THREAD

**Issue by pafade89** [ioBroker/ioBroker.lovelace#461]
**Describe the bug**  
When you connect with a new browser then the following warning is written to the log:

`State "lovelace.0.instances.1a271a40-333c3657.blackout" has no existing object, this might lead to an error in future versions
`

**To Reproduce**  
1. Open Lovelace with new browser
2. Error occurs

**Screenshots & Logfiles**  

![image](https://github.com/ioBroker/ioBroker.lovelace/assets/113902279/1190c045-136b-4f3b-bf80-7c4cb2cfa1aa)

**Versions:**  
 - Adapter version: 3.0.1
 - JS-Controller version: 4.0.24
 - Node version: 18.16.0
 - Operating system: debian
 
Thanks for your help

Cheers P

**Comment by Garfonso** [comment]
Thanks for reporting the error. 

I recognized it and already [fixed it](https://github.com/ioBroker/ioBroker.lovelace/commit/5dfa0be15b7fade6aa84a598a2d950103b0f337b). It will be gone in a future version of the adapter.
