### ISSUE TITLE
No Raw editor

### ISSUE THREAD

**Issue by stonemaan** [ioBroker/ioBroker.lovelace#463]
**Describe the bug**  
Hi all,

seit kurzem ist bei mir kein Code Editor mehr verfügbar. 

<img width="623" alt="Ohne Titel" src="https://github.com/ioBroker/ioBroker.lovelace/assets/73359164/7d73de15-65ca-439c-8b94-fab1c1792236">

auch über den Raw-Konfigurationseditor kann ich nichts ändern oder sehen. 

Jemand eine Idee wie ich den wieder finden kann? 

Danke euch.

 - Adapter version: 2.2.0
 - JS-Controller version: 4.0.24
 - Node version: 16.20.1
 - Operating system: Mac OS x 13.5

**Comment by Garfonso** [comment]
Hm. Adapter Version 2.2.0? Aktuelle stable ist 3.0.1. Bitte mach mal ein Update... vermutlich ist das Frontend für die verwendeten Browser mittlerweile einfach zu alt.

Guck mal, ob da Fehler in der Browser-Konsole sind.

**Comment by stonemaan** [comment]
Hi, oh sorry, ich hatte mich vertippt. ich hab die 3.0.1 installiert. im Browser steht nur folgendes: 

<img width="1918" alt="Bildschirmfoto 2023-08-24 um 15 32 02" src="https://github.com/ioBroker/ioBroker.lovelace/assets/73359164/c99ce710-eeae-4cf7-b175-3c4f808b8883">

Ist meines Erachtens auch erst mit dem Update auf die 3.0.x aufgetreten.. Logeinträge im Job hab ich keine nennenswerten vom Lovelace im iOb.

Das alles im Safari 16.6..

**Comment by stonemaan** [comment]
Okay, konnte das Problem etwas eingrenzen. Betrifft aktuell nur Safari 16.6 auf Mac OS X 13.5 .. auf dem iPhone ist der Editor problemlos aufrufbar, auch über Chrome auf MacOS X 13.5.. Auf den alternativen Browser bin ich nicht gekommen.. Danke für den Tipp!

**Comment by Garfonso** [comment]
Ich bereite ein Release mit neuem Frontend vor. Wenn du möchtest, wäre es hilfreich, wenn du mal die github Version ausprobierst, ob es da geht.

**Comment by stonemaan** [comment]
mach ich gerne! habe die Benachrichtigungen dazu aktiviert..

**Comment by stonemaan** [comment]
Funktioniert wieder 🤷🏻‍♂️
