### ISSUE TITLE
Benachrichtigungen ohne Funktion

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.lovelace#477]
**Describe the bug**  
Mit der aktuellen GitHub Version werden keinerlei Benachrichtigungen zur Anzeige gebracht. Im Datenpunkt "lovelace.0.notifications.list" werden jedoch die Benachrichtigungen gesammelt.

**To Reproduce**  
1. Lovelace GitHub Version installieren.
2. Benachrichtigung auslösen.
3. Es werden keine zur Anzeige gebracht.
4. Prüfe den Datenpunkt "lovelace.0.notifications.list". Dieser sollte nicht leer sein.

**Expected behavior**  
Es sollten die Benachrichtigungen zur Anzeige gebracht werden.

**Screenshots & Logfiles**  
Sind nicht nötig (denke ich).

**Versions:**  
 - Adapter version: GitHub Version
 - JS-Controller version: v7.1.6
 - Node version: v18.18.2
 - Operating system: Docker Container v9.0.1

**Additional context**  
Wenn die letzte Stable Version installiert wird, werden nach dem starten die gesammelten Benachrichtigungen angezeigt.

**Comment by Garfonso** [comment]
Danke für den Hinweis. 

Mit der jetzt aktuellen Github Version sollte es wieder gehen (aber das Frontend ist wieder aktualisiert worden ;-)  und die Shoppinglist ist weg / umgebaut ... mal sehen).

**Comment by dontobi** [comment]
Ich teste es im Laufe der Woche

**Comment by Garfonso** [comment]
sollte in Version 4.0.x gefixt sein. Falls nicht, bitte nochmal melden.
