### ISSUE TITLE
History Graph Karte kein Zustandsverlauf mehr

### ISSUE THREAD

**Issue by Track4123** [ioBroker/ioBroker.lovelace#480]
Hi.  Ab Version 4.0.0 (bis zur aktuellen) werden in der History Graph Karte keine Zustandsverläufe mehr angezeigt.
Wenn ich zurück gehe auf 3.0.1 ist alles wieder wie gehabt.

![image](https://github.com/ioBroker/ioBroker.lovelace/assets/144127021/176f65f4-dd30-4856-b824-71f22a43fb61)

**Comment by DiveSurfer** [comment]
Kann ich nur bestätigen, auch der history-graph ist leer
Plattform: linux
Betriebssystem: linux
Architektur: arm64
Node.js: v18.17.1
NPM: 9.6.7
Js-controller: 5.0.16

**Comment by gui2180** [comment]
Bei mir auch
Plattform: linux
js-controller: 5.0.17
Node.js: v18.19.0
NPM: 10.2.3

**Comment by Garfonso** [comment]
sollte in 4.0.7 gefixt sein.

**Comment by Track4123** [comment]
Hi, hat funktioniert! Muss dann leider sagen das jetzt Farbgebung nicht ganz glücklich ist für an / aus Status...
War vorher grün / rot, jetzt wie unten, leider schlecht erkennbar,

![image](https://github.com/ioBroker/ioBroker.lovelace/assets/144127021/2f7b9386-1ad7-474a-ac9c-849813e14e77)

Vielleicht kann man das noch tunen?

**Comment by Garfonso** [comment]
Über das Theme, vermutlich. Das ist out of scope für den Adapter. Dazu mal in der HomeAssistant Welt suchen, wie die das sehen.
