### ISSUE TITLE
Notifications: uncaught exception when using sendTo()

### ISSUE THREAD

**Issue by marcprenger** [ioBroker/ioBroker.lovelace#501]
Hi,

I upgraded to the latest and greatest version and I'm now experiencing an issue when trying to add notications:

![image](https://github.com/ioBroker/ioBroker.lovelace/assets/27813142/1ea8ebea-9183-4280-a93f-0a857caaef40)

This exception is being thrown as soon as I issue the following command:
sendTo('lovelace.0', 'send', {message: 'Message text', title: 'Title'}); // full version

When I use the alternative instead, it works without that issue:
setState('lovelace.0.notifications.add', '{"message": "Message text", "title": "Title"}'); // full version

Please let me know if you need more information. 

Best,
Marc

**Comment by Garfonso** [comment]
Ooops... I didn't even know there was a message handling for that. :-/
Of course, I have to adjust that, too. Thanks for reporting the issue.
