### ISSUE TITLE
How to update hass_frontend

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.lovelace#52]
Following the instructions given here (https://github.com/ioBroker/ioBroker.lovelace#how-to-build-the-new-lovelace-version) works compiling, but when replacing the `hass_frontend` folder within iobroker.lovelace, the frontend requires an authentication / login.

Could you explain which changes you have applied to the original `home-assistant-polymer`?

**Comment by algar42** [comment]
yes, I tried and got the same result.... did not find solution

**Comment by Zefau** [comment]
Thanks for the feedback. Good to know I'm not the only one.

@GermanBluefox Sorry, for pinging. Could you help on this? The current version is some commits behind and we would like to keep it up-to-date. Thanks!

**Comment by GermanBluefox** [comment]
Nice, that someone wants to help. 

It is required to merge master against https://github.com/GermanBluefox/home-assistant-polymer

Hass changed first authenticaton, then notifications and I must revert these changes by every merge

**Comment by algar42** [comment]
could you please update instruction in readme? it would be really helpfull.

**Comment by Zefau** [comment]
@GermanBluefox https://github.com/GermanBluefox/home-assistant-polymer is outdated though compared to its origin. 

Our objective is to update to the current official release. 

An detailed instruction of your changes would be very helpful. Thanks in advanced!
Alternatively an automation of your repository to rebase to the origin would also be working.

**Comment by GermanBluefox** [comment]
I updated the docu: https://github.com/ioBroker/ioBroker.lovelace#how-to-build-the-new-lovelace-version
