### ISSUE TITLE
Uhrzeit und RGB Slider

### ISSUE THREAD

**Issue by ali86x** [ioBroker/ioBroker.lovelace#521]
Vielleicht gibt es die Möglichkeit schon und ich bin einfach blind.
Gibt es die Möglichkeit, eine einfache digitale Uhr anzuzeigen?
Finde da keinen Weg zu. 

Außerdem wäre es cool, wenn man bei Lampen per Slider die Farbe ändern könnte (ähnlich wie Helligkeit etc).
Aber auch da blicke ich nicht durch.

**Comment by Garfonso** [comment]
siehe forum. 

Oder auch hier: https://github.com/ioBroker/ioBroker.lovelace/blob/master/docs/de/automatic_entities.md
