### ISSUE TITLE
Aktuelle SSL-Zertifikate werden nicht mehr gezogen

### ISSUE THREAD

**Issue by BOfH85** [ioBroker/ioBroker.lovelace#529]
**Describe the bug**  
Es ist ein gültiges SSL-Zertifikat im iobroker hinterlegt. Der Admin-Adapter erkennt es auch tadellos. Lovelace jedoch nicht. Let's Encrypt funktioniet ja schon länger nicht mehr, weil lovelace immer noch die alten Optionen in der GUI anbietet (aber im Hintergrund offenbar keine Aktionen mehr dahinter liegen). 
Bisher konnte ich es so lösen, dass ich dem lovelace Adapter dann einfach das genaue Zertifikat mitgeteilt habe. Jetzt ignoriert er auch das und springt zwangsweise auf das letzte Let's Encryp Zertifikat, das noch mit der alten Methode erstellt wurde - was irgendwann 2023 war und darum heißt es jetzt natürlich, das Zertifikat wäre ungültig, weil längst abgelaufen. 

Heißt, lovelace zieht sich nicht das aktuelle Zertifikat, trotz angegeben, sondern zieht sich das letzte, welches von der alten Let's Encrypt Methode erstellt wurde, die aber ja mittlerweile auch nicht mehr funktioniert, weshalb auch dieses alte Zertifikat nicht erneuert werden kann. 

**Expected behavior**  
Lovelace sollte wieder wie bisher auch die Adapater-Einstellungen korrekt übernehmen und das Zertifikat verwenden, was man ihm angibt.

**Screenshots & Logfiles**  
![image](https://github.com/ioBroker/ioBroker.lovelace/assets/2980638/3ba8b98a-969a-4dba-a5c1-ccc68f33b31b)
![image](https://github.com/ioBroker/ioBroker.lovelace/assets/2980638/aa3aeb5c-7edc-49b2-99af-9e78bf1d5512)
![image](https://github.com/ioBroker/ioBroker.lovelace/assets/2980638/46ddd91c-cb27-40ab-ab61-691c37d722e0)

**Versions:**  
JS-Controller: 5.0.19
Admin-Adapter: 6.13.16
Lovelace-Version: 4.1.8

**Comment by Garfonso** [comment]
Kann ich nicht reproduzieren. Manuell Zertifikate einstellen geht bei mir ohne Probleme. Die müssen natürlich richtig sein, also im Admin richtig konfiguriert.

Let's Encrypt sollte seit Februar auch wieder gehen, wenn du den ACME Adapter installierst, der sich darum kümmert, die aktuell zu halten. Ob da die Let's Encrypt Optionen noch sinnvoll sind, oder nicht, weiß ich nicht. Vermutlich nicht. Hast du den ACME Adapter?

**Comment by BOfH85** [comment]
Das manuelle Zertifikat IST richtig, für den Admin-Adapter nutz ich es ja auch und da öffnet sich die Weboberfläche mit dem AdminPort korrekt mit dem aktuellen Zertifikat, also dem, welches ich manuell im iobroker hinterlegt hab. Selbes Zertifikat (Siehe Screenshots) ist im lovelace-adapter eingestellt. Aber da zieht es sich nur ein uraltes. abgelaufenes. 

Wenn ich auf let's encrypt umstelle passiert: Gar nichts. Auch da zieht er einfach wieder nur das alte, abgelaufene Zertifikat. Und allein das ist ja der Fehler, das manuell hinterlegte sollte eigentlich immer gezogen werden, wenn ausgewählt.

**Comment by BOfH85** [comment]
Abgesehen davon will ich ja gar nicht auf das interne Lets's Encrypt umstellen, das hab ich aus und will es auch aus haben. Ich möchte einfach dass Lovelace wie jeder andere Adapter das Zertifikat verwendet, welches ich ihm angebe. Wenn ich mir ein 1-Jahres-Zertifikat kaufe das für alle meine Geräte im Netz auf der selben Domain gilt, dann möchte ich nicht nur für lovelace einen Workaround basteln müssen.

Es nimmt sogar das uralte, abgelaufene Let's Encrypt-Zertifikat wenn ich im iobroker eindeutig unabhängige RapidSSL-Zertifikatdaten hinterlege. Und wie gesagt: Der Admin-Adapter frisst diese Daten problemlos. Gebe ich das exakt gleiche Zertifikat im Lovelace-Adapter an, ignoriert er das eisenhart. Übrigens auch nach kompletter Deinstallation und Neuinstallation des Adapters.

**Comment by Garfonso** [comment]
Wie gesagt, kann ich hier nicht reproduzieren. Wenn ich dem lovelace adapter die Zertifikate, die ich im admin hinterlegt habe, gebe, dann geht es ohne Probleme und er nimmt auch die richtigen Zertifikate.

Ohne dass ich das hier reproduzieren kann, weiß ich gerade nicht, wie ich das reparieren kann. Mit dem ganzen SSL Kram kenne ich mich ehrlich gesagt auch nicht aus. Vielleicht muss da mal @GermanBluefox oder jemand drüber gucken.

**Comment by BOfH85** [comment]
Jetzt klappts plötzlich wieder. Alles was ich jetzt geändert hab war, dass ich den Adapter vorher komplett gestoppt hatte, dann das Zertifikat umgestellt und ihn dann wieder gestartet. Naja, solang er es wieder tut ist ja alles gut :-)
