### ISSUE TITLE
Zigbee device icons cannot be loaded in authenticated setup (>= 4.1.9)

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.lovelace#531]
**Describe the bug**  

I have 2 instances of the adapter installed on a single ioBroker installation. One instance is for guests, accessible only from inside my network. Another one is the authenticated instance for me.

With anonymous access allowed:

```sh
$ curl  https://gast.ogd.therightstuff.de/adapter/zigbee/img/philips_hue_lst002.png
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
```

The authenticated site:

```sh
$ curl  https://lovelace.ogd.therightstuff.de/adapter/zigbee/img/philips_hue_lst002.png
File img/philips_hue_lst002.png not found: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
```

This line is logged (with level `debug`):

```
Trying to send file img/philips_hue_lst002.png for zigbee.admin
```

**The same setup works in 4.1.8. I suspect 34c2f9e5eca2370fc70f9bebe99b5a87cdc67a3d is the issue. I think the root cause might be that these images are requested by the browser without supplying an authentication token.**

**Versions:**  
 - Adapter version: 4.1.9
 - JS-Controller version: latest
 - Node version: 18
 - Operating system: docker

**Comment by Garfonso** [comment]
Hrgn... ok... stupid oversight. ;-)
Could you check the latest git version? (i.e. https://github.com/ioBroker/ioBroker.lovelace/commit/8c65dea9666e0ec7a85fd6cc3c45e8cd1ed4f50d )

**Comment by agross** [comment]
Yep, that commit started working again.

**Comment by agross** [comment]
Closing this because https://github.com/ioBroker/ioBroker.lovelace/commit/8c65dea9666e0ec7a85fd6cc3c45e8cd1ed4f50d contains the appropriate fix. Thank you!
