### ISSUE TITLE
Eingabefeld-Zahl wandelt Wert in String um

### ISSUE THREAD

**Issue by Timmssss** [ioBroker/ioBroker.lovelace#545]
Ich habe einen Datenpunkt, welchen ich als Entitätstyp 'Eingabe - Zahl' an Lovelace übergebe.

Vor der Änderung des Wertes in Lovelace mach ich einen Debug-Output, in dem mir der Typ vom Wert ausgegeben wird - Typ = number.

Nun verändere ich diesen Wert in Lovelace, aus einer 21 wird eine 22. Danach wieder der Debug-Output - Typ = String.

Wieso wird die Zahl in einen String konvertiert, in einem Input-Number Feld?

**Comment by Garfonso** [comment]
> Wieso wird die Zahl in einen String konvertiert, in einem Input-Number Feld?

Weil in der HASS Welt states ausschließlich string sind... :-(

Du meinst, wenn du in lovelace den Wert änderst, wird er in ioBroker als Zahl gespeichert (vermutlich mit entsprechender Warnung)? Falls ja, danke für den Report. Gucke ich mir an, soll so natürlich nicht.

**Comment by Timmssss** [comment]
> Du meinst, wenn du in lovelace den Wert änderst, wird er in ioBroker als Zahl gespeichert (vermutlich mit entsprechender Warnung)? Falls ja, danke für den Report. Gucke ich mir an, soll so natürlich nicht.

ich habe in ioBroker einen number-Datenpunkt mit Wert 21. Verändere ich diesen in Lovelace mit dem Eingabefeld-Zahl, wird dieser Wert in einen String umgewandelt ☹

Bist du in der Sache schon etwas weiter?

**Comment by Garfonso** [comment]
Sorry, hatte wenig Zeit für Lovelace. Nach den Herbstferien NRW hab ich mir vorgenommen da weiter rein zu gucken. :-)

**Comment by Garfonso** [comment]
So, ich hoffe, die tests laufen durch und der ganze Prozess. Dann sollte es in Version 4.1.11 gefixt sein. :-)
