### ISSUE TITLE
Manuelles Hinzufügen von Entities

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.lovelace#6]
Es wäre super, wenn man in den Instanz Einstellungen des Adapters auch manuell Entities eintragen könnte.

**Comment by dontobi** [comment]
Kann geschlossen werden. Man kann unter Objekte die Entities die man möchte aktivieren.

**Comment by jankokert** [comment]
Danke für das Ticket und die Lösung! Ich habe zuvor bestimmt 1h herumgerätselt, wie das funktioniert! 
Also: Reiter Objects, dann ganz rechts auf das Zahnrad (custom settings) und [x] bei Enable für lovelace
