### ISSUE TITLE
Node-RED Daten werden nicht mit Glance dargestellt

### ISSUE THREAD

**Issue by BastelKlaus** [ioBroker/ioBroker.lovelace#60]
Objekte aus Node-Red 
![](https://forum.iobroker.net/assets/uploads/files/1574959466878-f232ce88-3fdd-4e79-934f-8eea4f16ff5d-image.png)

Können in Sensor-Card dargestellt werden
![image](https://user-images.githubusercontent.com/58326321/69856901-fe571f80-128e-11ea-8f36-78a2bd256dff.png)

aber nicht in einer Glance-Card
![](https://forum.iobroker.net/assets/uploads/files/1574959247929-b4b197fd-8833-40d2-bba5-ae8ec5b0d1e5-image.png)

mit Zigbee ausgelesene Sensorwert alleine, funktionieren einwandfrei. (selbe wie Bild 3 nur ohne Node-Red Wert) 
![](https://forum.iobroker.net/assets/uploads/files/1574959150658-345b348b-6bb0-4fec-9e93-f7a3b20d4f4f-image.png)

**Comment by Apollon77** [comment]
Hi, sorry für die Blöde frage aber: Was sind "Glance Cards"? Warum tut es nicht? Was genau ist falsch/anders als erwartet? Kann es sein das dier Punkte im Namen irgendwie stören? Wenn ja dann ist das ein problem was eher bei der "glance card" gelöst werden muss in meinen AUgen oder Du musst die Werte mit anderen Namen bereitstellen

**Comment by algar42** [comment]
dots in entity names are prohibited. Change the name of the object.

**Comment by algar42** [comment]
btw, how did you create entity with dots in the name? In entity settings it automatically replace dots to dashes when you are typing the name..

**Comment by BastelKlaus** [comment]
thanks for the fast response

I did a Test, with no . in the Node-RED Topic.
![image](https://user-images.githubusercontent.com/58326321/69859390-5ba19f80-1294-11ea-8a1c-7ca3c3b97d41.png)

" how did you create entity with dots in the name?" --> i only select the Entität

Same result with or without DOT`s.

**Comment by algar42** [comment]
hmm... it looks like Glance card does not accept dash as well :)
Unfortunately there is nothing we can do for Iob adapter for this issue. It is the problem of original lovelace card. 
Please try without dash... it should work.

**Comment by BastelKlaus** [comment]
Without dots will not work for me. 
The `.` are generat by the Topic of Node-RED

![image](https://user-images.githubusercontent.com/58326321/69861494-c3f28000-1298-11ea-9d16-54c65a2f5038.png)

an gives the structure in my Objekts

![image](https://user-images.githubusercontent.com/58326321/69861635-0caa3900-1299-11ea-8b83-d2865511589d.png)

without all Objekts are paste in Node_RED Folder like this.

![image](https://user-images.githubusercontent.com/58326321/69862828-a246c800-129b-11ea-998f-c4de954d3320.png)


But i did the Test without `dash` and `dot` and it works.

![image](https://user-images.githubusercontent.com/58326321/69862093-ffda1500-1299-11ea-8b4a-d7be84f3d119.png)
 
I don´t understand why, because the lumi Sensors have `dash` inside.

**Comment by algar42** [comment]
For individual state you can override entity name here:
![image](https://user-images.githubusercontent.com/40002726/69863209-4be28500-12ad-11ea-90a5-f7cd025ebc66.png)

or you can change the common.name property of the state, e.g.:
![image](https://user-images.githubusercontent.com/40002726/69863324-8f3cf380-12ad-11ea-925d-2aea316c8c2a.png)

you don't need to change the ID of the state. Entity name is generated from its name. Preference is to common.name.en name.

**Comment by BastelKlaus** [comment]
Oh great it Works 

![image](https://user-images.githubusercontent.com/58326321/69864276-d96aa880-129e-11ea-9639-2b64a1a32c9a.png)

Ok for all with the same Problem, in the unique Name there could be `_` but no  `-`  

![image](https://user-images.githubusercontent.com/58326321/69864331-f30bf000-129e-11ea-98c6-3b1048cba451.png)

@algar42 you solved the Problem thank you!!!
