### ISSUE TITLE
Anmeldezeitlimit deaktivieren?

### ISSUE THREAD

**Issue by JB1985** [ioBroker/ioBroker.lovelace#61]
Hallo,

es gibt ja leider keine App für die lovelace UI. Ich will daher für mein Smartphone die lovelace URL als App starten, mit "Zum Home-Bildschirm" via iOS.

Ich habe unter den Adapterkonfiguration: lovelace.0 den Anmeldezeitlimit auf 0 gesetzt, scheint aber leider nicht zu funktionieren. Ich muss mich weiterhin alle paar Male anmelden.
Auch das Passwort Speichern unter Safari scheint nicht zu funktionieren.

Hat da jemand eine Lösung für?

**Comment by GermanBluefox** [comment]
You can use this one for Android: 
https://play.google.com/store/apps/details?id=io.homeassistant.companion.android

May be there are some iOS apps too.

**Comment by JB1985** [comment]
And how?

I add the URL of my Lovelace IU:

https://myurl:8091

I get the error:

Unbekannter Fehler: Der Vogang konnte nicht abgeschlossen werden. ObjectMapper failed to serialize response.

**Comment by GermanBluefox** [comment]
httpS ??
Do you have valid certificate?

**Comment by JB1985** [comment]
Yes. 

I am using iobroker mit Lovelace UI. Not the Homeassistent.

**Comment by GermanBluefox** [comment]
> Yes.
> 
> I am using iobroker mit Lovelace UI. Not the Homeassistent.

I understand that we are speaking about ioBroker+LovelaceUI. 
My question was about https connection. Because I could communicate with Android App in local network without SSL Certificate.

What the certificate do you have? Let'sEncrypt or something else?

**Comment by JB1985** [comment]
It is a digicert, not Letsencrypt.

And i am using the IOS Version from Homeassisstent App.

**Comment by JB1985** [comment]
Any other idea?
