### ISSUE TITLE
Darstellungsfehler bei Benachrichtigungen 

### ISSUE THREAD

**Issue by klotzma** [ioBroker/ioBroker.lovelace#62]
In der neusten Version ist ein Darstellungsfehler, über ein Smartphone sind die Benachrichtigungen nach rechts verschoben (siehe Bild).
Ich habe es auf verschiedenen Browsern überprüft und auch Browserdaten gelöscht, Problem immernoch vorhanden.

In der Version 0.2.3 war dieses Problem noch nicht.

![1574517665451-20191123_150023](https://user-images.githubusercontent.com/45261052/70391808-6f0de280-19d9-11ea-8862-eb272faf2890.jpg)

**Comment by robotastic-io** [comment]
Hi,

I can confirm the issue. It seems that the drawer width is set to a fixed 500px. Adding

`notification-drawer #contentContainer{
max-width: 100vw;
}`

to css solve this.

**Comment by klotzma** [comment]
Where do I have to enter the CSS in lovelace?

**Comment by klotzma** [comment]
Where can i add this in lovelace?
> `notification-drawer #contentContainer{ max-width: 100vw; }`

**Comment by robotastic-io** [comment]
My message was pointed towards the developers. Sorry for not making this more clear.

**Comment by Garfonso** [comment]
I think I fixed it. To test, please try my dev-branch. Install from admin, github->custom url: `Garfonso/iobroker.lovelace#dev`

(A lot of other stuff has changed, too. I'd be happy to get more feedback on that, maybe we can target for a new stable relase. Would be great).
