### ISSUE TITLE
Entity type: binary_sensor nicht verfügbar

### ISSUE THREAD

**Issue by fullcavediver** [ioBroker/ioBroker.lovelace#63]
Welchen Typ soll man für Bewegungsmelder wählen, wenn 'binary_sensor' nicht verfügbar ist?
Ich habe schon ziemlich alle ausprobiert, aber keiner passt hunderprozentig. Beim 'sensor', wie bei den Meisten, bekomme ich den Status 'true/false' und die Graphen (history und mini-graph-card) funktionieren nicht. 

![2019-12-09_092640](https://user-images.githubusercontent.com/49302111/70419953-dd4cb680-1a66-11ea-95b8-be0083aba152.png)
![2019-12-09_092653](https://user-images.githubusercontent.com/49302111/70419958-dfaf1080-1a66-11ea-9774-9893ea2cebb4.png)
![2019-12-09_092704](https://user-images.githubusercontent.com/49302111/70419962-e2116a80-1a66-11ea-89c5-b2d6490834e8.png)

Wenn ich 'input_boolean' wähle, dann sind die Graphen zwar richtig, aber ich kann mit dem Schalter den Zustand ändern, was nicht das Richtige ist.

![2019-12-09_092926](https://user-images.githubusercontent.com/49302111/70419978-ed649600-1a66-11ea-81cb-d8b06689a086.png)
![2019-12-09_092955](https://user-images.githubusercontent.com/49302111/70419986-f05f8680-1a66-11ea-875a-0b2bb965f693.png)
![2019-12-09_093010](https://user-images.githubusercontent.com/49302111/70419990-f2c1e080-1a66-11ea-87f5-ebcb158d1809.png)

Ideal wäre, den Typ 'binary_sensor' zu haben, den finde ich aber nicht in der Auswahl.

Danke im Voraus für die Hilfe!

**Comment by kurt4160** [comment]
Wäre auch für den Fenster/Tür Status notwendig.

Danke

**Comment by algar42** [comment]
binary_sensor added to list in PR #77

**Comment by fullcavediver** [comment]
It works perfect. Thank you!
