### ISSUE TITLE
Problem: "by controller[0]: TypeError: Cannot read property 'bind' of undefined"

### ISSUE THREAD

**Issue by b3ster** [ioBroker/ioBroker.lovelace#71]
Hi, I hope someone can help me here :) as I would like to give lovelace a change for as my ui 

My system is up to date, but if I want to start any instance it ends in the following loop, please let me know if I can provide any additional information.

Following error occurs:

host.Home-Server | 2020-01-28 11:21:55.510 | info | instance system.adapter.lovelace.0 started with pid 1657
-- | -- | -- | --
host.Home-Server | 2020-01-28 11:21:55.491 | info | object change system.adapter.lovelace.0
host.Home-Server | 2020-01-28 11:21:28.394 | info | Restart adapter system.adapter.lovelace.0 because enabled
host.Home-Server | 2020-01-28 11:21:28.394 | error | instance system.adapter.lovelace.0 terminated with code 6 (uncaught exception)
Caught | 2020-01-28 11:21:28.394 | error | by controller[0]: at Manager.ondata (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:322:16)
Caught | 2020-01-28 11:21:28.394 | error | by controller[0]: at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
Caught | 2020-01-28 11:21:28.394 | error | by controller[0]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
Caught | 2020-01-28 11:21:28.393 | error | by controller[0]: at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2020-01-28 11:21:28.393 | error | by controller[0]: at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
Caught | 2020-01-28 11:21:28.393 | error | by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
Caught | 2020-01-28 11:21:28.393 | error | by controller[0]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2020-01-28 11:21:28.393 | error | by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
Caught | 2020-01-28 11:21:28.393 | error | by controller[0]: at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
Caught | 2020-01-28 11:21:28.393 | error | by controller[0]: at Socket.adapter.getForeignState (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1991:68)
Caught | 2020-01-28 11:21:28.392 | error | by controller[0]: TypeError: Cannot read property 'bind' of undefined
lovelace.0 | 2020-01-28 11:21:28.370 | info | cleaned everything up...
lovelace.0 | 2020-01-28 11:21:27.365 | info | cleaned everything up...
lovelace.0 | 2020-01-28 11:21:27.363 | error | at Manager.ondata (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:322:16)
lovelace.0 | 2020-01-28 11:21:27.363 | error | at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
lovelace.0 | 2020-01-28 11:21:27.363 | error | at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
lovelace.0 | 2020-01-28 11:21:27.363 | error | at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
lovelace.0 | 2020-01-28 11:21:27.363 | error | at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
lovelace.0 | 2020-01-28 11:21:27.363 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
lovelace.0 | 2020-01-28 11:21:27.363 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
lovelace.0 | 2020-01-28 11:21:27.363 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
lovelace.0 | 2020-01-28 11:21:27.363 | error | at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
lovelace.0 | 2020-01-28 11:21:27.363 | error | at Socket.adapter.getForeignState (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1991:68)
lovelace.0 | 2020-01-28 11:21:27.363 | error | TypeError: Cannot read property 'bind' of undefined
lovelace.0 | 2020-01-28 11:21:27.362 | error | uncaught exception: Cannot read property 'bind' of undefined
lovelace.0 | 2020-01-28 11:21:26.312 | info | http server listening on port 8091
lovelace.0 | 2020-01-28 11:21:26.168 | info | starting. Version 1.0.8 in /opt/iobroker/node_modules/iobroker.lovelace, node: v8.16.0

**Comment by b3ster** [comment]
In the meantime I have updated the system:
Node.js :: v10.18.1
admin :: 3.7.8
js-controler: >2.0

**Comment by b3ster** [comment]
logoutput directly from container:

TypeError: Cannot read property 'bind' of undefined
    at adapter.getForeignState (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1991:68)
    at client.get (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:580:17)
    at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by b3ster** [comment]
I found the issue if you see a problem like that please check your Entities! In my case, one of them was broken, after removing all Entities step by step I found the broken one.
Better logging for that exception may help in the future,...

**Comment by Garfonso** [comment]
This was my fault. Not really an issue with your entities, but a bug in the code. It is fixed in 7fb9153, so since 1.0.16.
Can be closed.
