### ISSUE TITLE
Adapter startet nicht

### ISSUE THREAD

**Issue by snookerap** [ioBroker/ioBroker.lovelace#72]
Edit: scheinbar läuft die Version 1.0.8 nicht, 1.0.6 funktioniert komischerweise

Adapter startet nicht und gibt folgenden Fehler im LOG.
Bitte um Hilfe.

host.ubuntu-iobroker | 2020-01-29 09:17:31.055 | info | instance system.adapter.lovelace.0 started with pid 1774
-- | -- | -- | --
host.ubuntu-iobroker | 2020-01-29 09:17:01.047 | info | Restart adapter system.adapter.lovelace.0 because enabled
host.ubuntu-iobroker | 2020-01-29 09:17:01.047 | info | instance system.adapter.lovelace.0 terminated with code 0 (NO_ERROR)
host.ubuntu-iobroker | 2020-01-29 09:17:01.047 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:68:7)
host.ubuntu-iobroker | 2020-01-29 09:17:01.047 | error | Caught by controller[0]: at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
host.ubuntu-iobroker | 2020-01-29 09:17:01.047 | error | Caught by controller[0]: at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
host.ubuntu-iobroker | 2020-01-29 09:17:01.046 | error | Caught by controller[0]: at client.get (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:491:17)
host.ubuntu-iobroker | 2020-01-29 09:17:01.046 | error | Caught by controller[0]: at adapter.getForeignState (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1991:68)
host.ubuntu-iobroker | 2020-01-29 09:17:01.046 | error | Caught by controller[0]: TypeError: Cannot read property 'bind' of undefined
lovelace.0 | 2020-01-29 09:17:00.533 | info | (1755) Terminated (NO_ERROR): Without reason
lovelace.0 | 2020-01-29 09:17:00.532 | info | (1755) terminating
lovelace.0 | 2020-01-29 09:17:00.486 | info | (1755) cleaned everything up...
lovelace.0 | 2020-01-29 09:17:00.485 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
lovelace.0 | 2020-01-29 09:17:00.485 | error | at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
lovelace.0 | 2020-01-29 09:17:00.485 | error | at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
lovelace.0 | 2020-01-29 09:17:00.485 | error | at client.get (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:491:17)
lovelace.0 | 2020-01-29 09:17:00.485 | error | at adapter.getForeignState (/opt/iobroker/node_modules/iobroker.lovelace/lib/server.js:1991:68)
lovelace.0 | 2020-01-29 09:17:00.485 | error | (1755) TypeError: Cannot read property 'bind' of undefined
lovelace.0 | 2020-01-29 09:17:00.484 | error | (1755) uncaught exception: Cannot read property 'bind' of undefined
lovelace.0 | 2020-01-29 09:16:59.916 | info | (1755) http server listening on port 8091
lovelace.0 | 2020-01-29 09:16:59.886 | info | (1755) starting. Version 1.0.8 in /opt/iobroker/node_modules/iobroker.lovelace, node: v10.18.0

**Comment by Garfonso** [comment]
Ist vermutlich gefixt? Sonst bitte mit aktueller Version neues issue. Danke.
