### ISSUE TITLE
Manually created light/dimmer entities do not work

### ISSUE THREAD

**Issue by Coalado** [ioBroker/ioBroker.lovelace#75]
**Describe the bug**  
If you manually create an entity for a dimmer value (like 0-255) , it simply does not work. 

**Expected behavior**  
Dimming cards should work as expected an set the *.bri value.

**Versions:**  
 - Adapter version: Latest 1.0.9 Github

The code in server.js/_processManualEntity cannot work.

`    entity.context.ATTRIBUTES = [{attribute: 'brightness', getId: id}]; `

misses setId and max values which are both required for _setLightAdvancedAttributesToIOBStates

Moreover, _parseLightAdvancedOn sets true to the brightness state:

```
 this.adapter.setForeignState(entity.context.STATE.setId, true, false, {user}, () =>
                            this._setLightAdvancedAttributesToIOBStates(data, entity, user,resolve, reject));
```

` entity.context.ATTRIBUTES = [{attribute: 'brightness', getId: id,setId:id,max:iobMaxValue}];`
party solves the issue, but only because  setting true to a number field is ignored.
I guess the code should somehow set the *.on state to true before setting the *.bri state to the correct brightness value.

**Comment by Garfonso** [comment]
Could you please check if this is still an issue. I think it should be corrected with 1.1.0
