### ISSUE TITLE
Device historical status chart is not displayed

### ISSUE THREAD

**Issue by yaming116** [ioBroker/ioBroker.lovelace#79]
**Describe the bug**  
Click on 'entity'，Display the historical status information of the device, but the chart does not show, I found that the back-end related interfaces have been coded, but the front-end page has not initiated any requests

http://ip/api/history/period/2020-02-09T06:23:43.963Z?filter_entity_id=switch.espurna_3d925f&end_time=2020-02-10T06:23:43.963Z
 
1. Click on 'entity'

**Screenshots & Logfiles**  
* iob
![image](https://user-images.githubusercontent.com/2171071/74125507-7c7d5e00-4c10-11ea-9f8a-6b4403aded5a.png)

* ha
![image](https://user-images.githubusercontent.com/2171071/74125545-99199600-4c10-11ea-86cd-6453463dd3f5.png)

**Versions:**  
 - Adapter version: 1.0.6

**Comment by Garfonso** [comment]
Is added in 1.2.2 (currently in dev build, you can install from `Garfonso/iobroker.lovelace#dev` if you want to test).
