### ISSUE TITLE
Feature Request: eigene Bilder hochladen

### ISSUE THREAD

**Issue by Pendora2017** [ioBroker/ioBroker.lovelace#81]
Ich würde mich freuen, wenn eine Möglichkeit geschaffen werden würde, eigene Bilder in lovelace reinzuladen. Vielleicht genau so, wie die Themes oder die kundenspezifischen Karten ein Menüpunkt direkt in der Adapter Konfiguration.

Die manuelle Geschichte über SSH / SCP wird ja leider bei einem Adapter Update wieder gelöscht.

**Comment by Garfonso** [comment]
Du kannst Bilder bei den Karten hochladen. Ist sogar in der Readme beschrieben und der richtige Weg für eigene Bilder.

Die sind dann mit Pfad zB /cards/Bild.jpg nutzba.
