### ISSUE TITLE
Configuration Option in UI Menu disappeared

### ISSUE THREAD

**Issue by domi1893** [ioBroker/ioBroker.lovelace#85]
Hi,

I got the following problem with the Lovelace instance:  after changing something in the instance settings the button for configuration in der UI disappears. I can´t get it back. If i make a new instance without changing the settings, the configuration in UI is possible. For example: Only changing the Port and saving it let the config disappear and only the help option is left in the UI.

Node JS: 10.19.0
NPM: 6.13.4
JS-Controller: 2.2.9
Lovelace: 1.0.12 (But same behavior with different Versions)
OS: Linux (Docker Container on a Syno)

Thanks in Advance,

Domi

**Comment by Garfonso** [comment]
Wait a minute, I think, I see this here, too. You see only the "help" link in the menu, right? Did you have authentication enabled?

**Comment by DaveMe81** [comment]
Hello!
I got the same issue: I see only "help" in the menu. I have authentication of. I use not the admin account. I tried w/ and w/o authentication, both habe same issu.

ideas?

**Comment by Garfonso** [comment]
I did not yet find the chance to check the code, but I suspect that the adapter somewhere checks if it has write access to lovelace.0/configuration (which it needs. It needs to be able to change the object in order to store configuration changes). Either it does not have access to that object in some scenarios or the check is errornous... not sure, yet... 

You could test if the menu shows up if you do use the admin account.

TBH I'm not really familar with ACL in ioBroker (yet)... so maybe you can check access rights for the objects in lovelace.0 for your target user, too and experiment a bit with that. (But that is a wild guess)

**Comment by agross** [comment]
For me the "Configure UI" option only shows up when I'm logged in as the `admin` user. Any other user, even with admin access (i.e. members of `system.group.administrator`), cannot configure the UI.

**Comment by Garfonso** [comment]
> 
> 
> For me the "Configure UI" option only shows up when I'm logged in as the `admin` user. Any other user, even with admin access (i.e. members of `system.group.administrator`), cannot configure the UI.

This is definitively the case. There is a check for user == admin hardcoded in server.js. 
I am not sure that this is the best way to handle this. Maybe that should be extended to users in the admin group? Or all users with write access to the configuration object? Or an additional select in the configuration for a user-group that is a Lovelace-Admin? Or is using admin sufficient?

**Comment by agross** [comment]
> Or all users with write access to the configuration object

I'd say this is the best option. Admins likely can write that object. A user may create custom groups that are allowed to write the config object as well.

**Comment by Garfonso** [comment]
Write access is not easy to check, right now. So what I do is to check the ACL part of the configuration object. Users will become admin, if the either own the object or if they are members of the owning group. 

During that improvement I also fixed some possible issues with js-controller 3.2. Usernames should now be checked against the Name attribute of a user and not the id (change in js-controller 3.2). With this change also the username is not case sensitive.
