### ISSUE TITLE
Weather Card - keine Icons

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.lovelace#9]
Ich habe yr.no als Daten-Lieferant getestet und nutze derzeit Weatherunderground.
Bei beiden Daten-Quellen bekomme ich in der Weather Card keine Icons angezeigt.

![](https://i.imgur.com/Skyjt3X.jpg)

**Comment by sigi2345** [comment]
Was hast du als Entities eingetragen?
Ich glaube der Fehler ist bekannt, geht bei mir auch nicht.

**Comment by dontobi** [comment]
Da ich derzeit unterwegs bin, musste ich einen Screenshot machen. Kann den Code nicht raus Kopieren.![](https://i.imgur.com/8HQrlV2.jpg)

**Comment by GermanBluefox** [comment]
Die Ikons von lovelace sind nicht mit IoB kompatibel.
Die Lösung ist ziemlich kompliziert. Entwider PR gegen lovelace to support custom icons, oder mapping von hass icons zu IoB (unerwünscht).

**Comment by GermanBluefox** [comment]
auf github: 
![image](https://user-images.githubusercontent.com/4582016/61806753-8ab48a00-ae38-11e9-80ad-73458dd0d2aa.png)

**Comment by dontobi** [comment]
Ich werde es nachher oder spätestens am Wochenende testen. Danke schon Mal für deine Mühe.

**Comment by dontobi** [comment]
Ich habe das Update getestet und komplett funktionsfähig ist das ganze bei mir noch nicht. Ich verwende den yr Adapter und habe alles eingestellt. Icons bekomme ich angezeigt, aber Bilder sagen mehr...

![objekte](https://user-images.githubusercontent.com/19261667/61850773-62b73c00-aeb5-11e9-8984-95510b4ceab0.JPG)
![Card](https://user-images.githubusercontent.com/19261667/61850779-68ad1d00-aeb5-11e9-9540-3869b44af4f5.JPG)
![Extras](https://user-images.githubusercontent.com/19261667/61850796-6e0a6780-aeb5-11e9-8e14-243ba2635eac.JPG)

**Comment by dontobi** [comment]
Mit Weatherunderground sieht es so aus...
 ![](https://i.imgur.com/Qv9AQsV.jpg)

**Comment by Garfonso** [comment]
Wetter Icons gehen mit den letzten versionen im latest.
