### ISSUE TITLE
Shutter (Homematic IP Wired Device)

### ISSUE THREAD

**Issue by Benni08** [ioBroker/ioBroker.lovelace#90]
Sorry for asking here,

but i can't find any Solution, to put a Simple Shutter in Lovelace. Is there no Possibilty?

Best Regards
Ben

**Comment by Garfonso** [comment]
Personally I use input_number and some switches to control my covers which works fine. So my question would be what you are expecting and how that is not working for you.

From what I see in the code there is support for automatic detection of devices of type "blind". Could you install the [devices adapter](https://github.com/ioBroker/ioBroker.devices) (if not already installed) and have a look at the device tab in admin (might be necessary to activate). Do you see devices of type blind there?
If not you might want to try to add them using the devices adapter (which will create devices in alias.0 with aliases pointing to the objects you can select in devices adapter and set up correct roles and types). 

From further inspection of the code I see that a device of type blind will be converted into an input_number entity. It will not even create a stop switch. Hm. That probably needs improvement. So what would you expect to happen? Is there a card for cover/shutter/blinds? I see there is a [cover entity](https://developers.home-assistant.io/docs/entity_cover) in HomeAssistant which should be used as entity for devices of type blind.

But I have not yet looked into what advantages that might have above a simple input_number which is currently used. Of course that would be a breaking change for all current users, so it should have some benefit. So I'm really interested in hearing what you would expect here and what you want to achieve.

**Comment by Garfonso** [comment]
BTW: the easiest thing to do is to create a manual input_number entity for the position state of your shutter (click on the wrench symbol next to the object in ioBroker).

**Comment by Benni08** [comment]
At First, thank you for your fast Reply.

At Second, be aware of my Bad English.

I've just started yesterday to setup a VM for trying ioBroker. So maybe i was a litte bit to Fast to start this issue. When configuring IOBroke everything works so nice (autmatic look up for Devices and setup of the Instanes). After that I've just looked for a good and quite Nice Visu.

But back to Topic.

After a litte bit trying i've just found out, what you're saying (just using a input_number Device).

But would that be realy a breaking change for all current users, if just creating a new Devicetype named Shutter. The input_number devices should be working to, or not?

I think a Shutter would be easy to use for somebody, how just started to work with ioBroker. It would be a intutive use.

So when i look at all Visu's for IOBroker, in my opinion the lovelace visu brings the best user feeling (css for mobile user's etc.).

So maybe i found a Bug when using a Enumeration. I've just had a Entitiy with the german word for Kitchen. (The Entity was called input_number.Küche). When trying to add to a Enumeration, a Error is shown, wich depends on the "Ü". And when using a Enumeration, it would be nice to configure an Icon and a Title (So the Entity Name could be have a good Description of the Device). In my opinion it would be the Best solution, to Use german own Charactes in Title, and not in Entitynames... but you don't have the possibilty to change the Entityname in Enumerations).

in LoveLace i can even use own Icons. Where can the Icons be found on the Linux System, wich path could be used for it.

Best regards.
Ben

**Comment by Benni08** [comment]
And by the way, is there anywhere a Description to setup the Yaml for Lovelace, to use own CSS?

**Comment by Garfonso** [comment]
> But would that be realy a breaking change for all current users, if just creating a new Devicetype named Shutter. The input_number devices should be working to, or not?

Currently, if a device of type "blind" is detected in ioBroker (you can find detected devices in the devices tap, if the device-adapter is installed, which I recommend when working with lovelace) it will automatically create an entity inputer_number for it. 
If we change that behaviour and make the entity of type cover, entity_ids for all existing users might change and require updates to their vis. So this is breaking.
If you manually configure the entity, then that is not an issue, of course.
 
> So maybe i found a Bug when using a Enumeration. I've just had a Entitiy with the german word for Kitchen. (The Entity was called input_number.Küche). When trying to add to a Enumeration, a Error is shown, wich depends on the "Ü". And when using a Enumeration, it would be nice to configure an Icon and a Title (So the Entity Name could be have a good Description of the Device). In my opinion it would be the Best solution, to Use german own Charactes in Title, and not in Entitynames... but you don't have the possibilty to change the Entityname in Enumerations).

In the latest versions the Umlaut will be replaced. 
You can change the name in Enumartions, too, by using the code editor. See lovelace examples or the (long and horrifying) [thread in the forum](https://forum.iobroker.net/topic/22781/test-adapter-lovelace-v0-2-x). That is in fact where nearly all information for the lovelace adapter is burried, which is probably true for your other questions as well.

> And by the way, is there anywhere a Description to setup the Yaml for Lovelace, to use own CSS?

Do you mean the "Theme" tab in instance settings?

**Comment by Benni08** [comment]
> Do you mean the "Theme" tab in instance settings?

Yeah Right, but i 'even think i can find this information in the thread, so i have to search.

Thank you for the Info.
