### ISSUE TITLE
Lovelace Backup 

### ISSUE THREAD

**Issue by ipod86** [ioBroker/ioBroker.lovelace#92]
Hello, first sorry fit my bad englisch. 

I've been using Lovelace for a while and I think it's pretty cool.  
However, I have a question.  
I make regular iobroker backups with BackupIt.  However, this does not contain my own images for lovelace.  I save them under opt / iobroker / node_modules / iobroker.lovelace / hass_frontend / static / images / myimages.
 Is it possible to adapt the adapter to include this Folder in the backup?

**Comment by Garfonso** [comment]
Is there a reason why you are not using this method: https://github.com/ioBroker/ioBroker.lovelace#own-images 
Image URL then is /cards/image.jpg

This might already help with backup situation if backitup also backs up files in /opt/iobroker/iobroker-data.

**Comment by Apollon77** [comment]
Exactly ... the way to store own images in a node_modules directory is not supported (also because eaach and every update will remove them
