### ISSUE TITLE
Some Sensor Entity ID show old values

### ISSUE THREAD

**Issue by MarcelMertens** [ioBroker/ioBroker.lovelace#93]
Hello,

i have some entites (aqara temperatursensor) configured as "sensor" which is not updated in Lovelace.

![grafik](https://user-images.githubusercontent.com/20799825/84941188-4b8ec780-b0e1-11ea-84e8-b12f8cf629c2.png)
Object browser shows that the valie was updated about 40min ago:
![grafik](https://user-images.githubusercontent.com/20799825/84941404-a7595080-b0e1-11ea-95d4-d470eb68d4e3.png)

When restarting the lovelace instance, the latest value is used

Using Lovelace 1.10

**Comment by MarcelMertens** [comment]
Addition:
Here are all datapoints (10 newer points)

![grafik](https://user-images.githubusercontent.com/20799825/84941940-644bad00-b0e2-11ea-82d6-06b977aa5363.png)

**Comment by Garfonso** [comment]
A few questions come to mind:
- Is ack true or false when the value updates?
- Do you see this with all sensors / other datapoints or only deconz? 
  - is it somehow possible that deconz deletes / recreates the objects for any reason (like restart of adapter / rebuilding zigbee network)?
- Does it also help to refresh the UI in the Browser?

**Comment by MarcelMertens** [comment]
Sorry, was'nt aware of this issue, but in the last day i noticed the same issue again.

In my new situation all values are set from javascript:

I have several datapoints for controlling my AC:
![grafik](https://user-images.githubusercontent.com/20799825/96731654-cc274280-13b7-11eb-89bf-3610b8848993.png)
![grafik](https://user-images.githubusercontent.com/20799825/96731560-ac901a00-13b7-11eb-9486-552e6c7a9827.png)

The ACs are actual controlled by the Panasonic Cloud Service, so i wrote two scripts which syncronizes IObroker <> Cloud Service. 
The ACs could be also controlled via a Mobile App or direct via Infrared Remote.

GetStates Script (Runs every 30sec):
Reads the Values from the Cloud Service and sets the States in IObroker with ACK: True

ControlDevice (Runs every time on of the States in IObroker has changed):
If i change a IObroker state for the AC, the script runs and pushes the change to the Cloud Service. The Cloud Service pushed this change to the AC device.

This means, that states keep "Ack: False" until the "GetStates" runs and writes the current value from the cloud back to i broker.

Example:
1. Restarted Lovelace adapter, everything fine. Temperature Set to 19°C
![grafik](https://user-images.githubusercontent.com/20799825/96733419-b6b31800-13b9-11eb-8088-8741053bcf4f.png)

2. Changed Temperature via Lovelace to 25°C, lovelace updates state, but state is Ack: False. Control-Device script runs and pushes the new set value to the cloud service. AC changes temp to 25°C
![grafik](https://user-images.githubusercontent.com/20799825/96733602-ef52f180-13b9-11eb-8072-dfe10c066136.png)
But value in lovelace stays at 19°C

3. After several seconds, Get-States script reads the new set device back from the cloud and updates the state. Value still 25°C, but ACK: True
![grafik](https://user-images.githubusercontent.com/20799825/96733866-35a85080-13ba-11eb-995b-8e67d2789ba9.png)
But value in lovelace stays at 19°C

Only restarting the adapter helps to get the correct values show up....
I tried a different browser, different device

**Comment by MarcelMertens** [comment]
Ok, just digged a bit deeper in this topic (I'm not a iobroker developer, so don't know if this is interesting):
I switched the lovelace adapter to "SILLY" Logging and see that there are never "States user redis pmessage.." for the states published. On all other states i see "States user redis pmessage.." every then and now, but for my datapoints is nothing.

On the start of lovelace i see that there is a subscribtion on all states


```
lovelace.0 | 2020-10-22 09:16:14.995 | debug | (29238) IoB Subscribe on javascript.0.PanasonicAC.CS-TZ20WKEW+4756812442.fanSpeed
lovelace.0 | 2020-10-22 09:16:14.994 | debug | (29238) IoB Subscribe on javascript.0.PanasonicAC.CS-TZ20WKEW+4756812442.ecoMode
lovelace.0 | 2020-10-22 09:16:14.993 | debug | (29238) IoB Subscribe on javascript.0.PanasonicAC.CS-TZ20WKEW+4756812442.operationMode
lovelace.0 | 2020-10-22 09:16:14.993 | debug | (29238) IoB Subscribe on javascript.0.PanasonicAC.CS-TZ20WKEW+4756812442.temperatureSet
lovelace.0 | 2020-10-22 09:16:14.992 | debug | (29238) IoB Subscribe on javascript.0.PanasonicAC.CS-TZ20WKEW+4756812442.operate
```

If i change one of the values, the only thing i see in the log is:


`lovelace.0 | 2020-10-22 09:28:42.288 | debug | (29238) set_value: javascript.0.PanasonicAC.CS-TZ20WKEW+4756812442.temperatureSet = 21`


If my "Get-States" script updates the values nothing happens

**Comment by MarcelMertens** [comment]
Ok, more to come:

I changed my Get-States script (which also creates the states if not existing) and instead of using the deviceGuid ("PanasonicAC.CS-TZ20WKEW+4756812442") the script uses the deviceName (Buero) instead for the folder name.
So the new State name is

javascript.0.PanasonicAC.Buero.operate
instead of
javascript.0.PanasonicAC.CS-TZ20WKEW+4756812442.operate

Also the lovelace Entity is now called
"input_boolean.PanasonicAC_Buero_operate".

And now its working fine.

```
lovelace.0	2020-10-22 09:47:31.624	silly	(29238) States user redis pmessage javascript.0.PanasonicAC.Buero.operate/javascript.0.PanasonicAC.Buero.operate:{"val":false,"ack":true,"ts":1603352851612,"q":0,"from":"system.adapter.javascript.0","
lovelace.0	2020-10-22 09:47:31.622	silly	(29238) States user redis pmessage javascript.0.PanasonicAC.Buero.ecoMode/javascript.0.PanasonicAC.Buero.ecoMode:{"val":0,"ack":true,"ts":1603352851612,"q":0,"from":"system.adapter.javascript.0","user
lovelace.0	2020-10-22 09:47:31.619	silly	(29238) States user redis pmessage javascript.0.PanasonicAC.Buero.fanSpeed/javascript.0.PanasonicAC.Buero.fanSpeed:{"val":0,"ack":true,"ts":1603352851612,"q":0,"from":"system.adapter.javascript.0","us
lovelace.0	2020-10-22 09:47:31.617	silly	(29238) States user redis pmessage javascript.0.PanasonicAC.Buero.operationMode/javascript.0.PanasonicAC.Buero.operationMode:{"val":3,"ack":true,"ts":1603352851612,"q":0,"from":"system.adapter.javascr
lovelace.0	2020-10-22 09:47:31.614	silly	(29238) States user redis pmessage javascript.0.PanasonicAC.Buero.temperatureSet/javascript.0.PanasonicAC.Buero.temperatureSet:{"val":19,"ack":true,"ts":1603352851611,"q":0,"from":"system.adapter.java
javascript.0	2020-10-22 09:47:17.526	info	(30912) script.js.common.PanasonicAC.PanasonicAC_ControlDevice: State Change detected . State: 'javascript.0.PanasonicAC.Buero.temperatureSet' Old Value: [23] New Value: [19]
lovelace.0	2020-10-22 09:47:17.526	silly	(29238) States user redis pmessage javascript.0.PanasonicAC.Buero.temperatureSet/javascript.0.PanasonicAC.Buero.temperatureSet:{"val":19,"ack":false,"ts":1603352837520,"q":0,"from":"system.adapter.lov
lovelace.0	2020-10-22 09:47:17.511	debug	(29238) set_value: javascript.0.PanasonicAC.Buero.temperatureSet = 19
```

So it looks like a problem with the length or characters ("+") insight name name ot the state or entity?

**Comment by Garfonso** [comment]
Uhh... great findings. 😄 
I do not know the parts involved with the statedb and subscription system, I'll ask around if someone else has an idea. Maybe there is some issue somewhere deep below ( @Apollon77 )? Or + or - signs should be forbidden in IDs (they currently are [allowed](https://www.iobroker.net/#en/documentation/dev/objectsschema.md) and not even discouraged).

**Comment by Apollon77** [comment]
Maybe an encoding issue on Browser side? + is often converted in urldecode to a " "?
