### ISSUE TITLE
input_select states appears to be parsed incorrectly

### ISSUE THREAD

**Issue by grisia** [ioBroker/ioBroker.lovelace#96]
Maybe it's my fault but manually creating an input_select state with:

```
createState("test", 0, {def:    0,
			min:    0,
			max:    6,
			type:   'number',
			read:   true,
			write:  true,
			states: '0:JEA; 1:WOWO; 2:NOP',
			role:   'media.state',
			desc:   'Player handling',
			name:   'MyPlayer'
			});`
```

[ioBroker.javascript.md: on - Subscribe on changes or updates of some state](https://github.com/ioBroker/ioBroker.javascript/blob/bbcf8abd5b1a8de978f6112a0220e732508fa11a/docs/en/javascript.md#on---subscribe-on-changes-or-updates-of-some-state)
[Erzeugen von Datenpunkten mit Voreinstellungen](https://forum.iobroker.net/topic/911/erzeugen-von-datenpunkten-mit-voreinstellungen/2)

lovelace will parse the attributes like that

```
friendly_name: MyPlayer
initial: J
options: 0,:,J,E,A,;, ,1,:,W,O,W,O,;, ,2,:,N,O,P
```

So using this input_select state every letter is an option in lovelace. (In the iobroker objects grid only the first option is displayed correctly...)

I just tried a little and the following syntax will also be correctly interpreted by the iobroker objects grid (all options are displayed correctly):

```
createState("test", 0, {def:    0,
			min:    0,
			max:    6,
			type:   'number',
			read:   true,
			write:  true,
			states: '{"0":"JEA", "1":"WOWO", "2":"NOP"}',
			role:   'media.state',
			desc:   'Player handling',
			name:   'MyPlayer'
			});
```

lovelace will show as expected this:

```
friendly_name: MyPlayer
initial: "
options: {,",0,",:,",J,E,A,",,, ,",1,",:,",W,O,W,O,",,, ,",2,",:,",N,O,P,",}
```

But maybe here we could wrap this with "JSON.parse"?

```
-------------------------------- lib/server.js --------------------------------
index bc7dcdb..482529a 100644
@@ -2454,12 +2454,12 @@ class WebServer {
             }
             else if (entityType === 'input_select') {
                 if (obj.common.states ) {
-                    entity.attributes.options = Object.values(obj.common.states);
-                    entity.context.STATE.map = obj.common.states ;
+                    entity.attributes.options = Object.values(JSON.parse(obj.common.states));
+                    entity.context.STATE.map = JSON.parse(obj.common.states) ;
                 }
                 this.adapter.getForeignState(id, (err, state) => {
-                    if (obj.common.states && obj.common.states[state.val]) {
-                        entity.attributes.initial = obj.common.states[state.val];
+                    if (obj.common.states && JSON.parse(obj.common.states)[state.val]) {
+                        entity.attributes.initial = JSON.parse(obj.common.states)[state.val];
                     }
                 });
             }
```

_JS controller: v3.1.6
Node.js: v12.18.2
NPM: v6.14.5_

**Comment by Garfonso** [comment]
If you make it an object, as per docs here https://www.iobroker.net/#de/documentation/dev/objectsschema.md it will work.

I. E. remove the quotes in your second try.

It seems to me that string was allowed (current schema does clearly say "object") and still is used. So maybe we need to add support for that, too.

**Comment by Garfonso** [comment]
I added a workaround for the first version, which seems to be still quite common although not advertised for some time in 1.2.5.
